### ISSUE TITLE
ctx.game.tab(Game.Tab.INVENTORY)

### ISSUE THREAD

**Issue by MookyMan** [powerbot/powerbot#1000]
ctx.game.tab(Game.Tab.INVENTORY) returns out of bounds array when the deposit box is open because it removes the ability to click the invo button.

[SEVERE] java.lang.ArrayIndexOutOfBoundsException: -4 

![Error](https://dl.dropboxusercontent.com/u/148329451/Errors/depositbox.png)

**Comment by Timer** [comment]
Fixed
