### ISSUE TITLE
GeItem

### ISSUE THREAD

**Issue by CodeRedRS** [powerbot/powerbot#1001]
Can we get an old school version of GeItem?

**Comment by Strikegently** [comment]
There is no official RuneScape API for the OSRS Grand Exchange.

**Comment by CodeRedRS** [comment]
I was unaware that there was official api for RS3. I figured the way it was working for rt6 was just using a form a html scraping because all you need to pass is the item id and look it up on the grand exchange.

http://services.runescape.com/m=itemdb_oldschool/viewitem?obj={ItemId}

**Comment by Strikegently** [comment]
oh, apparently there is an OS API. My mistake.

http://services.runescape.com/m=itemdb_oldschool/api/catalogue/detail.json?item=[id]

**Comment by Strikegently** [comment]
https://gist.github.com/Strikegently/5cd8c2f42541765238ec

**Comment by Paris** [comment]
Added for the next version.
