### ISSUE TITLE
Game mode selection option

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1003]
The client should ask the user which game mode to start the client in, rather than loading RS3 by default.

**Comment by Strikegently** [comment]
Requesting milestone be changed to 7018. About a third of all issues in Client Support are regarding this.

**Comment by Paris** [comment]
The next version will remember the last game mode played and auto-startup into that one.

**Comment by AnthonyOSX** [comment]
@Paris Remembering the default is useful but please also implement an explicit selector (maybe a "Game Selector" menubar item that also handles closing the existing applet viewer?). Your solution does not help mitigate the main issue of users not even understanding how to run a different game mode in the first place.

**Comment by rs-sliske** [comment]
@AnthonyOSX explicit stuff is rubbish, what your really need is a sliske version selector http://www.powerbot.org/community/topic/1296157-/

**Comment by AnthonyOSX** [comment]
@rs-sliske This would only be useful if it was packaged with the main application. Most users only bother coming on the forums if they have an issue or error, and even then they'll be hard pressed to search the developers section for a game switcher.

**Comment by rs-sliske** [comment]
https://github.com/powerbot/powerbot/issues/1112

**Comment by AnthonyOSX** [comment]
@rs-sliske The API does not handle bot internals.
