### ISSUE TITLE
Forum Data API/ORM

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#1009]
I'd like for some data to be exposed in some sort of web api (restful would be ideal). You could also create some small scale ORM in the client for scripts to make use of this data. This information could be used to create personalized dynamic signatures and better associated script usage data with a unique forum user.  It's nothing not already exposed by regular forum usage so I don't see an issue with providing access to it through a web api and an ORM within the client.
```
Site
     Online Users (number)
     Ranks (see below for desired information)
User (searchable by id or name)
     Profile Picture
     Username
     Online Status
     Join Date
     Gender
     Ranks
Rank
     Tag Name
     Tag Icon URL
```

**Comment by Paris** [comment]
This doesn't have much commercial value so we won't be implementing it.
