### ISSUE TITLE
ORM/MySQL Database Support

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#1011]
Currently, the client requires additional drivers to make complete usage of JDBC with MySQL databases. Providing support for JDBC would allow script writers to fully deploy an ORM to make interacting with their database(s) very simple and efficient. Thus, script writers would have further access to explore support things such as dynamic signatures, high scores, etc.. 

mysql-connector-java-5.1.36.jar is what I currently use on various other projects (available on Maven) which is necessary for connecting with MySQL databases. If you want to support in-memory databases, HSQLDB is used for a lot of unit testing around the industry, hsqldb-2.3.3.jar (also available on Maven).

To augment this addition, if considered, I'd fully recommend adding additional support for Hibernate, hibernate-core-4.2.0.Final.jar (also available on Maven).

**Comment by IITC** [comment]
Since Joe loves NoSQL, Hibernate also supports NoSQL databases via their OGM, org.hibernate.ogm:hibernate-ogm-core:4.2.0.Final.

**Comment by Paris** [comment]
This is unsuitable for a desktop application. It should communicate with a web service for database backend functionality instead.
