### ISSUE TITLE
Add missing bank npcs

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1018]
Missing npcs were dumped from cache and filtered by "Bank" action. I've manually checked them and they are all valid.
```
902, 3794, 3795, 4296, 5383, 5898, 11299, 13455,
16604, 16947, 18308, 19916, 19917, 19918,  21390,
21391, 21392, 21393
```

**Comment by rs-sliske** [comment]
http://sliske.uk/img/captures/0d5425.png 
902 - mage arena banker
4296 - warrior guild banker
5353 - banker in lair of tarn razorlor (you have to pay to use this guy)
5898 - extra banker on lunar isle after starting dream mentor

**Comment by Strikegently** [comment]
Because of Darkscape and Deadman modes (#974), I think it would be more prudent to just make the Bank API check for Npcs/Objects with bank actions instead of relying on IDs.

**Comment by Timer** [comment]
Done
