### ISSUE TITLE
#select(int) for GroundItem

### ISSUE THREAD

**Issue by iitc** [powerbot/powerbot#1019]
It'd be convenient to make use of the `select(int)` that game object have made available to them for other applicable entities.

**Comment by PatriqDesigns** [comment]
Support!

**Comment by Timer** [comment]
This can only be applied to Ground Items. Use within for Npcs/Players.

**Comment by IITC** [comment]
Could you just use the local x/y of the accessor classes so that you avoid creating excess wrappers?

**Comment by Timer** [comment]
I guess if you're doing this for the memory footprint .. I could try.
Open a separate issue for just Npcs/Players since it's a different solution.

**Comment by Timer** [comment]
done ~
