### ISSUE TITLE
[Bot] Null Internal Error

### ISSUE THREAD

**Issue by ChainedHope** [powerbot/powerbot#1021]
```
[SEVERE] java.lang.NullPointerException 
z.CoM7.<init>(ue:323)
z.BB.run(mi:41)
```

Happens when trying to start any script right after stopping one. Doesnt happen everytime, but most of the time.

**Comment by Timer** [comment]
This looks like partly the script.
```[SEVERE] java.lang.NullPointerException 
z.CoM7.(ue:323)
org.powerbot.gui.BotMenuBar$13$1.run(BotMenuBar.java:286)```

**Comment by ChainedHope** [comment]
I checked my script for nulls and tried catching them but im not seeing any NPE's and its still giving the error occasionally. It might be because of how im implementing the GUI (theres a simple and an advanced gui depending on the usage). I'm going to see if it happens if I drop the JMenu from my current revision.

**Comment by Timer** [comment]
Are you starting your UI on the event queue?

**Comment by ChainedHope** [comment]
Yeah I am.

#in start()
EventQueue.invokeLater(new Runnable(){

public void run(){
g_simple = new GUISimple();
g_simple.setVisible(true);
g_advanced = new GUIAdvanced();
g_advanced.setVisible(false);
g_advanced.setLookBack(g_simple);
g_simple.setLookBack(g_advanced);
}
})

setLookBack just links them so that they can change each other's visibility through the actionListener on the JMenuItem.

**Comment by ChainedHope** [comment]
I just tried dropping the advanced gui and removing the JMenu and I recieved the same error after stopping and starting the script a few times. I'm about to wrap the script in a try/catch with a printed stacktrace on NPE's to see if I can figure out whats happening.

**Comment by Paris** [comment]
This seems like a script specific issue.
