### ISSUE TITLE
Detecting legacy combat mode.

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1022]
Right now, we have a method to determine if the user is using the legacy interface, but not if they are using the legacy combat system.

Maybe just `combatBar.isAvailable()`, since the point is to determine if they have a combat bar (not legacy).

**Comment by ArtificialPB** [comment]
I've implemented this in my framework by checking if minimize/maximize combat bar button is visible. 
Here are textures of those two buttons:
```
private static final int COMBATBAR_MINIMIZE_TEXTURE = 18612,
COMBATBAR_EXPAND_TEXTURE = 24004;
```

**Comment by Timer** [comment]
Added #legacy.
