### ISSUE TITLE
CombatBar + Legacy Interface doesn't work

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1024]
Very related to #1022.

When in legacy interface mode, the combat bar query always returns empty. The widgets are the same, the varps are the same (View > Abilities actually shows all of the ability information correctly) so I assume you have a preemptive `hud.legacy()` check somewhere in there.

So add #1022, then replace the legacy check for legacy combat check.

**Comment by Timer** [comment]
Fixed.
