### ISSUE TITLE
Support for levels > 99

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1025]
Currently, `realLevel()` returns 99 if the user is >= 99.
Since all skills support level 120, `realLevel()` should return appropriately.

**Comment by Timer** [comment]
RT6?

**Comment by Strikegently** [comment]
Yes.

**Comment by Timer** [comment]
That's weird because the level is retrieved from the game engine itself. See if doing `levelAt(experience(skill))` works.

**Comment by Strikegently** [comment]
I don't have any skills over 99, so I can't test anything, but I'm pretty sure that would work. 
It's your call if you want to just return what the game says or what their XP is based on.

**Comment by Timer** [comment]
@Strikegently where did you get the information "Currently, realLevel() returns 99 if the user is >= 99" from?

**Comment by Strikegently** [comment]
http://i.imgur.com/EeqHtdT.png

User posted a screenshot. He has 105 magic.

**Comment by Timer** [comment]
Patched.
