### ISSUE TITLE
CombatBar 6 does not work.

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1027]
The pattern (#924) works for CombatBar 1-5, but it does not work on 6.

When `getBarIndex()` is 6:
5265 + slot = abilities
5335 + slot = items

**Comment by rs-sliske** [comment]
how about 7 - 10?

**Comment by Strikegently** [comment]
I don't know, I don't have 7-10 unlocked.

**Comment by Timer** [comment]
What is the varp for items?
And what is the value of `getBarIndex()` when the new varps need to be used?

**Comment by Strikegently** [comment]
When `getBarIndex()` is 6:
5265 + slot = abilities
5335 + slot = items

**Comment by Timer** [comment]
Done.
