### ISSUE TITLE
Fix menu consistency

### ISSUE THREAD

**Issue by Timer** [powerbot/powerbot#1032]

**Comment by ArtificialPB** [comment]
I think I've found what's causing this issue. Sometimes ```ctx.menu.indexOf(Filter)``` will return ```1``` even though the desired action is the first one (and should return ``` 0```  instead). This only changes if you restart the client.

 This only applies to rt6 as I haven't tested in rt4. I'll create a pull request with an additional method to check the index of the menu tomorrow.

**Comment by Timer** [comment]
@ArtificialPB this isn't an API bug, and only I can fix it. If you want more details I can explain why.

**Comment by ArtificialPB** [comment]
I'm not saying it's an issue with the API, although it may seem like that from my post. 

It's okay, I don't need an explanation since I can't fix it.
