### ISSUE TITLE
Hud.Window.OPTIONS

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1034]
The Options menu is surprisingly missing from Hud.Window.
Definitely needed.

**Comment by Strikegently** [comment]
Thinking about it, it may not fit in well with the hud API, since it's not really the same as the other windows.
Either way, just a method to check if the Options menu is open and a method to open it is what I need.

**Comment by Strikegently** [comment]
You open the Options window for game.logout(), so just put that code in a separate method and make it public.

**Comment by Timer** [comment]
```java
ctx.hud.open(Hud.Menu.OPTIONS)
```

```java
ctx.input.send("{ESCAPE}")
```
