### ISSUE TITLE
Speed up bank items loading

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1035]
Currently it takes up to 10 seconds to load items in bank if you have around 500-600 items in it. This is really problematic with skilling scripts because it spends a lot of time banking. Could you make it run item loading on several different threads so that each thread loads 100 items or something like that?

**Comment by IITC** [comment]
What. It takes you 10 seconds to load 500-600 items in your bank?? Could you post your code? I don't understand what powerbot would be running that would cause it to take 20ms to initialize every item? Unless it's loading item definitions on creation of each item and the cache reader is really slow.

**Comment by ArtificialPB** [comment]
The part of code that takes a lot of time is ctx.bank.select(). It usually takes around 5-6 seconds but sometimes it takes 10.

**Comment by Timer** [comment]
I honestly don't see how this can take 10 seconds to load ... nothing is done but wrapper creation.

**Comment by ArtificialPB** [comment]
This is due to grabbing info from components (item id, stack size) while loading. It takes a couple times longer to get any info from them than in v6, so multiply that by 500 items and it adds up fast.

**Comment by Timer** [comment]
@ArtificialPB I've reduced its running time by 33%. Please reopen this issue if it's still of consequence.
