### ISSUE TITLE
Request - Make the Actionable interface extend Interactive

### ISSUE THREAD

**Issue by ac1d8lank** [powerbot/powerbot#1038]
It seems all Actionable classes (GameObject, GroundItem, Item, Npc) are Interactive, and it would be nice to be able to treat them generically.

I.e. `someActionable.interact(someActionable.actions()[3])`

**Comment by Timer** [comment]
wat?

**Comment by Strikegently** [comment]
I think he means have Interactive extend Actionable, so can have an Interactive instance and be able to call `Interactive.actions()`

**Comment by ac1d8lank** [comment]
Right, except Actionable would have to extend Interactive, e.g. `Actionable extends Interactive`. That means all Actionable items are implicitly Interactive.

The other way around is incorrect because there are some Interactive elements that don't extend Actionable currently (Actor, Component, TileMatrix)

**Comment by IITC** [comment]
Why do you necessarily need a dynamic array reference? Where aren't you going to know the interact string beforehand? I'd recommend using a Filter for menu commands.

**Comment by IITC** [comment]
Some entities don't have unique actions. The game generates them and they're not always constant.

**Comment by Strikegently** [comment]
Can you post some code about what you're trying to achieve?

**Comment by Timer** [comment]
Not all interactives implement actionable iirc.

**Comment by ac1d8lank** [comment]
Will write up an example when I'm back on a computer.

Joe: The other way around :) All Actionables implement Interactive.
If you make Actionables extend Interactive, nothing changes except for the
new ability to use interact() on an instance of Actionable.

**Comment by IITC** [comment]
```
import org.powerbot.script.Actionable;
import org.powerbot.script.Interactive;

/**
 * ActionInteractTest
 *
 * @author Ian
 * @version 1.0
 */
public class ActionInteractTest {
    public <T extends Interactive & Actionable> boolean interact(T interactive) {
        return interactive.interact(interactive.actions()[2]);
    }
}
```

**Comment by Paris** [comment]
Done for the next version.
