### ISSUE TITLE
Modelling bounds interface does not work (Bounds issue?)

### ISSUE THREAD

**Issue by Monkey103** [powerbot/powerbot#1039]
The modeling bounds interface will not pick up the bounds of objects or draw the bounds.

Also the draw(graphic) method on objects and such does not draw anything.

**Comment by Strikegently** [comment]
I tested Npcs, Players, and GroundItems and they all work fine.
Objects do not.

**Comment by Timer** [comment]
Objects work, they're just *very* **extremely** slow.

**Comment by Monkey103** [comment]
I don't believe they do. It sits there long enough for me to idle logout with no drawing.

Have had a couple people on the powerbot dev skype chat test this out and can confirm no draw of objects what so ever.

IE: Open the model bounds interface, select object from menu, select an object. You can see that the object has been selected in the window id=theid name=thename and no drawing for the entire time until logout.

using object.draw(graphic) is the same and will never draw the object. Tiles, Players and GroundItems do indeed work as intended.

**Comment by Strikegently** [comment]
How slow are we talking? I've left it for several minutes and nothing's happened.

**Comment by NexPB** [comment]
Any ideas when this will be fixed?

**Comment by Timer** [comment]
It's in the 7017 milestone which is targeted for the 21st.

**Comment by Timer** [comment]
Fixed speed in rt6.
