### ISSUE TITLE
ImageIO.write() throwing exception from checkPermission()

### ISSUE THREAD

**Issue by sippylabs** [powerbot/powerbot#1043]
```
[SEVERE] java.lang.SecurityException: setContextClassLoader 
 org.powerbot.CoN.checkPermission(wf:270)
 com.sun.imageio.stream.StreamCloser$2.run(StreamCloser.java:100)
 com.sun.imageio.stream.StreamCloser.addToQueue(StreamCloser.java:84)
 com.sun.imageio.spi.OutputStreamImageOutputStreamSpi.createOutputStreamInstance(OutputStreamImageOutputStreamSpi.java:68)
```

Any clues? Not a Java guy but looks like a worker thread with not enough permissions (from rapid Googling). Issue is intermittent, doesn't present every time, can't figure out how to do it consistently.

**Comment by Strikegently** [comment]
[downloadImage(String url)](http://www.powerbot.org/rsbot/docs/org/powerbot/script/AbstractScript.html#downloadImage%28java.lang.String%29)

**Comment by sippylabs** [comment]
It's not for downloading.

**Comment by Strikegently** [comment]
Post source.

**Comment by Paris** [comment]
Looks like a script specific issue.
