### ISSUE TITLE
Allow mouse algorithm overrides

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1044]
Allow us to override the default mouse algorithm with our own custom ones.

**Comment by IITC** [comment]
You can use `hop(x,y)` and `hop(Point)` to add in any custom mouse algorithms.

**Comment by AnthonyOSX** [comment]
@IITC Then we would have to write a custom API for everything. Override the default implementation and a simple API call to say, withdraw an item from the bank, will utilize the new algorithm. Obviously not a necessity but would be quite the feature to market.

**Comment by Timer** [comment]
then overwrite the ctx's mouse instance

**Comment by IITC** [comment]
@Timer, that doesn't work how you think it does. `((CustomContext)ctx).mouse` and `((ClientContext)ctx).mouse` would return different things, the original and the custom mouse class.

**Comment by AnthonyOSX** [comment]
Exactly what I was trying to avoid. Allowing direct setting of the context instance would be one possible solution.
