### ISSUE TITLE
combatBar.health() / maximumHealth() do not function correctly if combat bar is on side of screen.

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1045]
Numbers don't show when it's like this, so the methods don't work.

![](http://i.imgur.com/R1B8bBS.png)

**Comment by Timer** [comment]
How the hell do you turn it?

**Comment by Strikegently** [comment]
Drag it to the side.

**Comment by Timer** [comment]
@Strikegently tried that multiple times it wont work

**Comment by Strikegently** [comment]
Drag it to the side, then grab the corner and drag it towards the edge; it should resize and snap to the window.
It took me a few tries to get it.

**Comment by Timer** [comment]
This is not a varpbit or in widgets, you must be hovering it to get the health. This is just going to have to be a hard limitation. Tell users not to do this.
