### ISSUE TITLE
Development Warnings

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#1046]
There should be some warnings printed out to the console while in dev mode.

Calling filter functions on a query that has never been populated.
Calling `Tile#matrix(ClientContext)` on a NIL Tile.
etc..

**Comment by Timer** [comment]
I really like this idea.

**Comment by Paris** [comment]
While this sounds nice in theory it shouldn't happen if the script was written properly to begin with. In Java there are many places for redundancy which doesn't result in compiler warnings so we won't implement them either.

**Comment by IITC** [comment]
Then I would ask for improved documentation. I only asked for this due to clear ambiguity in the client.
