### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by iitc** [powerbot/powerbot#1055]
Support for logging in using powerbot credentials in a secured fashion.

**Comment by Strikegently** [comment]
For what purpose?

**Comment by IITC** [comment]
Allowing scripters to have their own websites to offer various utilities to each user for their scripts. Issue trackers, dynamic signatures, etc.

**Comment by Strikegently** [comment]
You can do that without our involvement.

**Comment by IITC** [comment]
Not without having them enter their credentials.

**Comment by Strikegently** [comment]
Why do they need credentials at all for displaying dynamic signatures?

**Comment by IITC** [comment]
Not necessarily for individual signature but for viewing botting statistics and all of the signatures. Also for the issue tracker. My website will be interactive. Also dynamic signatures will not be linked directly to their powerbot id and the script. It'll be hashed/masked in a way and they need some way to get the URL. Logging in would allow them to see all their signatures and retrieve the URLs.

**Comment by Paris** [comment]
OpenID is a deprecated technology, OAuth superseded it.

**Comment by IITC** [comment]
Woops. I was thinking OAuth and said OpenID. lol

**Comment by IITC** [comment]
Can you also return the data from http://www.powerbot.org/api/user/ upon redirecting?

**Comment by Strikegently** [comment]
Everything you need is in properties.
user.name
user.id
user.vip

**Comment by IITC** [comment]
I need it for my website. Upon signing in, I need to cache their avatar url, display name, and other stuff.

**Comment by rs-sliske** [comment]
"http://powerbot-dequeue.netdna-ssl.com/community/uploads/profile/photo-" + userid + ".gif" 
seems to be avatar url

**Comment by IITC** [comment]
@rs-sliske, true. There seems to be a weird parameter passed after the url but it doesn't change the image. Regardless, it'll be just as easy including the actual path to the avatar than not.

**Comment by Paris** [comment]
The parameter is just a cache buster and serves no purpose, as others have mentioned you can get all the details already so implementing OAuth provides no useful benefit.

**Comment by IITC** [comment]
I clearly stated I needed this outside of the client. @Strikegently mentioned a client-side solution. @rs-sliske listed a solution to 1/4 of my request.

**Comment by Paris** [comment]
There needs to be a valid commercial reason for us to invest development time into this.

**Comment by IITC** [comment]
It encourages script writers to develop additional offerings to go alongside their scripts to enhance their products.

**Comment by Paris** [comment]
We'll look into implementing [JWT](https://jwt.io/introduction/) as an alternative if developer demand arises.
