### ISSUE TITLE
Implement a output logging window

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1061]
Please add an optional window users can toggle which receives the default output/error streams. It's very hard to debug user issues caused by exceptions when they don't know how to run the bot from the command line.

**Comment by Strikegently** [comment]
Help > View Log

**Comment by AnthonyOSX** [comment]
@Strikegently The error stream doesn't seem to be outputting.

**Comment by Paris** [comment]
Use the provided logger instead of the system output streams, which is better to avoid detection also.
