### ISSUE TITLE
Tile.distanceTo()

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1063]
Currently, Tile.distanceTo() uses Euclidean distance which makes 1 diagonal step a distance of ~1.4 (sqrt(2)). So moving from 0,0 to 1,1 is calculated as 1.4 steps.

If you changed it to Chebyshev distance, diagonal steps have the same weight as orthogonal steps; i.e. 0,0 to 1,1 would be calculated as 1 step, which is correct.

**Comment by Strikegently** [comment]
Unless the purpose is to discourage diagonal steps in the pathfinding, then it's fine the way it is now.

**Comment by Timer** [comment]
It takes longer for your character to move diagonally.
