### ISSUE TITLE
Resource file compressions

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1064]
A lot of bandwidth could be saved if the resource server would automatically compress the text files we upload.
A `downloadResource()` method could be added that would download and unzip the specified file.

For security purposes, it should only accept a valid SDN resource URL.

**Comment by Paris** [comment]
The server and CDN both support [HTTP compression](https://en.wikipedia.org/wiki/HTTP_compression) which is utilised in the `downloadResource()` method with the appropriate [`Accept-Encoding`](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3) headers. This is all done transparently, with uncompressed requests also supported.
