### ISSUE TITLE
Don't try to open the backpack when this window is active

### ISSUE THREAD

**Issue by NexPB** [powerbot/powerbot#1069]
Would it be possible to not try and open the backpack when this window is visible?

![img](https://i.gyazo.com/56b5b0aa1a7313df0cda47b5211cf89c.png)

**Comment by Timer** [comment]
@NexPB is there not a secondary backpack available at this point?

**Comment by NexPB** [comment]
No it's when you open a deposit box.

**Comment by Timer** [comment]
@NexPB would you expect it to return true or false?

**Comment by NexPB** [comment]
True since the backpack is there but you just can't interact with it.

**Comment by Timer** [comment]
I cannot find this widget, do you have any insight on this?

**Comment by NexPB** [comment]
@Timer I'll see if I can get them tomorrow.

**Comment by Timer** [comment]
Please reopen this if you can find the widget or a way to detect this, I was not able to.
