### ISSUE TITLE
ctx.magic.spell()

### ISSUE THREAD

**Issue by MookyMan** [powerbot/powerbot#1070]
Rt4 this returns and array out of bounds if used after world hopping.

Like if you open the client, world hop to an empty world then start the script it returns out of bounds but if you reopen the client and start it on the first world you log in to then it works fine.

```
[SEVERE] java.lang.ArrayIndexOutOfBoundsException: -1 
	org.powerbot.script.rt4.Widget.component(hb:345)
	org.powerbot.script.rt4.Widgets.component(kb:264)
	org.powerbot.script.rt4.Magic.spell(ld:71)
```

Edit: Okay manually switching to magic tab fixes it.

**Comment by Strikegently** [comment]
So open the magic tab before calling it?

**Comment by MookyMan** [comment]
It works perfectly when not on the magic tab normally.

But after a world hop you have to flick to the magic tab.

**Comment by Timer** [comment]
```
[SEVERE] java.lang.ArrayIndexOutOfBoundsException: -1 
    org.powerbot.script.rt4.Widget.component(Widget.java:28)
    org.powerbot.script.rt4.Widgets.component(Widgets.java:47)
    org.powerbot.script.rt4.Magic.spell(Magic.java:138)
```

**Comment by Timer** [comment]
Fixed
