### ISSUE TITLE
Mouse speed

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1071]
Allow us to set the time between mouse hops.

**Comment by Paris** [comment]
Reasons?

**Comment by AnthonyOSX** [comment]
@Paris My current use case would be for interactions with moving entities. Other cases could include efficient skilling (very prominent in Old School with rapid clicks between the game viewport and inventory), built in "fatigue" antipattern, etc.

**Comment by Paris** [comment]
The next version will have a new method for controlling this: [`Input.speed(int)`](http://www.powerbot.org/rsbot/docs/org/powerbot/script/Input.html#speed(int))
