### ISSUE TITLE
Bank.withdraw taking awhile to return

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1072]
Doesn't happen all the time but when tested with Bank#withdraw(int, int) it takes up to 6 seconds for the method to return. Haven't done any testing with Bank#withdraw(int, Amount).

It withdraws the items fine but then idles after selecting the proper menu option.

**Comment by Strikegently** [comment]
withdraw(int, int) and withdraw(int, Amount) are literally the same thing.

**Comment by AnthonyOSX** [comment]
@Strikegently I'm not developing the API, how am I supposed to know one or care about how one just references the other?

**Comment by ArtificialPB** [comment]
@AnthonyOSX Take a look at the old rsbot sources. A lot of methods are basically the same.

**Comment by AnthonyOSX** [comment]
@ArtificialPB Only thing I could see taking awhile would be a getCount or equivalent call.

**Comment by ArtificialPB** [comment]
Do you have a lot of items in bank? @AnthonyOSX

**Comment by AnthonyOSX** [comment]
@ArtificialPB Only about 5 rows so barely anything.

@Timer why was the request label added if it's a bug?

**Comment by ArtificialPB** [comment]
Could be related to https://github.com/powerbot/powerbot/issues/1035 since it's refreshing the query couple of times when withdrawing.

**Comment by Timer** [comment]
@AnthonyOSX this means your inventory count is not seeing a discrepancy when moving items [as it expects], are you doing other things like depositing before this?

**Comment by AnthonyOSX** [comment]
@Timer yeah, I notice it happens while cooking (deposit all -> withdraw all) and in the middle of withdrawing fletching materials (deposit all -> withdraw 14 bow strings and unstrung bows).

**Comment by Timer** [comment]
Yeah, the only way for you to really mitigate this @AnthonyOSX is to wait for your inventory count to change yourself after deposit all. The bank class isn't smart enough to check for ids.
