### ISSUE TITLE
CombatBar.maximumHealth() reports wrong number in Legacy combat

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1073]
health() returns correctly, but maximumHealth() is returning 10 times what it should, so at full health, your health is reported as 10%.

**Comment by ArtificialPB** [comment]
@Timer I assume you changed this for when in legacy interface AND legacy combat. https://github.com/powerbot/powerbot/issues/1067

**Comment by Timer** [comment]
fml

**Comment by Timer** [comment]
Let me get this right..
EOC + RS3 Interface = read from combat bar
EOC + LEG-HUD = ctx.skills.realLevel(Constants.SKILLS_CONSTITUTION) * 10
RS2 + LEG-HUD = ctx.skills.realLevel(Constants.SKILLS_CONSTITUTION) * 100

**Comment by ArtificialPB** [comment]
EOC + LEG-HUD = ctx.skills.realLevel(Constants.SKILLS_CONSTITUTION) * 100
RS2 + LEG-HUD = ctx.skills.realLevel(Constants.SKILLS_CONSTITUTION) * 10

**Comment by rs-sliske** [comment]
cant the values be read from the minimap orbs if running in legacy combat mode?
basing on constitution level only works if the user is wearing low level armour or no armour

**Comment by Timer** [comment]
Fixed

**Comment by Strikegently** [comment]
@rs-sliske 
The orb on the minimap only shows your current health, not your maximum health.

**Comment by rs-sliske** [comment]
@Strikegently doesnt it store the max health somewhere to work out what % your hp is at?
how does it know what color/how much of the orb to fill?
