### ISSUE TITLE
Scripts randomly freezing

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1075]
Scripts sometimes randomly freeze for random amount of time, often for a couple of minutes or more causing the user to get logged out. I've also seen cases where it was not getting unfrozen even after a longer period. Is anyone else experiencing this?

**Comment by Timer** [comment]
I believe this must be related to #953.

**Comment by Strikegently** [comment]
@Timer 
It is. It happened last time while I was trying to find #953. There wasn't anything in the debugging you put, though.

**Comment by Strikegently** [comment]
@Timer 
Every time it gets stuck, it's using item queries in either the bank or the inventory. 
This needs to be fixed ASAP.

**Comment by Timer** [comment]
should be fixed in 6a2c053
Thanks to @Strikegently for pinpointing
