### ISSUE TITLE
Menu not appearing on OSX 10.10.5

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1076]
![](http://i.imgur.com/bZj3o1Z.png)
http://www.powerbot.org/community/topic/1290213-how-do-i-run-osrs-on-powerbot-macosx/

**Comment by ChrisBPB** [comment]
it works with yosemite and el capitan, I tested on both

the guy was running java 6 though I am guessing it was that

**Comment by Strikegently** [comment]
@ChrisBPB 
Ask him to update Java and see if that works.

**Comment by Paris** [comment]
@Strikegently he should just update his OS X instead (which is free), since it's virtually impossible for me to downgrade and test this bug won't be fixed.
