### ISSUE TITLE
GroundItems with incorrect name.

### ISSUE THREAD

**Issue by Robert-G** [powerbot/powerbot#1078]
The names of some GroundItems are incorrect, not sure about other values as I haven't checked into it.
I first noticed it when my script was hovering the mouse over an item. A quick look at my debug log showed this:

Checking: Clue scroll (hard), ID: 13000
added Clue scroll (hard), value: 2178 to the loot list.

The actual item was a pair of Adamant gauntlets. The id is fine, as when I print the associated GEItem, it returns the proper name.

**Comment by Timer** [comment]
This means the cache block it has cached is invalid. This is a tricky situation to handle... let me see what I can do.

**Comment by Strikegently** [comment]
It's also an issue with Ghostly Essence (32341).

**Comment by Timer** [comment]
Is this primarily related to rt4 or rt6?

**Comment by Timer** [comment]
Closing this until more information is provided.
