### ISSUE TITLE
API Development Team

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1080]
Just a suggestion, but awhile back when I worked for another botting company we had a few script developers with API access so they could easily fix bugs + implement new features without bothering the actual developers. I think implementing such a team would be extremely beneficial here.

**Comment by NexPB** [comment]
Won't happen. I don't know the exact reasons but I'm sure it has to do with contracts and stuff.

**Comment by AnthonyOSX** [comment]
@NexPB All this would require is a basic NDA.
