### ISSUE TITLE
MessageListener seems to be broken

### ISSUE THREAD

**Issue by rs-sliske** [powerbot/powerbot#1081]
![](http://sliske.uk/img/captures/b8e46e.png)
![](http://sliske.uk/img/captures/8c17d2.png)

https://github.com/rs-sliske/rsbot/blob/master/src/uk/sliske/rsbot/rs3/scripts/winedrinker/WineDrinkerRS3.java
tested in other scripts, and with all my web tracker stuff commented out. no change

**Comment by Strikegently** [comment]
![](http://i.imgur.com/uDvQly2.png)

**Comment by Timer** [comment]
What is your client hash?

**Comment by rs-sliske** [comment]
[INFO] Bot: Hash: df4bc90bf8d22ff4f44810130babfbe92de6380c size: 1241

not sure if this is what you mean but this is the hash i get when i start the client

**Comment by Timer** [comment]
yes ty

**Comment by rs-sliske** [comment]
ive done quite a few tests today and found the problem happens on os aswell, if you think they could be useful ill link screenshots / gists of all the tests i did in the morning (would do now but its 4 am and im tired :( )

**Comment by Strikegently** [comment]
Is this fixed when using Java 8?
#1084

**Comment by rs-sliske** [comment]
Haven't tested os but it's working with rs3

**Comment by Timer** [comment]
Please re-open if this hook becomes problematic again.
