### ISSUE TITLE
Problems with Npc#inCombat() and Npc#healthPercent()

### ISSUE THREAD

**Issue by Robert-G** [powerbot/powerbot#1082]
There seems to be a couple of problems with the Npc class, inCombat is returning false and health is returning 100%.

![npc health](https://cloud.githubusercontent.com/assets/766242/11326011/13e0afac-9155-11e5-9988-b1c9b1b70c2c.png)

**Comment by Timer** [comment]
When not using legacy combat you must use the combatBar methods for targets.

**Comment by Robert-G** [comment]
That doesn't really help when your trying to filter out dead npcs so you don't attack them though?
Unless I'm missing something?
I didn't see any method in the combat bar to return an npc object to compare to in my filter or anything.

**Comment by Timer** [comment]
Those methods should work if you're not fighting the Npc you're inspecting. Otherwise use ctx.combatBar.target**().

**Comment by Robert-G** [comment]
Well the don't, that was the whole point of this post :p.

**Comment by Robert-G** [comment]
This is the problem:

![unrendered](https://cloud.githubusercontent.com/assets/766242/11344443/3feab1e2-9209-11e5-8c7b-ff56e3f5915e.png)

At that point the client still returns the npc as having 100% health and being valid, so instead of attacking a new target, you keep attacking the spot where the previous one died.

**Comment by Timer** [comment]
fixed.
