### ISSUE TITLE
Debug overlays broken (Java 6 Windows)

### ISSUE THREAD

**Issue by rs-sliske** [powerbot/powerbot#1084]
![](http://sliske.uk/img/captures/bbb2c3.png)

not sure if it is related to the problems im having with message listener #1081

**Comment by Strikegently** [comment]
What Java version are you using?

**Comment by rs-sliske** [comment]
http://sliske.uk/img/captures/ac07b2.png

**Comment by Strikegently** [comment]
Try using Java 7 or 8.

**Comment by rs-sliske** [comment]
works fine with java 8

**Comment by Strikegently** [comment]
Okay, then use Java 8.

**Comment by Paris** [comment]
For the next version the bot will prompt the user to upgrade their Java if they're running JRE 6 or older on Windows.
