### ISSUE TITLE
Input (mouse)  #moving() method request

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1088]
I'd like to request a method to return if the mouse is already being used. This would allow script writers to write more human-like antipatterns and doing multiple tasks at once on different threads without interfering with main scripts execution.

**Comment by Strikegently** [comment]
Extend Camera. Have a `boolean moving` field. Override `turnTo()` and whatever else to basically be:

```
turnTo(...) {
moving = true;
super.turnTo(...);
moving = false;
}
```

**Comment by ArtificialPB** [comment]
@Strikegently I guess you're right about the camera since it's not used in any client methods.

**Comment by Timer** [comment]
This cannot reliably be added because of methods like hop, etc.
Please just don't try using the mouse from multiple threads.
