### ISSUE TITLE
CombatBar#expand(boolean) broken

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1092]
Does not expand combat bar and returns false even if the combat bar is already opened.

**Comment by Strikegently** [comment]
Very possibly related to #1090. It may preemptively call `hud.legacy()` (since it was written prior to `combatBar.legacy()`.

**Comment by Timer** [comment]
Fixed for legacy ui

**Comment by Strikegently** [comment]
@Timer 
expanded() worked correctly, but expanded(boolean) did not when I tested in RS3 layout.
