### ISSUE TITLE
Stack trace decoder

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1095]
Would be useful to have one so we can quickly resolve exceptions being thrown in our scripts.

**Comment by Paris** [comment]
Does the stack trace logs not already output the source script and line number?

**Comment by AnthonyOSX** [comment]
Nope. Here's an example output:

java.lang.NullPointerException 
org.powerbot.bot.rt4.cOn.poll(sg:96)
org.powerbot.script.PollingScript$6.run(me:181)

**Comment by Paris** [comment]
Those two lines are internal RSBot API which you do not need to deobfuscate. We have the facility to deobfuscate them in order to identify bugs.
