### ISSUE TITLE
Issue with ctx.hud.open

### ISSUE THREAD

**Issue by Robert-G** [powerbot/powerbot#1096]
For some reason ctx.hud.open(Window.BACKPACK) has started to return false even when the window is open and visible. I'm not sure if any other windows are affected.

**Comment by Timer** [comment]
No code has changed, does this happen in *all* game versions?

**Comment by Robert-G** [comment]
I have only tried with EoC. I think this bug might only affect certain game packs too, as when one of my users reported the problem I couldn't replicate it, then this morning it happened to me.

As of now, it is working again, as I'm on a different game pack. Next time the issue appears I will post back with more info, including bot hash.

**Comment by Timer** [comment]
ok thanks

**Comment by Timer** [comment]
Cannot replicate. I believe the issue is that we do not support a customized ribbon bar, it *must* be the default given by RuneScape.
