### ISSUE TITLE
Sales report broken

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1098]
When you try to check sales report on the SDN it shows: "The page you are trying to view is currently unavailable. This is may be a temporary problem so please try again later."

**Comment by NexPB** [comment]
It only works sometomes for me and when it does it doesn't even show what we made this month but all time.

**Comment by Strikegently** [comment]
@Paris removed the payments panel citing incorrect calculations for non-USD developers.

**Comment by Paris** [comment]
Ensure you have the correct login session cookies by refreshing at least once on the [forum page](http://www.powerbot.org/community/) then visit the staff panel again and it should work.

**Comment by ArtificialPB** [comment]
Refreshed the page and logged out and back in but it still shows that error when trying to download.cvs report file.
