### ISSUE TITLE
Withdraw-X optimisation

### ISSUE THREAD

**Issue by k0na** [powerbot/powerbot#1100]
This method - in rt6 (possibly also rt4) - currently ALWAYS does the following:

- Finds item with id and right clicks it
- Chooses "Withdraw-X", types in amount and hits enter

It'd be nice if it only selected "Withdraw-X" the first time and afterwards selected whatever amount was inputted first, i.e. "Withdraw-28" or "Withdraw-14". This would both save time and be more like a human player.

Might be related to #1032 but since it has no description I'm not sure

**Comment by Paris** [comment]
Consolidating into #1032
