### ISSUE TITLE
NullPointerException thrown while exiting

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1101]
A NullPointerException is thrown while trying to exit RSBot via the menu bar. It doesn't exit, and has to be terminated.

> [SEVERE] java.lang.NullPointerException 
>	z.NA.windowClosing(mn:156)
>	z.LpT6.close(mn:286)
>	z.G.actionPerformed(og:186)

**Comment by Paris** [comment]
Fixed for next version thanks.
