### ISSUE TITLE
SDN Not updating

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1102]
It updated yesterday for the first time in a couple of days, but again stopped working after that. Got some updates that need to get through, including for a premium script. @Paris

**Comment by Monkey103** [comment]
Yeah same been a couple of days since rebuild and I have pushed a couple of changes to fix my script.
Not happening, pushing alright to SDN or so git says but is never rebuilt

**Comment by ArtificialPB** [comment]
Seems to be working now.
