### ISSUE TITLE
Powers#prayerActive(Effect) wrong for some prayers

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1103]
- If you turn on Piety (Normal prayer) it shows that Rapid Renewal is active.
- If you turn on Chivalry (Normal prayer) it does not show any active prayers.

**Comment by Timer** [comment]
I need an account for this, please contact me in the dev chat.

**Comment by Timer** [comment]
Fixed, thanks. I suspect Rapid Renewal will not work but I guessed the index.
