### ISSUE TITLE
Set System.out/err streams to the log

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1105]
I find myself calling System.out.println just out of habit (plus ctx.controller.script().log is very verbose). Would be nice if by default this write to the log.

**Comment by Timer** [comment]
why not set a variable in the class and shorten that to just `log.info("")`?

**Comment by Strikegently** [comment]
If this is done, just make sure to.
1. change it back to default when closing the client
2. direct the output to the log AND the default, so script writers can still see output

Or @AnthonyOSX could just set a live-template in IntelliJ to autocomplete this for him.

**Comment by AnthonyOSX** [comment]
@Timer Obviously that's just a ramble, System.out.println is just as cumbersome.

@Strikegently A concern was brought up by @Paris in #1061 regarding bot detection when scripts output to the default stream.

**Comment by Paris** [comment]
We won't modify the system output for detection reasons and really it's not a genuine inconvenience to use the logger.
