### ISSUE TITLE
[Severe] Script: Could not download script

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1107]
I'm constantly getting this error when trying to run SDN versions of my ACrafter and ASlayer. My other two scripts, AMiner and ASmither, work fine. I've tried pushing to the SDN to force it to rebuild, but I still get the same issue every time. SDN compile log does not show any errors. Here's the stack trace of the issue:
```
[SEVERE] Script: Could not download script
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at z.con.break(bf:151)
	at z.cOm8.run(cg:358)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ArtificialPB** [comment]
ASmither also stopped working now.

**Comment by ArtificialPB** [comment]
Any news on this? Majority of my scripts are nonfunctional, including both premium scripts.

**Comment by Paris** [comment]
Your code fails to compile on the SDN and more details are in your build log.

**Comment by ArtificialPB** [comment]
Build log error:
```
ZKM error:	Attempt to use "obfuscate" statement at line 10 with unusable classes : Class 'com.artificial.framework.script.ScriptInfo' not found while looking for method 'version()' in class 'com.artificial.framework.script.ScriptInfo' which is referenced in class 'ACrafting-388775.jar!com/artificial/framework/awt/paint/APaintBox.class'. Check the classpath option and reopen classes. (1a)
```
Any idea how to fix this without removing ScriptInfo annotation?

**Comment by Paris** [comment]
Just reference it statically in your code somewhere.

**Comment by ArtificialPB** [comment]
I still get the same issue with the annotations. I've modified my scripts to provide this info in other way, without annotations, but it would be great if this would work.

**Comment by Strikegently** [comment]
You can store any information you'd like in the Properties field until a solution is crafted (though, be aware, this would be low-priority).

**Comment by ArtificialPB** [comment]
I'm aware this is a low priority fix. Like I said, it would be great if it worked, but there are other ways to get what I need, it would just be simpler with annotations.
