### ISSUE TITLE
Change script directory

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1108]
Not sure why temp is being used as a persistent data store location....

`System.getProperty("user.home") + File.separator + "RSBot"`

**Comment by Moosheplusplus** [comment]
I'm pretty sure that's a feature, because it doesn't need to leave a cache of the downloaded scripts.

**Comment by Moosheplusplus** [comment]
it already creates ~/.rsbot/

**Comment by AnthonyOSX** [comment]
@Moosheplusplus Should have clarified, scripts can only use IO operations on the file system in the designated storage directory or else it gets blocked by the security manager. This directory defaults to temp.

**Comment by Paris** [comment]
This is because the design is to let scripts have access to a local cache, not as permanent file storage. If you want to have permanent settings then it should be linked server side with the users' ID.
