### ISSUE TITLE
Game objects have no name

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1109]
Been getting a lot of bug reports on my woodcutter stating it won't chop Yew trees in specific locations (behind Varrock Castle, Gnome Stronghold, etc.) while other spots work (behind Lumbridge Castle, etc.). After a little debugging I noticed the spots that weren't working had no name associated with the object:

![image](https://cloud.githubusercontent.com/assets/6828951/11855072/ff66761e-a415-11e5-8f8c-31c584ff2cf8.png)

As you can see both the plant and normal tree work fine. The Yew trees however (ID 27255) do not have a name. This happens with a few other objects in the Stronghold (but not limited to) as well including flax.

![image](https://cloud.githubusercontent.com/assets/6828951/11855142/74fedc2c-a416-11e5-90e5-df4c802430e4.png)

**Comment by AnthonyOSX** [comment]
@Timer this is rt4.

**Comment by Timer** [comment]
It seems the cache only contains ids up to 27151 ... @iitc any ideas why that is?

**Comment by iitc** [comment]
@Timer, I've got up to 27292 object configs. Some are missing though in the range you're missing though, specifically the two listed in the screenshot. lol

**Comment by iitc** [comment]
Sounds like your cache is outdated. The latest ids were from the deadman and christmas updates.

**Comment by Timer** [comment]
@iitc maybe we need to implement a cache downloader in the bot that builds entire thing ...

**Comment by iitc** [comment]
@Timer, that'd be really beneficial. You would then have all the map data loaded as well and could create a decently sized web off of it. There's an open source downloader on rune-server if you're feeling lazy. :P

**Comment by Timer** [comment]
@iitc Method's code is excellent it'd be a crime if I didn't use it.

**Comment by Logicail** [comment]
ObjectDefinition 27255 {name: "null", type: 1, width: 3, height: 3, actions: ["Chop down", null, "hidden", null, null], animationId: -1, scriptId: 4153, configId: -1, childrenIds: [11758, 9714], unwalkable: T, blockType: 0, solid: F}

11758 is Yew Tree
9714 is Tree Stump

Need to add script/config loading to fix this like NPCs

**Comment by Timer** [comment]
@Logicail it is there

**Comment by Logicail** [comment]
`CacheObjectConfig.load(Bot.CACHE_WORKER, 27255)` returns null

**Comment by Timer** [comment]
Yeah, we established that @Logicail. Don't know why it fails yet.

**Comment by Logicail** [comment]
Can you test with `for (int i = 0; i < len; i++) {` (removed the <=)
at https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/CacheObjectConfig.java#L201

**Comment by Logicail** [comment]
I believe `b.getSector(id)` returns null at https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/CacheObjectConfig.java#L50 might want to compare it to what https://github.com/Strikeskids/CacheReader/blob/master/src/com/sk/cache/fs/Archive.java#L47 does.

**Comment by Timer** [comment]
Fixed

**Comment by Logicail** [comment]
I get the correct names, something to do with outdated cache?
It could be useful for @ChrisBPB to upload there cache for testing?

**Comment by ChrisBPB** [comment]
Was fixed in 7020 @Logicail

**Comment by iitc** [comment]
@logicail, I only mentioned outdated cache because the wrong indexing lined up perfectly with game updates. I'm sure it's not related.
