### ISSUE TITLE
Item instance exists, but has no values

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1110]
Reporting on behalf of [Laputa's issue on powerbot] (http://www.powerbot.org/community/topic/1293771-client-booleans-not-working-properly/) - I was able to replicate the bug.

```java
ItemQuery<Item> c = ctx.inventory.select().action("Eat");
if(c.isEmpty())
	log.info("No food");
else
	for(Item i : c)
		log.info("Item found: "+i.name());
```

Trying to select all inventory items with the action "Eat" when there's only Monkfish will return an empty ItemQuery.

Output of above code with just Monkfish:
> [INFO] pw.mooshe.merch.MainScript: No food

Output of above code with both Monkfish and Shrimp:
> [INFO] pw.mooshe.merch.MainScript: Item found: Monkfish
> [INFO] pw.mooshe.merch.MainScript: Item found: Shrimps

Output of above code with just Shrimp:
> [INFO] pw.mooshe.merch.MainScript: Item found: Shrimps

This is only reproducible if there are no different types of items with the action "Eat". If there is another item with "Eat", it will return both normally.

```java
ItemQuery<Item> c = ctx.inventory.select();
for(Item i : c)
	log.info("Actions for "+i.getName()+": "+Arrays.asList(i.actions()));
```

When I try to output the actions of each item in the inventory with Shrimp and Monkfish in the inventory, it produces this result:
> [INFO] pw.mooshe.merch.MainScript: Actions for Monkfish: [Eat, null, null, null, Drop]
> [INFO] pw.mooshe.merch.MainScript: Actions for Shrimps: [Eat, null, null, null, Drop] 

If I have just Monkfish in the inventory, the ItemQuery has an item in it, but it has no values whatsoever (no name, no item ID, no actions, etc.)

It doesn't seem like Monkfish registers properly with RSBot if it's the only food item in the inventory.

**Comment by AnthonyOSX** [comment]
Possible duplicate and/or related to #1109

**Comment by Timer** [comment]
This is because we do not yet have cache definitions for rt4 items, perhaps @iitc can help with this.

**Comment by iitc** [comment]
@Timer, item definitions for OS are identical to RS3 but for opcodes
```
                case 1:
                case 23:
                case 24:
                case 25:
                case 26:
                case 78:
                case 79:
                case 90:
                case 91:
                case 92:
                case 93:
```
you read a unsigned short rather than the unsigned "packed int" that chooses between a short/int.

**Comment by iitc** [comment]
I don't have a client to open on this pc to get the upper bound on OS opcodes but regardless, those cases will never get hit so it's nothing to worry about. lol

**Comment by iitc** [comment]
The return for those opcodes are never used so you can just skip the values. I'll compare them later tonight but that's the only thing I remember being different.

**Comment by Timer** [comment]
@iitc do you know the file/id hashing off hand?

**Comment by Timer** [comment]
I'll postpone this another release to get it right.

**Comment by ArtificialPB** [comment]
It's cache type 2, archive 10, if that's what you mean @Timer

**Comment by Timer** [comment]
Yeah that's what I meant, @ArtificialPB.

**Comment by iitc** [comment]
@Timer, for further reference, http://rs-hacking.com/forum/index.php?/topic/1075-introduction-and-comprehensive-cache-format/?hl=cache.

**Comment by Timer** [comment]
Done thanks to @Logicail and @iitc.
