### ISSUE TITLE
Open source the API

### ISSUE THREAD

**Issue by Paris** [powerbot/powerbot#1112]
By popular demand.

**Comment by iitc** [comment]
This is a good old monkey wrench. Looking forward to seeing it. What's contribution going to look like? Is it going to be read-only or what?

**Comment by AnthonyOSX** [comment]
Would prefer to see this closed to SW+ or PSW+ only.

**Comment by Timer** [comment]
@iitc open to all parties to submit pull requests, all rights retained by us iirc.

**Comment by iitc** [comment]
Can we license out software for you to package into the client while retaining all rights according to said license? I don't have any examples of when I'd make use of such a clause but it never hurts to clarify.

**Comment by Timer** [comment]
@iitc no

**Comment by iitc** [comment]
Thanks for clarifying. Looking forward to contributing.

**Comment by Timer** [comment]
@iitc reason being is because once code is in the main branch it becomes an integral part of the bot, which means we need full rights to relicense it later on if need be and update it at will (and not be asked to remove it because scripts will come to depend on it). To keep things simple, we chose to acquire all rights to the code submitted. Sorry if this is an inconvenience.

**Comment by iitc** [comment]
@Timer, sounds completely appropriate. Only thing I can think of that I could contribute to would be cache reading and web walking. However, I don't know how keen ya'll would be to introducing a huge part of the api written by a third-party.

**Comment by Timer** [comment]
@iitc, the majority of cache reading is there already, however webwalking is not. And web walking is not something I believe we're going to willy nilly accept from a pull request -- it would be a separate project to create a uniform and agreed upon specification.

**Comment by iitc** [comment]
@Timer, exactly. Knowing how anal I am with design standards, I assume you and @Paris are just the same. How open are ya'll to collaborating with script writers on huge extensions to the API now that it will be exposed?

**Comment by Timer** [comment]
@iitc well that's exactly what I meant, we'll probably create other sub-projects dedicated to web walking, for example. We're totally open to entirely new sections of the api, but will probably run through it and rewrite it to conform to the API standard.

**Comment by iitc** [comment]
@Timer would you allow any developers other than yourself and @Paris to lead any new sub-projects?

**Comment by iitc** [comment]
Or are you just saying that anything can be requested(pre-written) and you'll just rewrite everything to your standards?

**Comment by Timer** [comment]
@iitc all sub-projects will most likely stay in house (in terms of pull request merge access) and be monitored by Coma and myself. Of course we will listen to our contributors for changes and how they wish the project matures etc. Reason being is that for licensing reasons the code needs to reside on our powerbot organization on github and have Aadil as the root commit specifying license terms.

**Comment by Timer** [comment]
@Paris don't forget to include .idea/codeStyleSettings.xml

**Comment by iitc** [comment]
@Timer @Paris why don't tall just have all contributors to the client signed CLAs? It's common practice for open-source software.

**Comment by Paris** [comment]
The code is [now available](https://github.com/powerbot/powerbot/tree/rsbot-api).
