### ISSUE TITLE
Script Select Window is freezing up

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1116]
Sometimes the Script Select Window/Login Window will freeze everything(the game, bot, etc) indefinitely. I believe this is due to an open stream on the AWT thread.

**Comment by Paris** [comment]
Does this still happen?

**Comment by Moosheplusplus** [comment]
@Paris it won't freeze up, but it stays blank (which may make people post on the forums asking for help). If it cannot connect, maybe pop up a message dialog saying powerbot could not be reached?

**Comment by Moosheplusplus** [comment]
This issue is occurring again.

**Comment by Moosheplusplus** [comment]
This issue is still occurring, and makes it very tedious to develop scripts for RSBot.

**Comment by Paris** [comment]
Do you think it's an internet connectivity issue because I can't seem to find anywhere in the code where it will hang?

**Comment by Moosheplusplus** [comment]
@Paris whatever it is, it's running on the AWT thread, and causes it to freeze. Even if it is a connection to the internet that's causing it, it shouldn't be running on the AWT thread.

If you could give me a copy of RSBot which is verbose, I'd be able to give you a detailed log, since I'm able to replicate this bug frequently.

**Comment by Moosheplusplus** [comment]
@Paris this is what it looks like:

![](https://i.imgur.com/vexjCEM.png)

**Comment by Moosheplusplus** [comment]
the issue seemed to be related to the IDE; switching IDEs seemed to have fixed this. Not entirely sure what the issue was to begin with, but it seemed not reproducible on other people's clients.
