### ISSUE TITLE
DarkScape walking is broken

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1118]
Possibly linked to
https://github.com/powerbot/powerbot/issues/1091

Can confirm RS3 walking still works though.

**Comment by Timer** [comment]
Really? It looks fine to me... 
![](http://puu.sh/mf8pa/86edeff981.png)

**Comment by ChrisBPB** [comment]
it makes no attempt to walk with .step or .traverse() for me and the other guy who reported it on the forums

**Comment by Timer** [comment]
@ChrisBPB is this is legacy ui or normal rs3 ui

**Comment by ChrisBPB** [comment]
both

**Comment by ChrisBPB** [comment]
Still broken
http://www.powerbot.org/community/topic/1298471-standing-there/

**Comment by Timer** [comment]
ok
