### ISSUE TITLE
When scripts fail to compile developers can't see why

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1119]
Compilation log only shows if you have a script on the SDN, so you get stuck in a loop if your script(s) don't compile.

**Comment by ChrisBPB** [comment]
Sadfiesch scripts failed to compile earlier but his log was visible so I guess it isn't caused solely by failing to compile

**Comment by Paris** [comment]
I reviewed the code and this shouldn't happen but if it does please re-open.
