### ISSUE TITLE
Some users scripts aren't compiling

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1120]
Cody, Famous, Minho, BlackShadow (Minho and BS were demoted too as they had no scripts on the SDN, but I have repromoted them)

From the complete compilation log I can't see any attempt to compile their scripts.

**Comment by ChrisBPB** [comment]
I think BlackShadow is ok now

**Comment by ChrisBPB** [comment]
I demoted Famous and emptied his repo then promoted him and added it back and still nothing.

Also took his script and put it in my repository and it hasn't rebuilt anything, so doesn't seem to detect the changes


I'll leave it there for an hour or 2 and see if it eventually gets picked up.

**Comment by ChrisBPB** [comment]
Famous and Minho have now compiled

**Comment by ChrisBPB** [comment]
Snoop Dogg also affected

**Comment by ChrisBPB** [comment]
CodeRed too

**Comment by ChrisBPB** [comment]
and sliske

**Comment by ChrisBPB** [comment]
high priority pls x, we're missing so many scripts

**Comment by ChrisBPB** [comment]
I cloned Cody's repo and pushed each script one at a time on my own repo, first one went well and showed on the SDN, then I pushed the 2nd and it never rebuilt so I deleted it and pushed the 3rd, it rebuilt but the SDN was showing the 2nd script (which had been deleted..), I have no idea what's happening to be fair but I pushed a text file to Cody and Sliske's repos and then renamed it and pushed again and their scripts are back.

Can not get Snoop Dogg's or CodeRed's to work though

Seems like the SDN is building old pushes or something but it's just a mindfuck.

**Comment by ChrisBPB** [comment]
2 random pushes also 'fixed' dads repo (probably not a true fix but the scripts are back..)

**Comment by ChrisBPB** [comment]
ok I got everyones scripts back but I have no idea how I did it

**Comment by ChrisBPB** [comment]
actually I think Robert G is still down unless it's just delayed

**Comment by Paris** [comment]
This should be fixed now.
