### ISSUE TITLE
Scripts page is caching locally

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1121]
http://powerbot.org/scripts is getting cached by the users browser, this means they can see scripts that aren't there and can't see scripts that are there a lot of the time

**Comment by Paris** [comment]
Fixed

**Comment by ChrisBPB** [comment]
not fixed

**Comment by NexPB** [comment]
Still broken should be fixed asap kinda annoying, people see premium scripts still as free or don't see new scripts.

Regular users rarely hard refresh.

**Comment by ChrisBPB** [comment]
I agree, especially with OSRS going premium people think the site's just broke

**Comment by Paris** [comment]
I've added some code to disable local caching, hopefully it should be fixed now.
