### ISSUE TITLE
getting equipment ids

### ISSUE THREAD

**Issue by rs-sliske** [powerbot/powerbot#1123]
after some discussion / testing in the dev skype chat, we found the ids returned from appearance are offset (so the game can tell what player looks like when they arent wearing anything)

would be nice to be able to get the item id because that is going to be more useful

wrote a small method which cancels out the offset but would be nice to have something in the api

```java
public int getEquipmentID(final Player player,final int index){
	return player.appearance()[index] & 0xfffffdff;
}
```

**Comment by rs-sliske** [comment]
```java
public int getEquipmentID(final Player player,final int index){
	return player.appearance()[index] & 0xfffffdff;
}
```

**Comment by Timer** [comment]
What game version is this for?

**Comment by rs-sliske** [comment]
Osrs, might be useful in darkscape aswell but i havent tried it there

**Comment by rs-sliske** [comment]
https://github.com/powerbot/powerbot/issues/1123

**Comment by Timer** [comment]
See a70ea62278b309e00728d3ff05409c449fc4d422.
