### ISSUE TITLE
Could not download script

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1125]
Currently limited to a single user as of now.

Reference: http://www.powerbot.org/community/topic/1295799-one-specific-script-is-not-working/

Compiles and shows up on the repository fine.

**Comment by Paris** [comment]
Version 7018 will produce a more detailed error output which should help identify the issue, for now I really can't be sure where it's happening from.

**Comment by Paris** [comment]
See #1216.
