### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by iitc** [powerbot/powerbot#1126]
I have been implementing Gradle recently across all my projects and I found it could drastically improve the SDN. Many requests in the past have called for third-party libraries and Gradle could be used to monitor third-party libraries through a simple source-checking script on build, package them into the SDN jars, and allow the script writer to learn an invaluable skill of build automation.

**Comment by iitc** [comment]
This may also solve all the issues with developers not knowing what caused build issues with their scripts.

**Comment by Logicail** [comment]
I quite like the idea, I worry that the vast majority of scripts would have no need for it which will probably put @Paris off the idea. The only time I've personally used gradle was with android apps.

Couple of things to mention some of which were discussed on the Skype chat,
* Make it optional (detect existence of build.gradle file) so people can continue using the existing method and won't break existing scripts
* Would allowing dependencies to be added to the jar cause issues due to script size? some libraries could be 2MB+? which may cause issues for slower connections?
* Would allowing dependencies cause a security issue and how could they be alleviated (dependency on a repository outside of powerbot hosting a jar containing code that steals accounts etc.)

**Comment by iitc** [comment]
I wouldn't worry about security or size when integrating gradle. The size will only increase as more features are being added to scripts. It's a necessary size increase. Also you have access to all sources, including dependencies, within the build script to do source checking for malicious content.

**Comment by Paris** [comment]
This is a non-essential feature, there's absolutely nothing you can't do without it. The bot is designed to be lightweight and efficient, with a major focus on undetectability. When you start introducing third-party libraries you lose control over what objects are created on the heap and the order of the thread stack, which contributes to detectability.

While I accept that you're making requests that are *nice to have* from a business perspective it does not make sense for us to invest developer time into fancy features that we've been doing without just fine. You haven't made any Premium Scripts yet either, so it looks like you're making frivolous requests for the sake of it.

**Comment by iitc** [comment]
All of my feature requests that you've put down are in relation to third-party library support and exposing parts of your site/api for third-party applications. Gradle would've made your life extremely easy when it comes to allowing certain third-party libraries on a script by script basis rather than packaged into the client as a whole. I am not making frivolous requests for the sake of it, I've been sitting here waiting for github issues that have sat open for years to be addressed and closed. Like I've said plenty times before to you, you're not holding up your side of our agreement when I made the commitment to powerbot. When the client was ready, I was going to release my script collection. 

I can't even run scripts with debug information or a paint, #778. 
I can't create scripts that make use of trading/shop selling, #710. 
My script paints can't work properly for resizable without extensive workarounds, #807. 
The API is lacking in very important areas: #825, #826, #887, #1010, #1023. 
The API is broken in very important areas: #935, #953, #1032, #1075, #1078, #1109, #1110.

These are only issues related to my oldschool development. I left out rs3/ds specific issues or web-related bugs.

 Instead of putting your time into blaming me for not producing scripts, why don't you actually do what I've(we've) been asking of you for a long time? I spent months creating workarounds and patches for my scripts which was the motivating factor for removing my scripts from the SDN in the first place (no premium platform was the icing on the cake, not the initial motive). I'm not going to go through the same process when my scripts are actually supposed to be upheld to "premium" standards.

**Comment by Moosheplusplus** [comment]
@iitc In regards to #778, you could resize the overlay to force it to clear, which will clear it once, but you'll have to do that every time to clear the paint. It also doesn't seem to be only affecting RSBot. I've had the same issue with numerous programs in java (6-8 OpenJDK/Oracle) and repainting. It's possibly a system-dependent issue.

**Comment by Timer** [comment]
@Moosheplusplus this is a java bug not RSBot, we established this long ago -- just never came up with a good workaround, do you know of any other ways besides resize?

**Comment by iitc** [comment]
I think it's time to make the transition to Java 8, @Timer. lol I have the Java 8 fix on hand..

**Comment by Moosheplusplus** [comment]
@Timer no, every program which is susceptible to this issue gets cleared by resizing. However, RSBot is the only one which doesn't clear at all.

**Comment by iitc** [comment]
@Timer, here's something new that I haven't heard people trying. http://stackoverflow.com/a/31437149

**Comment by Timer** [comment]
@iitc what is this "java 8" solution?

**Comment by iitc** [comment]
It involves some JFX hackery, @Timer.

**Comment by iitc** [comment]
Feel free to try this also, http://stackoverflow.com/a/32542174.

**Comment by Moosheplusplus** [comment]
@iitc sun.java2d.noddraw [only affects] (https://docs.oracle.com/javase/7/docs/technotes/guides/2d/flags.html#noddraw) windows systems.

**Comment by iitc** [comment]
Woops. @Moosheplusplus nice find. lol

**Comment by iitc** [comment]
The most disliked actual solution for this problem, is recycling your dialog in between frames. Feel free to measure the cpu/mem usage of the approach but it's simple and works across the board.

**Comment by AnthonyOSX** [comment]
I don't think bothering with #778 is of any importance at the moment. The glitch is purely cosmetic and doesn't even pertain to more than a percent of the bots overall user base.

**Comment by iitc** [comment]
@anthonyosx, you act as if the issue hasn't been on the tracker for over a year. lol it's not a matter of prioritizing that single issue but actually running through issues quick enough to be able to address that issue within the next year..

**Comment by AnthonyOSX** [comment]
@iitc Completely agreed, I'd just rather issues be prioritized when they are actually being worked on :p

**Comment by iitc** [comment]
@paris, if you don't want to go full gradle, you could just support maven by itself. Packaging in local resources would be nice and maven handles it flawlessly.

**Comment by Paris** [comment]
This suggestion will be shelved for now.
