### ISSUE TITLE
Unexposed Dependencies

### ISSUE THREAD

**Issue by iitc** [powerbot/powerbot#1130]
The API has countless `org.powerbot.bot` and `org.powerbot.util` and `org.powerbot` class references. Is this intentional? I can simply ignore compile issues related to those classes if necessary.

**Comment by Paris** [comment]
Yes this [is intentional](http://www.powerbot.org/community/topic/1296179-open-source-api/); the API is provided as a reference not something which you can build against the bot since it's a closed source product.

**Comment by iitc** [comment]
@Paris I accomplished this by just doing a single branch clone of rsbot-api to the sub-directory, `src/org/powerbot/script`.

**Comment by Paris** [comment]
@iitc that's a clever method.

**Comment by Timer** [comment]
@iitc surely you can compile it against the RSBot.jar, no?

**Comment by rs-sliske** [comment]
@Timer i tried and it didnt work

**Comment by iitc** [comment]
@timer, the dependencies I'm talking about are the obfuscated ones. Mouse algorithm, client settings, etc.

**Comment by Timer** [comment]
@iitc oh well I see how that's a problem, if that's the case then yes you'll have to ignore them -- sorry. maybe we can look into a shell rsbot with no source to compile against.
