### ISSUE TITLE
Widget#valid() optimization rt4

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1156]
Right now, checking if certain Widget is valid only checks if it's index is valid and not if it's actually present. Can you optimize it do to something like in rt6 version of it: 
https://github.com/powerbot/powerbot/blob/rsbot-api/rt6/Widget.java#L82

**Comment by Timer** [comment]
Sure, see `return arr != null && index > -1 && index < arr.length && arr[index] != null && arr[index].length > 0;`.
