### ISSUE TITLE
TileMatrix.Draw(Graphics g) not drawing

### ISSUE THREAD

**Issue by FireFlyForLife** [powerbot/powerbot#1160]
doesn't draw anything. If iterating over the x and y of bounds with TileMatrix.getBounds().xpoints (or ypoints) and drawing those points it works.

**Comment by iitc** [comment]
For the record, `((Graphics2d)graphics).draw(matrix.getBounds())` works just fine.

**Comment by FireFlyForLife** [comment]
Also this is on rt4

**Comment by Timer** [comment]
It works fine, you must set bounds first.
I added a default case, though.
