### ISSUE TITLE
appearance ids

### ISSUE THREAD

**Issue by rs-sliske** [powerbot/powerbot#1172]
https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/Player.java#L50

```java
arr[index] = arr[index] & 0xfffffdff;
```

needs changing to either

```java
arr[index] = arr[index] < 512 ? -1 : arr[index] & 0xfffffdff;
```
(this will return -1 if they have nothing equipped)
or
```java
arr[index] -= 512;
```
(this will return a negative number if they have nothing equipped (-512 <= result < 0))

the current method only removes the offset if they have something equipped in that slot

if they have nothing equipped it will return the id of an item

**Comment by Timer** [comment]
Thanks for the analysis.
Accepted your commit (8c4255e2391ed0d22f97adb943807c6c58190be4).
