### ISSUE TITLE
Could Area#getTiles be made public?

### ISSUE THREAD

**Issue by SD8Z** [powerbot/powerbot#1173]

**Comment by AnthonyOSX** [comment]
Why don't you do it yourself and create a pull request?

**Comment by Timer** [comment]
Why do you need said method?

**Comment by SD8Z** [comment]
Nothing too fancy. I personally would just use it to draw the Area. Back in RSBot 2 there was a method that would draw the area but that is no longer here.
By having access to the array of tiles, a person could be able to get the TileMatrix and therefore draw each tile, which would be drawing the area.
Obviously this is just for aesthetic purposes, and (at least me) wouldn't draw an area bigger than 3x3.

**Comment by Timer** [comment]
@SD8Z the problem is we have to consider the viability of such a method and its memory implications when someone uses an area larger than 3x3. Can you not use the tiles you generated the area with? Or get the polygon and compute each point, constructing a custom polygon and drawing.
