### ISSUE TITLE
Parse equipment without opening tab

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1178]
Is it possible to parse equipped items without having to open equipment tab in rt4?

**Comment by rs-sliske** [comment]
Ctx.players.local.appearance

**Comment by ArtificialPB** [comment]
It returns wrong ids for a lot of items @rs-sliske

**Comment by Timer** [comment]
@ArtificialPB the appearance was fixed, but I can look into without opening tab (or did you fix that in your PR @ArtificialPB)?

**Comment by ArtificialPB** [comment]
I did not fix that in my pull request @Timer

**Comment by ArtificialPB** [comment]
Already merged, closing this.
