### ISSUE TITLE
Missing property for allowed trades

### ISSUE THREAD

**Issue by xXTheAwesomerXx** [powerbot/powerbot#1180]
There is currently no way to check if the allow trades property is currently enabled

**Comment by Paris** [comment]
This has been added for the next version: the [property](http://www.powerbot.org/rsbot/docs/org/powerbot/script/ClientContext.html#properties) for `trades.allowed` is `1` or `0`.

**Comment by Strikegently** [comment]
@Paris 
`trades.allowed` was not added to the properties.

**Comment by Paris** [comment]
I just checked @Strikegently and it's definitely in there, is it always `0`?

**Comment by Strikegently** [comment]
Last time I tested, it returned null.

I'll test again in a bit.

**Comment by Strikegently** [comment]
@Paris 
Yes, it wasn't added. It returns null.

**Comment by Paris** [comment]
Ah I think I know why, it's because you need to toggle the option at least once for the property to be set. I'll fix this and close.

**Comment by Paris** [comment]
Fixed for next version.
