### ISSUE TITLE
Bank pin not being entered

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1196]
Also bank.opened isn't returning true when bank pin screen is open (I think it should be?)

Main widget is 213, if needed then 213,7 contains the text "enter your pin"

Widgets for the numbers start at 213,16 and go every other one (i.e 213,16   213,18   213,20 ... 213,34, the value is found at 213,X,1

**Comment by Timer** [comment]
I need an account with a bank pin!

**Comment by Timer** [comment]
still need account with bank pin

**Comment by ChrisBPB** [comment]
I have a pin set now, let me know on Skype when you want it.

**Comment by ChrisBPB** [comment]
still an issue

**Comment by Timer** [comment]
added
