### ISSUE TITLE
Object names and actions are null (since update)

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1199]
Object names are null 

org.powerbot.script.rt4.GameObject[id=18491,name=null,type=INTERACTIVE,tile=(3208, 3221, 2)]

Above example is bank booth, some random objects still appear to have names.
![image](https://cloud.githubusercontent.com/assets/7156240/12170277/ce91ab7a-b537-11e5-9ac2-c31d26cb4423.png)

Some objects with names have the wrong name  - ladder = table
![image](https://cloud.githubusercontent.com/assets/7156240/12174262/79fc8244-b553-11e5-8b9a-cbaa986b3552.png)

Object actions are also all null

**Comment by Timer** [comment]
#1109
