### ISSUE TITLE
[rt4] Equipment Not Finding Ammo

### ISSUE THREAD

**Issue by sethrem** [powerbot/powerbot#1205]
Hello,
When trying to check item in quiver slot it returns nill and when you iterator through all your equipment it doesn't include your ammo even when the equipment tab is open.

**Comment by Timer** [comment]
@ArtificialPB see what you did?!

**Comment by ArtificialPB** [comment]
IIRC appearance() returns an array with length of 12 and there are 11 slots. It worked for all of the slots I tested, looks like the quiver slot might be offset then @Timer

**Comment by rs-sliske** [comment]
http://sliske.uk/img/captures/4716d90f26.png
https://gist.github.com/7287ac268dcf9b0f53b0

looks like you will need to go back to getting ammo from the widget (387,16,1)

maybe if the equipment widgets are visible, use them
only use the appearance if the widgets arent visible?

**Comment by rs-sliske** [comment]
after a quick test it seems ring doesnt work either

**Comment by Timer** [comment]
fixed
