### ISSUE TITLE
Keywords for scripts

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1206]
Would be nice if authors could add keywords or phrases to their manifest, for example - looking for a flax spinning bot on RS3 'flax' returns nothing, but ACrafter by @ArtificialPB does this. 

Bonus points for regex support, ((.*)? spinning)

**Comment by Strikegently** [comment]
I'm pretty sure that's what the description is for.

**Comment by ChrisBPB** [comment]
Descriptions should be concise, "All in one crafting script, with support for portables and harp playing"

Keywords "Flax spinning, jewellery crafting, glass blowing, harp, protean, portables"

**Comment by AnthonyOSX** [comment]
The description should also be scrollable on the scripts page. It's very difficult to describe your script in what appears to be something along the lines of 30 words or less, especially if it is an all in one or semi complex.

**Comment by k0na** [comment]
@AnthonyOSX I disagree here. Having a scrollable description will make the entire scripts page look messy (look at some of powerbot's competitors' websites), and it's fairly easy to describe your script as it is now. You don't need to list all its features in the description.

**Comment by Paris** [comment]
Closing for reasons mentioned by @k0na. I've tried to keep things simple and it seems to have worked okay so far with just the description alone. If we have sufficiently more complex scripts in future this is something we can revisit.
