### ISSUE TITLE
Local player health returning -1

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1208]
I think for npcs they have to be in combat for their health to show? If not, they are also returning -1.

Anyway, for the local player health and max health returns -1 when not in combat, I assume this is why combat scripts broke after the Zeah game update.

**Comment by NexPB** [comment]
Wasn't this always like this?

**Comment by Timer** [comment]
This is the intended behavior, use `ctx.combat.health()`.
