### ISSUE TITLE
Inventory queries require the inventory tab to be open

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1230]
Not sure if this is a bug or RS limitation but refreshing the inventory query yields an outdated result set if the inventory tab is not open.

**Comment by iitc** [comment]
If this is a restriction, I find this to be an appropriate location to force open a tab. Same goes for any other component-based query.

**Comment by Timer** [comment]
which game version?

**Comment by Timer** [comment]
you said inventory so assuming rt4 ...

**Comment by Timer** [comment]
I believe this should be left up to the script writer. They may want outdated results.
