### ISSUE TITLE
Add a non temp directory script storage location

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#1237]
Bringing this back up due to my users getting annoyed when their settings are cleared on almost a daily basis. This request was previously denied with the reasoning that scripters should persist data on their own servers, but I cannot see myself or others wasting their time with this when there is a perfectly acceptable solution that would take at most a few minutes to implement.

**Comment by AnthonyOSX** [comment]
Please don't forget about this!

**Comment by Paris** [comment]
If users have applications which clear caches we have to respect that. Storing persistent files creates a lot of clutter. I would advise you to instruct your users to disable their cache cleaning software, or select the option to only remove files older than 24/48 hours.
