### ISSUE TITLE
Hold higher standards for the Open Script Repository™

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1239]
The Open Script Repository serves as an educational resource for prospective developers. Developers that are new to RSBot will be looking at the scripts within this repository to better familiarize themselves with the API, and some may even be trying to learn java.

Erroneous scripts have been merged in the past (https://github.com/powerbot/powerbot/pull/1144, https://github.com/powerbot/powerbot/pull/1145). Right now, pretty much any pull request that doesn't look malicious is accepted and merged into the Open Script repository. The script can be erroneous or broken, and will still be accepted into the repository, for example, https://github.com/powerbot/powerbot/pull/1226. The script is only required by the current standards to have a valid script manifest and packaging, which some of them don't even have that.

I believe that before a script is merged into the repository, it should be reviewed by other developers to see if it can serve valuable to the users of RSBot and the prospective developers who want to learn how to write scripts. This does not defeat the purpose of the open repository, because the author will be able to get feedback from experienced developers to better improve their script, before users will be able to test whether or not it works. Implementing this will benefit the authors and users of RSBot.

**Comment by xXTheAwesomerXx** [comment]
Support, maybe not for every pull request but at least a every new script merge.

**Comment by Strikegently** [comment]
The purpose of the Open Script Repository is to give inexperienced developers the ability to share their scripts. There are no quality requirements for a reason: how can you expect a Script Writer to improve their scripts if they can't receive feedback on the functionality of their scripts?

Your entire argument is based on a misunderstanding of the intentions behind developing the OSR, and is backed by factually incorrect or misleading statements and assertions. 

We are keeping the OSR and we are keeping it as an open platform.

**Comment by Moosheplusplus** [comment]
You can and always have been able to comment on pull requests to provide feedback, as described in this issue.

I never said that the pull requests from non-script writers to be denied access to the repository, rather that it goes through the same exposure as it would in an application. The author would still be able to get feedback as they would normally. This benefits everybody: the user, the author, and the rsbot community.

The OSR should remain open to developers. All I'm saying is that before it's merged, it should be considered and reviewed by other developers.

With the current standards of the repository, an author can have a valid manifest and package name, and still be able to introduce a non-functional script to the repository, or worse, a script that does not properly use the API, and causes more harm than good to the users of the script.

You should at least allow discussion on this issue before closing it after 25 minutes.
