### ISSUE TITLE
Mac toolbar name

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1246]
Right now it just says "bin"

System.setProperty("com.apple.mrj.application.apple.menu.about.name", "RSBot");

**Comment by ChrisBPB** [comment]
mine says RSBot

**Comment by Foxies** [comment]
Mine also says "bin"

**Comment by Paris** [comment]
Seems to be a bug that's caused by the official client hijacking the names. I'll put this down as an issue related to the icon changing.
