### ISSUE TITLE
Abilities tab update

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1253]
When in Legacy Interface mode and in EOC combat mode, the bot is unable to open any of the abilities tabs: http://i.imgur.com/gY24z5w.png?1

**Comment by Timer** [comment]
I didn't know this was something we supported?

**Comment by ArtificialPB** [comment]
These are Hud.Window.RANGE_ABILITIES, etc.. In EOC combat mode and Legacy interface mode they are under the same tab.

**Comment by Timer** [comment]
ok @ArtificialPB will investigate

**Comment by Timer** [comment]
Added the ability to open the magic tab.
Please open a new issue for the sub-tabs.
