### ISSUE TITLE
Make dynamic objects show their parents id

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1255]
Prior to moving to reflection, dynamic objects showed its parent id and loaded child definition. For example, herb patch south of falador is a dynamic object with id 8150. Right now the client changes the id of the patch every time you interact with it because it changes state and therefore loads a different child definition. So in short, keep the id of the parent and load properties of the child.

You could just overload this method https://github.com/powerbot/powerbot/blob/rsbot-api/rt6/BasicObject.java#L43-L59 with a boolean argument to only return parent id.

**Comment by Timer** [comment]
This is purposely done to enable things like farming scripts. We can add a method that gets the parent id. By the way, that method is not where the id gets swapped -- that `getId` will always return the parent id.

**Comment by ArtificialPB** [comment]
This is really useless if you'd want to make a fully working farming script. It would even make it harder to develop because you'd have to find all of the ids instead of just getting an id of the parent. You'd then have to manually map each state (from varpbits) to child id so you'd know whit what object to interact. 

If someone wants to make a fully working farming script, instead of just making it work in a single location by standing there the whole time, they'd have to get familiar with vaprbits and dynamic objects.

**Comment by Timer** [comment]
Sorry I was thinking rt4 for my previous comment.

**Comment by ArtificialPB** [comment]
Yeah I understand the need for that for rt4. Could you change this only for rs3 then?

**Comment by Timer** [comment]
Added `mainId` helpers. If you want to select, use a filter instead of id on query.
See 362625b.
