### ISSUE TITLE
Reading from cache on demand

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1256]
We talked about this on Slack some time ago, just opening a request here as a reminder.

**Comment by Logicail** [comment]
Maybe genetics so we can do something like `load<GameObjectConfig>(id)` so we can manage the decode ourselves and add reading of things not in the api.

**Comment by ArtificialPB** [comment]
One way to solve null values would be by returning a nil wrapper when loading from cache fails.

I like what @Logicail proposed, being able to extend cache reading to other parts, not just what's currently supported in the API. Exposing CacheWorker and Block.Sector would be the simplest, yet the best solution in my opinion as it would give much more freedom to the developers.

**Comment by Timer** [comment]
Why not simply request things to be exposed or implemented so they can be done in a null safe way?

**Comment by ArtificialPB** [comment]
That's why I opened this request, to make the API support null safe cache reading. I just shared my opinion about it.

**Comment by ArtificialPB** [comment]
Here's a snippet of making item cache reading null safe: https://gist.github.com/ArtificialPB/6f1ace8b75d9bdf82959

**Comment by Timer** [comment]
Closed per #1268
