### ISSUE TITLE
Add support for additional collision flags

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1260]
Right now, CollisionMap#flagAt(int,int) only returns one of the supported flags (unless I'm missing something), but ignores all other flags on that tile. For example, the tile in the varrock palace, right next to the cage where Monk of Zamorak is in, returns 130 but when loading the flag for the same tile directly from cache returns 545326210.

**Comment by Timer** [comment]
We generate these ourselves and do not extract from the cache. Unfortunately we cannot provide things like range capable etc.
Feel free to make a PR which adds this capability.

**Comment by ArtificialPB** [comment]
Closing this for now, cache region reading does not produce valid collision data for some regions.
