### ISSUE TITLE
Can't push to the SDN

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1264]
As of today, I'm unable to push anything to the SDN. Here's what I get when the push gets rejected:
```
Counting objects: 10, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (10/10), 761 bytes | 0 bytes/s, done.
Total 10 (delta 6), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; result=22, HTTP code = 405
```

**Comment by Moosheplusplus** [comment]
Yes, I'm also experiencing this:

```
Counting objects: 58, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (58/58), 9.49 KiB | 0 bytes/s, done.
Total 58 (delta 25), reused 0 (delta 0)
error: RPC failed; result=22, HTTP code = 405
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

**Comment by Paris** [comment]
This is a very strange issue, which I'm putting down to a bug in Git itself since that's the only thing that has been changed. I'll try to rectify this ASAP.

**Comment by ArtificialPB** [comment]
New error:
```
fatal: unable to access 'https://www.powerbot.org/developer/git/388775/scripts/': The requested URL returned error: 500
```

**Comment by rs-sliske** [comment]
i get what appears to be same error as @ArtificialPB 

![https://www.powerbot.org/developer/git/9961/scripts/: 500 Internal Server Error](http://sliske.uk/img/captures/d94a224306.png)

**Comment by NexPB** [comment]
I can't push any updates either getting same error as @rs-sliske & @ArtificialPB

**Comment by ChrisBPB** [comment]
I also get 500 error, same as @rs-sliske & @ArtificialPB & @NexPB

**Comment by Strikegently** [comment]
This needs to be a priority.

**Comment by ChrisBPB** [comment]
yes, I can't even update ads

**Comment by tomHaum** [comment]
+1 for the 500 error

**Comment by Paris** [comment]
This has been fixed.
