### ISSUE TITLE
NegativeArraySizeException Inventory RT4

### ISSUE THREAD

**Issue by MaartenBoodts** [powerbot/powerbot#1269]
When I run: 
`        for (Item item : ctx.inventory.select()) {
            for (String s : item.actions()) {
                if (s != null)
                    System.out.println(s);
            }
        }`

or 

`        for (Item item : ctx.inventory.select()) {
            System.out.println(item.name());
        }`

I get a NegativeArraySizeException.

**Comment by Timer** [comment]
Always or only sometimes?

**Comment by MaartenBoodts** [comment]
I get this error everytime.

**Comment by ArtificialPB** [comment]
Just got this with objects:
```
java.lang.NegativeArraySizeException
	at z.Fc.long(al:152)
	at z.Fc.<init>(al:177)
	at z.Lpt3.long(ti:11)
	at org.powerbot.script.rt4.CacheObjectConfig.long(md:287)
	at org.powerbot.script.rt4.GameObject.id(lc:123)
	at org.powerbot.script.rt4.GameObject.name(lc:144)
```

**Comment by Timer** [comment]
This is caught and displayed; this happens when there's a concurrent write going on or the cache is malformed in sections.
To diagnose this fully @MaartenBoodts, I need a copy of ur cache. Alternatively, simply delete ur cache and let it redownload.
