### ISSUE TITLE
Ex-Script Writers can still submit scripts

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1283]
Sadfiesch was restricted over a month ago now I think because someone went on his account and he's failed to submit a virus scam to become unrestricted, so he doesn't have the SW rank

he can still however push updates to his scripts, which are still on the SDN.

**Comment by Paris** [comment]
The last successful push on his account was on the 26 December 2015, was this after he was banned? He would be able to authenticate but the no commits would go through if he lost his developer permissions.

**Comment by ChrisBPB** [comment]
Oh, I'm not sure.GoldenMidas (277789) also has scripts without SW

**Comment by Paris** [comment]
User ID 277789's last successful push was on 27 Nov 2015.
