### ISSUE TITLE
Scripts don't click sometimes

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1284]
Has happened for ages, but restarting your computer fixes it. It will hover the object and just not interact. People just assume the scripts broken.

Maybe @ArtificialPB has more information.

**Comment by ArtificialPB** [comment]
Nope, I have no idea why this is happening. I've only encountered this once so I don't really have any more information about it other than what you posted.

**Comment by ArtificialPB** [comment]
Just happened again for me. This error has been thrown when starting the client:
```
[SEVERE] java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0 
	z.cOm7.run(ch:133)
```

**Comment by Timer** [comment]
Fixed the exception.

**Comment by ChrisBPB** [comment]
this still seems to happen, seems to be a lot more frequent after a game update
