### ISSUE TITLE
Random spikes in withdrawing time

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1289]
The withdrawing part is fast (clicks withdraw with no delay), then it hangs afterwards with the items succesfully withdrawn, sometimes for as long as 9 seconds. I assume it's [this](https://github.com/powerbot/powerbot/blob/53cda921b0bc10eeeea65ca150ef9c74ef258dcf/rt4/Bank.java#L265) line causing the delay.

Apologies for the typo in 'inventory'

![image](http://i.imgur.com/olN80fK.png)

**Comment by AnthonyOSX** [comment]
#1072

**Comment by Timer** [comment]
This isn't a bug but an unintended consequence of depositing and withdrawing in rapid succession, I'll try to make a better check.

**Comment by Moosheplusplus** [comment]
@ChrisBPB How are you implementing this? I used to have issues with this because I was selecting the inventory and checking if it were empty, and then depositing the inventory. Doing this seems to cause no delay:
```java
ctx.bank.depositInventory(); // won't bother depositing unless inventory is empty
ctx.bank.withdraw(item, 28);
```

**Comment by ChrisBPB** [comment]
well the first item (it's 14 of each) withdraws at a good pace (<2s) so I imagine if it was a full inventory (28) it'd be fine too but the 2nd item is where the delay happens 

```
ctx.bank.depositInventory();
ctx.bank.withdraw(bowString, 14);
ctx.bank.withdraw(unfBow, 14);
```

is my implementation

**Comment by ChrisBPB** [comment]
unable to replicate now, times seem consistent and no noticeable delay
