### ISSUE TITLE
Canvas repainting issue on Ubuntu 15.04

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1295]
The canvas is not being cleared after painting for one of my script users
Happening on RSBot v7022. It could be related to https://github.com/powerbot/powerbot/issues/778

![](http://i.imgur.com/NfRBEFx.png)

**Comment by Paris** [comment]
What Java version are you running? Also have you tried Safe Mode?

**Comment by ArtificialPB** [comment]
I'm not sure about it as it's not happening to me. I'll post additional information if I get any.

**Comment by Moosheplusplus** [comment]
This issue has been fixed in #778 for the most part. I believe this is an issue with Ubuntu itself. This happens to me on occasion, but you can just force it to repaint properly by resizing or minimizing the overlay, and it should work properly again.

**Comment by ChrisBPB** [comment]
Happens on openjdk 8 update 71

**Comment by Moosheplusplus** [comment]
@ChrisBPB I've tested it before on Oracle's Java; it's not specific to any version or variation of java. In #1126, it was determined it's an [OS-specific](http://stackoverflow.com/a/31437149) issue with per-pixel-transparency.

**Comment by ChrisBPB** [comment]
Don't know if it's the same for anyone else but as of 7024 it isn't having this issue anymore

**Comment by Moosheplusplus** [comment]
@ChrisBPB yep, it's still happening for me.

**Comment by ChrisBPB** [comment]
ok it's inconsistent for me, restarted RSBot on all VPS' and 1 of them started doing it again but the other 4 are still fine (and this one was also prior to restart)

**Comment by Moosheplusplus** [comment]
There's also an issue in Ubuntu 16.04, Gnome 3 where the overlay will remain white, even when resized/minimized.

![desktop](https://i.imgur.com/pkycQDb.png)

**Comment by Paris** [comment]
What java version are you using @Moosheplusplus?

**Comment by Moosheplusplus** [comment]
@Paris I've tried versions ranging from 6-8, from both oracle and OpenJDK; they all have this issue.

**Comment by Moosheplusplus** [comment]
Not sure if relevant, but this was being thrown and the overlay wasn't clearing.

> [SEVERE] java.lang.NullPointerException 
>	z.Com7.break(dh:179)
>	z.com7.run(dh:94)
>	org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:697)

**Comment by ChrisBPB** [comment]
Unable to replicate, please reopen if you have a system that still has this error

**Comment by Morganb816** [comment]
Can replicate on Ubuntu 18. Client flickers white untill i try to move client window to other monitor then it will stay white. Or if i try to change window size it will stay
`[SEVERE] Exception: java.lang.IllegalStateException: Buffers have not been created 
	org.powerbot.gui.com3.this(BotOverlay.java:194)`
