### ISSUE TITLE
Add "Staff" tab to forum theme "Animate"

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1300]
Picture of what I'm talking about: http://i.imgur.com/4EzPmmj.png?1

**Comment by rs-sliske** [comment]
http://sliske.uk/img/captures/b4d22cc528.png

it already shows for me, maybe they just need to change which usergroups it shows for

**Comment by ChrisBPB** [comment]
done

**Comment by Timer** [comment]
@ChrisBPB stop locking and limiting these, just close em
