### ISSUE TITLE
Show main object id when debuging objects

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1301]
Make the client also show main id when debuging objects (View -> Objects in the client).

**Comment by Logicail** [comment]
I'd expect that to confuse people, can't you just display it yourself?

**Comment by ArtificialPB** [comment]
When checking objects in game it's not always clear which are normal ones and which are dynamic so I'd basically have to check for every object manually. I would just like some way to distinguish dynamic object by debuging in the client. Maybe add a dynamic boolean next to it's name instead of displaying main id.

**Comment by Timer** [comment]
We can add this, ya.
