### ISSUE TITLE
Not attaching properly on Ubuntu 15.04 vps

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1308]
Only error thrown is 

[SEVERE] java.lang.UnsupportedOperationException: PERPIXEL_TRANSLUCENT translucency is not supported 
z.Com9.<init>(zk:305)
z.Nb.run(ck:65)

---

Xfce4

**Comment by Paris** [comment]
Need to start safe mode by hitting `s` while the game loads.

**Comment by ChrisBPB** [comment]
I tried that but it didn't help

**Comment by Paris** [comment]
Due to the multitude of different configurations on Linux there's nothing we can really do to solve this.
