### ISSUE TITLE
Object definition impl

### ISSUE THREAD

**Issue by Polish-Civil** [powerbot/powerbot#1310]
Like comon, you have definition loader, ok you don't share it that's fine but at-least implement all the getters in game object... RS3

**Comment by Timer** [comment]
Enlighten me to what you need, please.

**Comment by Polish-Civil** [comment]
`
public int xSize;
public int ySize;
public boolean isObjectBlocked;
`

from 

> CacheObjectConfig

to

> GameObject

**Comment by Polish-Civil** [comment]
???????????????????????????????????????

**Comment by ArtificialPB** [comment]
Make a pull request with this additions.

**Comment by Polish-Civil** [comment]
If i only could even compile ... I don't want to waste my time

**Comment by Timer** [comment]
@Polish-Civil do you really need isObjectBlocked? What are you doing with all this anyway?
You know we already have a collision map.

**Comment by Polish-Civil** [comment]
U don't have, if so enlighten me. (landscape's debug for example, the one showing red dots is not right so i assume u dont have proper collision map as well as the pathfinding)

**Comment by ArtificialPB** [comment]
@Polish-Civil Collision flags are currently computed by the client using objects query. https://github.com/powerbot/powerbot/pull/1262 will add support for all of the collision flags by parsing them directly from rs cache.

**Comment by Timer** [comment]
@Polish-Civil our pathfinding works without error, if it doesn't, you should give us an example region where it is broken so we can fix it.
As @ArtificialPB, the collision flags are currently computed but miss various flags like projectile capabilities.

**Comment by Timer** [comment]
@Polish-Civil 
you can use our pathing utilities like so
`final Path p = ctx.movement.findPath(new Tile(0, 0, 0));`
or get the raw collision map using `ctx.movement.collisionMap()`, you can use the `flagAt` helpers or modify the map yourself with the `mark*` helpers.

**Comment by Polish-Civil** [comment]
@Timer 
Nope, it always return -1 @ collision flag for me
Also your collision's map are enums wich i don't like as well (even if they did work)
The ctx.movement thingy maybe generates path but as always i cannot even get that path 'tilepath' (or something) because its hidden.

To summarize: your api is too tight and slow for my things and i'd love to have things i posted in this issue. This is not something that you will spend hours on, so saying you have problem fulfilling my request is kinda weird.

I wouldn't do it if your api were more open to scripters/written better.

**Comment by Timer** [comment]
@Polish-Civil you seem pretty mad at the world and seem offended that I simply asked you why you were requesting such things? People tend to have reasons for stuff.

Also, there was no bug before, you were probably using it incorrectly. Feel free to ask for any information on how it works. Since you closed this, I assume you don't need it anymore.

**Comment by Polish-Civil** [comment]
@Timer Ye, brainfart at its finest. Turned out i were mad at myself recently and it went outside. Sorry for behavior.
