### ISSUE TITLE
Overlay will flicker white

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1315]
The overlay will flicker white. I'm not sure if this has to do with #1295, but seems to occur frequently whenever something such as varpbit explorer, widget explorer, or bounding tool is open. 

![Image](https://i.imgur.com/FyZATwQ.gif)

**Comment by ChrisBPB** [comment]
are you sure this isn't just a result of remote viewing?

**Comment by Paris** [comment]
Going to merge this into #1295.
