### ISSUE TITLE
Highlight the parents of searched components in Widget Explorer

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1316]
If a child component matches text when searched for, it will be highlighted red, however, if it's a child component of another component, the parent component isn't highlighted red, so we have to expand all of the different components to find it.

Example:
- Widget 105
  - Component 0
  - Component 1
    - Component 0
    - **Component 1**
  - Component 2
    - Component 0
    - Component 1

Desired:
- Widget 105
  - Component 0
  - **Component 1**
    - Component 0
    - **Component 1**
  - Component 2
    - Component 0
    - Component 1

**Comment by Strikegently** [comment]
This is in the next release.
