### ISSUE TITLE
Movement via minimap broken

### ISSUE THREAD

**Issue by PorkScripts** [powerbot/powerbot#1319]
Some widget IDs changed with the minimap in the latest RuneScape update which broke movement#step and shit.

**Comment by Moosheplusplus** [comment]
is this RS3 or OSRS

**Comment by PorkScripts** [comment]
Oh, it's RS3

**Comment by benjaminpott** [comment]
Still a problem - thanks for working on the fix!

**Comment by Timer** [comment]
fixed thanks to @Moosheplusplus

**Comment by benjaminpott** [comment]
how do I get the latest version on my computer?

**Comment by Moosheplusplus** [comment]
@benjaminpott wait for RSBot 7024 to be built. Should be built soon. You can get RSBot from [powerbot.org](http://powerbot.org/).

**Comment by benjaminpott** [comment]
Awesome - thanks @Moosheplusplus - I'll check back later today.
Is there any way to run the PowerBot java by cloning this git repo locally?

**Comment by Moosheplusplus** [comment]
not without the class map, so no.
