### ISSUE TITLE
Input keyboard press key?

### ISSUE THREAD

**Issue by Polish-Civil** [powerbot/powerbot#1322]
I don't see any functionality to press virtual key. Atm resolved by implementing the keyboard by my own, but it should be inside api IMHO.

**Comment by Strikegently** [comment]
`input.press(int key)`

**Comment by Polish-Civil** [comment]
U gotta be kidding with such comment right? This is going to be my last issue posted as well as the comment.

![9zylluc](https://cloud.githubusercontent.com/assets/10587799/13242726/3a4579c0-d9f8-11e5-99a6-8d75b2e3c4d8.png)

As well as your doc's say public abstract boolean press(int button)

"BUTTON" I clearly say keyboard,key,virtual key.

**Comment by Strikegently** [comment]
You do realize that virtual keys are represented as integers, correct?

https://docs.oracle.com/javase/7/docs/api/java/awt/event/KeyEvent.html

**Comment by Polish-Civil** [comment]
Yes i do. so what?

 @Timer can u fix this please. If not i'd love to hear why its not 'worth' it.

**Comment by Polish-Civil** [comment]
ctx.input.send("{VK_SOMETHING}")

**Comment by Timer** [comment]
You know, you should ask these things in the developer chat and get an answer before doing your own extensive development.
