### ISSUE TITLE
Component.scrollX() and scrollY() always remains 0 for rt6

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1324]
Component.scrollX() and Component.scrollY() will always remain 0, even if the thumb has been scrolled past 0.

![Widget Explorer](https://i.imgur.com/SrPUVDA.png)

**Comment by Timer** [comment]
You need to look at 57, I believe.

**Comment by Timer** [comment]
@Moosheplusplus the scroll isn't in the scroll bar component. scrollX and Y will change on the viewport rect for the page to the left of the scroll bar.

**Comment by Moosheplusplus** [comment]
ah I see, my bad

**Comment by Timer** [comment]
No, questions are good!
You can see https://github.com/powerbot/powerbot/blob/rsbot-api/rt6/Bank.java#L368 to get a better idea of what component you should be looking at.
Or, let me remind you that a scroll API already exists in the API.
