### ISSUE TITLE
CombatBar bar index 5 returns nil actions

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1326]
![Combat Bar](https://i.imgur.com/U9qLJw6.png)

Will translate to:
`[6] Actions: -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1`

Only happens on bar index 5.

**Comment by Timer** [comment]
spanks

**Comment by Strikegently** [comment]
#1027

**Comment by Timer** [comment]
done per @Strikegently suggestion
