### ISSUE TITLE
Internal error "Malformed class name"

### ISSUE THREAD

**Issue by Polish-Civil** [powerbot/powerbot#1328]
`[SEVERE] java.lang.InternalError: Malformed class name 
	org.powerbot.bot.nUl.toString(ej:303)
	org.powerbot.bot.Con.else(ej:190)
	org.powerbot.bot.Con.else(ej:93)
	org.powerbot.bot.rt6.client.Client.getWidgets(h:142)
	org.powerbot.script.rt6.Widget.else(pb:41)
	org.powerbot.script.rt6.Widget.component(pb:295)
	org.powerbot.script.rt6.Widgets.component(lb:17)
	org.powerbot.bot.rt6.Com3.poll(ae:292)
	org.powerbot.script.PollingScript$6.run(mj:191)`

Happens occasionally tho. with 7024

**Comment by ArtificialPB** [comment]
https://github.com/powerbot/powerbot/issues/1197

**Comment by Timer** [comment]
Merging into #1197, we'll get this fixed asap.
