### ISSUE TITLE
Request for additional Component methods

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1329]
- viewportRect()
- scrollWidthMax()
- scrollHeightMax()

**Comment by ArtificialPB** [comment]
Forgot to say, this is for rt4.

**Comment by Timer** [comment]
`scrollWidthMax` should just be `scrollWidth` afaik

**Comment by Timer** [comment]
Oh you're right @ArtificialPB we're missing hooks for this

**Comment by Timer** [comment]
Are you sure the existing scroll method doesn't work?

**Comment by ArtificialPB** [comment]
It's not that the existing scrolling method does not work, but I think you need this methods to implement mouse scrolling feature for rt4: https://github.com/powerbot/powerbot/issues/1330

**Comment by Timer** [comment]
No, the `scrollHeightMax` is to single-click the bar, not scroll with mouse.

**Comment by ArtificialPB** [comment]
Oh ok. Ignore this request if you can add mouse scrolling without the above methods.

**Comment by ArtificialPB** [comment]
Not needed anymore, closing.
