### ISSUE TITLE
AbstractScript#download doesn't properly download via HTTPS

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1333]
Possibly an issue with `org.powerbot.util.HttpUtil`

**Comment by Paris** [comment]
Details?

**Comment by Moosheplusplus** [comment]
If I were trying to download this image ( ![Cursor](https://i.imgur.com/FyUMGqJ.png) ) using HTTPS it would just return a 1x1 empty image.

If I were trying to download this [plaintext](https://paste.debian.net/plain/410323) using AbstractScript#downloadString and HTTPS, it would return an empty string.

However, if I were to switch to using HTTP, it would work properly.

**Comment by Paris** [comment]
There is a known issue with HTTPS on Github and Java, something to do with the type of encryption and SSL certificates they use. It's not something we can change on our end unfortunately.
