### ISSUE TITLE
Script and paint freezing

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1338]
Happened two times in the past couple of days. The only thing that sometimes fixes it is to logout to the lobby and log back in. Happened only in rt6. I currently don't have any other information about it.

Does anybody else experience this?

**Comment by ChrisBPB** [comment]
I get heapoverflow which crashes the paint but it's due to the canvas issue not being cleared

**Comment by ArtificialPB** [comment]
Could it be due to raising recursion depth to 50? https://github.com/powerbot/powerbot/blob/rsbot-api/rt6/Component.java#L21

**Comment by Timer** [comment]
No, that recursion depth is what should of fixed that problem originally @ArtificialPB.

**Comment by ArtificialPB** [comment]
I know @Timer. All I'm saying is that maybe a value of 50 is a bit too much and may be causing problems. I'll let you know if this issue still happens in v7025.

**Comment by AnthonyOSX** [comment]
Seems to be happening to my rt4 scripts as well.

**Comment by ArtificialPB** [comment]
I've got a log report about this and the script froze for 5 minutes in a bank close method call (```ctx.bank.close()```). This is still on v7024

**Comment by ArtificialPB** [comment]
Script froze again when trying to interact with a npc on v7025.

**Comment by ArtificialPB** [comment]
Happened again when trying to walk, most likely on this method call because I have debug messages before and after it and the message after was not printed:
```
tile().matrix(ctx).onMap()
```

**Comment by ArtificialPB** [comment]
This needs to be a high priority issue. A lot of my slayer script users are dying because the script freezes mid-combat and stops eating.

What solves this issue is manually logging out/ to the lobby and logging back in, possibly because new data gets loaded.

**Comment by ArtificialPB** [comment]
Seems to be solved now.
