### ISSUE TITLE
Not going past lobby (auto login)

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1340]
On RS3 it will log in (types super slow for some reason too) and then just sit in the lobby.

**Comment by Moosheplusplus** [comment]
Lobby components changed. I'll submit a PR soon.

**Comment by ChrisBPB** [comment]
@Moosheplusplus setting that in the script affects the login handler?

**Comment by Moosheplusplus** [comment]
@ChrisBPB no, I don't believe so. I thought you meant just in general.

**Comment by Timer** [comment]
fixed by @Moosheplusplus
