### ISSUE TITLE
input.send() "IllegalArgumentException" for ?

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1342]
You can't send a question-mark with input.send()

```
[SEVERE] java.lang.IllegalArgumentException: invalid keyChar (?) 
	org.powerbot.bot.COm2.else(ih:396)
	org.powerbot.bot.COm2.else(ih:448)
	org.powerbot.bot.COm2.send(ih:558)
	org.powerbot.script.Input.sendln(uh:166)
```

**Comment by Moosheplusplus** [comment]
From the [KeyEvent javadocs](https://docs.oracle.com/javase/6/docs/api/java/awt/event/KeyEvent.html):
> Not all characters have a keycode associated with them. For example, there is no keycode for the question mark because there is no keyboard for which it appears on the primary layer.

Try sending one using `{VK_SHIFT}` and `{VK_SLASH}`
