### ISSUE TITLE
Request to keep painting/block input until controller is stopped

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1360]
If the script controller is stopping, it will no longer call repaint(), even if the script has yet to stop. I propose that the script is still painted (and user input to remain blocked) while the controller is stopping, to prevent the player from interrupting the script from completing certain tasks.

**Comment by Strikegently** [comment]
If the script doesn't stop after the user presses the Stop button, then the script is designed improperly. I don't believe that core client functions should be modified to adapt to poor design principles.

**Comment by Moosheplusplus** [comment]
@Strikegently I've only experienced this issue when waiting for API calls to finish. For example, Bank#open(), which doesn't break until [after the player has stopped moving](https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/Bank.java#L127-L134) and interacted with the object/NPC, only to do the [same wait condition](https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/Bank.java#L136-L141) (under another anonymous class that does the same thing as the previous one).

**Comment by Paris** [comment]
This is by design, the user experience is poor when paint is still visible as it signals to them that things aren't being stopped. Your script should be designed with as few time based loops as possible so it can fail fast, ideally within half a second.
