### ISSUE TITLE
Bank#open() will try to open non-functional bank booths

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1361]
This will attempt to open non-functional bank booths (Object ID 6946) instead of bank booths which are usable (Object ID 9493).

![Bank Booth](https://i.imgur.com/dYHFeqg.png)

**Comment by ArtificialPB** [comment]
Don't use object/npc ids in osrs because they change with every update. You can make a pull request by adding action filters to this two queries: https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/Bank.java#L41-L42

**Comment by Timer** [comment]
Yeah, what tile is this object on?

**Comment by Moosheplusplus** [comment]
@Timer 
3096, 3242, 0
3096, 3241, 0
3096, 3245, 0

**Comment by Timer** [comment]
ok thanks @Moosheplusplus
