### ISSUE TITLE
Disable dismissing random events via Script Manifest properties

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1362]
I request a property to disable the bot from dismissing random events automatically, so the script can handle certain random events itself.

**Comment by Paris** [comment]
Which random event specifically because there was a property for disabling widget closer.

**Comment by Strikegently** [comment]
@Paris 
He asked for "certain" events, so I assume he wants a property for each random event individually.
We could probably have a property for each. It might get messy, though.

Potentially clean it up by adding a constants for all the available properties.

**Comment by Moosheplusplus** [comment]
for example, the ones that could be solved with just a single conversation (such as the genie or mysterious man).

**Comment by Paris** [comment]
In that case would it not be better for the bot to handle those conversations itself?
