### ISSUE TITLE
Backpack is borked

### ISSUE THREAD

**Issue by PorkScripts** [powerbot/powerbot#1363]
Checking if items in the backpack are valid with the valid() method always returns false: ctx.backpack.select().id(...).poll().valid(). Viewing the IDs by going to View > Items in RSBot's menu is also not working. Components were changed around in Widget 1473 from the last RS update.

**Comment by Strikegently** [comment]
#1364

BACKPACK_CONTAINER should be 5, not 4.
That should fix the issue (for real this time).
