### ISSUE TITLE
Disable dismissing Random Events if the script is paused or input is allowed.

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1373]
If input is allowed or the script is paused, that's typically an indication of the player themselves controlling the client, therefore, if a random event appears, the player will fight over the input with the bot.

**Comment by Paris** [comment]
In light of #1386 do you think this is still required?

**Comment by Strikegently** [comment]
@Paris 
Yes, but only if mouse control is allowed. That would probably be best, I think.

**Comment by Moosheplusplus** [comment]
Fixed in #1512.
