### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1375]
Show update notification when user clicks the "Script" menu option, rather than "Loading".

**Comment by Paris** [comment]
Do you mean when the packs are processing after a game update? Because if they click the *Loading..." menu item it brings up a message dialog with this information.

**Comment by Strikegently** [comment]
I want them to see the message as soon as they click "Script" instead of requiring them to click "Loading..."
Most people don't actually click the "Loading" button, they just post a thread in Support asking why it says "loading."

**Comment by Paris** [comment]
Done for the next version.
