### ISSUE TITLE
Breakhandler or killtimer for VIP users

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1412]
Free users have their scripts killed at 4 hours but VIP members will go until the script stops because even if they don't supply a username/password RT6 logs them back in and RT4 will soon™ (https://github.com/powerbot/powerbot/issues/1299). Some people don't want to bot for such long periods in one go and not everyone stays at their computer to stop the script.

**Comment by Moosheplusplus** [comment]
They can use crontab to kill the RSBot process at a certain time. Breaks introduce a new pattern not unique to the user which Jagex can detect.

**Comment by rs-sliske** [comment]
killing the process seems just as likely to cause pattern problems imo

no legit players force close the client to go afk for 10 - 15 mins, or even when they are closing rs completely
