### ISSUE TITLE
Player#name space byte value is -96 not 32

### ISSUE THREAD

**Issue by stumpy3toes** [powerbot/powerbot#1415]
http://www.powerbot.org/community/topic/1310365-rt4-issue-with-playername/

**Comment by stumpy3toes** [comment]
It appears it might be a server-side thing, the message that appears in the chat box when someone attempts to trade with you also has -96 as the byte value for a space but only in the players name part of the message string and the same for the trade window where it specifies who you are trading with

**Comment by Timer** [comment]
What would you like us to do about this?

**Comment by stumpy3toes** [comment]
Ian C on the PB forums suggested "to clean the strings and change all whitespace to a single whitespace character"
Also btw it's not -96 that was a mistake on my behalf I was using the wrong function to print the values, it's 0xA0 (160) which is a non-breaking space

**Comment by Timer** [comment]
We cannot do this on the API level because some scripts may have already come to depend on it. Please handle this within your script[s].
