### ISSUE TITLE
OSRS Object location offset

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1417]
Locations for some objects with the same orientation, namely doors, are offset. Is this one of the anti botting measures of OSRS or a bug?

**Comment by Moosheplusplus** [comment]
are you sure they are the same orientation? The way OSRS handles doors is very wonky (they move to different tiles and orientation depending on their state).

**Comment by ArtificialPB** [comment]
I checked again and I was wrong about those two doors having the same orientation @Moosheplusplus
OSRS door handling is really weird. I'll check out if there's any way to predict these weird tile changes.

**Comment by Moosheplusplus** [comment]
@ArtificialPB yeah, I was working with doors a while back in OSRS, and it's very annoying. I believe they move to different tiles in order to generate paths.

**Comment by Moosheplusplus** [comment]
@ArtificialPB can this be closed?

**Comment by ArtificialPB** [comment]
@Moosheplusplus it should be opened until it's confirmed it can't be fixed.

**Comment by Moosheplusplus** [comment]
what needs to be fixed @ArtificialPB? I thought this was just doors moving tiles entirely.

**Comment by ChrisBPB** [comment]
@ArtificialPB can you elaborate on this issue?
