### ISSUE TITLE
Investigate Java 8 SDN upgrade

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#1418]
- Determine feasibility 
- Potentially find a way to alert users who are using <Java 8

**Comment by iitc** [comment]
Good guy Coma.

**Comment by Paris** [comment]
Postponing due to NXT.

**Comment by Paris** [comment]
Due to Java 6 on OS X and NXT there doesn't seem to be a compelling reason to switch.

**Comment by Paris** [comment]
Since Apple Java 1.6 no longer works we'll be moving to Java 8.

**Comment by Paris** [comment]
The SDN now uses Java 8, which is now the new minimum version of Java that is required to run the bot.
