### ISSUE TITLE
Force left click ctx.bank.open()

### ISSUE THREAD

**Issue by Zarama** [powerbot/powerbot#1419]
Could you possibly overload `Bank.open()` function to left click bank?
There are times when we are standing at places where the bank is behind mobs and then makes it right click bank. 
This just causes delays and lags.

`Bank.open(boolean left_click)`

**Comment by Strikegently** [comment]
>There are times when we are standing at places where the bank is behind mobs and then makes it right click bank.

Well no shit. If the bank is behind another entity, it needs  to right click so it can open the bank.

**Comment by Zarama** [comment]
Not really, it can still left click. 
That's why we should allow for the overloaded function, so we can left click. 
A human wouldn't right click on a bank chest when they can clearly see it and click it.

**Comment by ArtificialPB** [comment]
@Strikegently The problem sometimes arises if there are too many people standing beside the bank. Index of bank opening menu action wont be the first one and it's usually off-screen. This causes the bot to get stuck in a continuous loop right-clicking the bank while it can be opened by left-clicking it.

I've solved this in my RS3 scripts by checking if the object can be right-clicked by calculating if the menu index will be off-screen or not and then checking if the tooltip while hovering the object is the same as the desired action (in this case it would be "Open"). If tooltip action and option match the ones provided, do a left click.

**Comment by Timer** [comment]
The menu needs to be fixed before this can be done.

**Comment by Timer** [comment]
dependent on #1032
