### ISSUE TITLE
RT4 Inventory empty when widget 300 is visible

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1420]
When Widget 300 (Trading with NPC), inventory selection returns empty (even though Widget 149 Component 0 still retains all item IDs).

Not sure if related to #1414.

**Comment by ChrisBPB** [comment]
similar to https://github.com/powerbot/powerbot/issues/1414 the inventory isn't visible but it does actually update properly if the inventory changes 

the items can be found in 301-0 though but again similar to the other issue not in the same way (id - stacksize http://i.imgur.com/DEJdjFo.png)
