### ISSUE TITLE
ctx.players.local().appearance() array length too short

### ISSUE THREAD

**Issue by stumpy3toes** [powerbot/powerbot#1423]
I noticed that ctx.equipment.itemAt(Slot) was working with the HEAD slot but not the RING slot, I investigated the API and noticed if the equipment widget wasn't visible then it would fallback on ctx.players.local().appearance() for the player worn item ids. Turns out the RING slot index is 12 and the appearance array has only 12 indexes. I wore only a ring item and all ids in the appearance array returned -1 so its not a problem with 12 being the wrong index for RING. So the array is being cut short for some reason

**Comment by rs-sliske** [comment]
ring isnt visible in appearance, you can only get it from the widgets
