### ISSUE TITLE
Valid broken for gameObjects

### ISSUE THREAD

**Issue by MaartenBoodts** [powerbot/powerbot#1437]
Game object *OreVein* (in motherlode mine) returns `false` to `vallid()` the moment you start mining it.
Should return `false` if the vein is depleted.

**Comment by Moosheplusplus** [comment]
The GameObject may change while the player interacts with it, leading it to being invalid.

**Comment by MaartenBoodts** [comment]
Tested it again. Now it .valid() returns false after a few seconds, even without touching it.

**Comment by ArtificialPB** [comment]
@MaartenBoodts Turn object debugging on and check if any ids change after it's not valid anymore.

**Comment by Timer** [comment]
We cannot change how the game engine operates. Sorry!
