### ISSUE TITLE
Possible for RSBot to download jagexappletviewer?

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1441]
On Mac it already does this if it doesn't exist but on windows it just won't launch. Is it possible to make it work the same way because with the NXT release less people seem to have the legacy client installed and despite specific instructions on the how-to thread, a lot of people just don't seem to get it. With no error output when it doesn't exist they don't know why RSBot isn't working.

**Comment by Moosheplusplus** [comment]
iirc it already installs jagexappletviewer.jar and stores it in ~/.rsbot/

**Comment by ChrisBPB** [comment]
Oh, guess it wouldn't help then

**Comment by Paris** [comment]
Can confirm it already does.

**Comment by Strikegently** [comment]
It doesn't work properly on Windows for whatever reason. Perhaps if the applet viewer isn't found, rather than downloading it and attempting to run that, we should prompt them to install the legacy client.
