### ISSUE TITLE
Bounding Rectangles are off for items in Grand Exchange widget

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1442]
The bounding rectangles are off, but item information is accurate.

How they look opened up in G.E.
![Image of Widget](https://i.imgur.com/xAXK3wt.png)

How they look normally:
![Image of Inventory](https://i.imgur.com/3PGt6bX.png)

**Comment by Moosheplusplus** [comment]
Off by 16,8 pixels.

**Comment by Timer** [comment]
fixed
