### ISSUE TITLE
Script stats page not working

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1444]
It shows the loading bar for a second and then it just stays at a blank page. The page does not load even after refreshing it multiple times.

**Comment by ArtificialPB** [comment]
Is there any way to access compile log without loading the stats page? I need to solve compile issues for one of my scripts.

**Comment by k0na** [comment]
Any update on this @Paris?

**Comment by k0na** [comment]
This appears to be fixed

**Comment by ArtificialPB** [comment]
This has been fixed.
