### ISSUE TITLE
some scripts dont seem to end cleanly, causes client to run slow

### ISSUE THREAD

**Issue by rs-sliske** [powerbot/powerbot#1445]
not great at explaining things :(

basically if i open a new rsbot client and start a script, it runs fine.

if i stop the script and start a new one without restarting the client, it runs a lot slower, and gets slower for each additional script start until the client gets restarted

ive noticed it with my own scripts, and when i asked on slack it had been noticed in other users scripts aswell

**Comment by Paris** [comment]
Need to investigate memory leaks.

**Comment by Strikegently** [comment]
Maybe some system resources that aren't released or threads that aren't stopped.
CPU usage increases quit a bit, which would lead me to believe it's the latter.

**Comment by Strikegently** [comment]
Maybe we could keep a thread group for all script-started threads. 
If a user starts a script, kill all threads in the script thread group to ensure no lingering resources.

**Comment by Paris** [comment]
Unless there is anything specific we can debug there's not much we can do.
