### ISSUE TITLE
Nicer way of adding things to the options menu

### ISSUE THREAD

**Issue by rs-sliske** [powerbot/powerbot#1448]
was trying to help someone with this the other day on slack, and the only way i found to add to that menu was very messy, and not user friendly (didnt matter that much as it was only being used for debugging)

ive seen users on the site asking why the options button doesnt do anything, and i think it would be used more if it was easy to use

possible solutions -
1 - make options a submenu, and give script (or ctx) a method to add a MenuItem to it, 
2 - make the frame variable accessible (probably not a good idea tbh)

**Comment by Paris** [comment]
The problem is the official client which we instrument into uses AWT not Swing, which has limited functionality for submenus.
