### ISSUE TITLE
offset paint glass pane if advertisement is visible.

### ISSUE THREAD

**Issue by MaartenBoodts** [powerbot/powerbot#1449]
This happens when there's an advert showing above the game.

![](https://i.gyazo.com/fd4fcfddac06539568a920630f718483.png)
![](https://i.gyazo.com/a91f051e64cb188dd40221524e34f473.png)

**Comment by ArtificialPB** [comment]
It looks like that the paint gets offset by game screen location, but the panel it's painted on stays in the same place, that's why it's cut of at the bottom.

**Comment by rs-sliske** [comment]
think this is now irrelevant

http://services.runescape.com/m=news/in-other-news?oldschool=1
!(https://sliske.uk/img/captures/08e9ecd11eb7363.png)

http://services.runescape.com/m=news/gower-quest--get-ready-for-telos?jptg=ia&jptv=news_list
!(https://sliske.uk/img/captures/ded05c80b6e6149.png)

**Comment by ArtificialPB** [comment]
I believe this can be closed now.
