### ISSUE TITLE
SDN not updating

### ISSUE THREAD

**Issue by k0na** [powerbot/powerbot#1457]
#1454 was marked as resolved by @ArtificialPB but the SDN still doesn't seem to update for me.

**Comment by ArtificialPB** [comment]
It's broken again for me as well.

**Comment by k0na** [comment]
12 days and counting...

**Comment by Paris** [comment]
Should be fixed now but I'll leave this open just in case, please report back.

**Comment by k0na** [comment]
I received a notification saying my scripts were rebuilt so it appears to be working again.

**Comment by stumpy3toes** [comment]
Got a rebuilt notification too
