### ISSUE TITLE
SDN does not seem to be updating again

### ISSUE THREAD

**Issue by stumpy3toes** [powerbot/powerbot#1458]

**Comment by ArtificialPB** [comment]
Can confirm

**Comment by Paris** [comment]
The SDN doesn't send notifications anymore but it continues to build, can you check by looking at your compiler log?

**Comment by Moosheplusplus** [comment]
@Paris Already checked, I have 3 commits pending to be compiled. One script was added and has yet to be compiled

**Comment by Paris** [comment]
I've triggered a complete rebuild but I'll look into this properly @Moosheplusplus and update this issue with developments.

**Comment by ArtificialPB** [comment]
@Paris After you triggered the rebuild, there are some issues with pushing to the SDN. It always returns error 403 unable to access.

**Comment by Moosheplusplus** [comment]
@ArtificialPB I'm not having an issue. Are you sure it wasn't just fail2ban?

**Comment by ArtificialPB** [comment]
Found the issue, had to change git username to my forum display name.

**Comment by k0na** [comment]
Still broken.

**Comment by k0na** [comment]
Could you please look into this @Paris? It's been 9 days, again...

**Comment by Paris** [comment]
I finally found the cause of the problem and this has been fixed *properly*. Again I will leave this issue open for the next few days just to verify with you guys everything is working as expected.

**Comment by ArtificialPB** [comment]
@Paris It only updated once today. I've pushed an changes today and I'm now waiting for almost an hour and it still hasn't updated. Can you please solve this as soon as possible? I have some compilation issues and all my scripts are gone from the SDN.

**Comment by Paris** [comment]
@ArtificialPB your latest push has compile errors, please check your log.

**Comment by stumpy3toes** [comment]
Waited over an hour/2 hours and pushed twice but it's not updating

**Comment by ArtificialPB** [comment]
@Paris can you please manually trigger SDN to update? I've got some critical bug fixes waiting to get live.

**Comment by Moosheplusplus** [comment]
@Paris could you trigger another manual update? I have a new script pending to be added to the SDN.

**Comment by k0na** [comment]
Could this be fixed @Paris?

**Comment by Strikegently** [comment]
@ArtificialPB @k0na @Moosheplusplus 
The SDN says it's building - you just don't get notifications for it any more (broke with IPB4).
I checked your logs, and all of your repos were rebuilt yesterday and the day before and all of your scripts are listed.

https://powerbot.org/store/orders
