### ISSUE TITLE
[rt4] Holding down a key

### ISSUE THREAD

**Issue by stumpy3toes** [powerbot/powerbot#1463]
I'm not 100% sure if this an issue with RSBot but it would appear to be. So for holding down keys by doing `ctx.input.send("{VK_LEFT down}"); Condition.sleep(5000); ctx.input.send("{VK_LEFT up}");` works for rotating the camera but if I did it for VK_BACK_SPACE that would not delete all the characters in the chat box for example. I posted a thread about this on the forums thinking that I was doing something wrong but no one has offered a working solution so I'm guessing this maybe a bug, here's a quote from that thread where I explain it in a little more detail: 

> Okay so it seems to work with holding down an arrow key to rotate the camera but not anything else. For instance if I want to hold space rather than click continue each time through a chat dialogue it will work once then stop skipping through the dialogue, as if the key has been pressed and not held. Same problem for typing in the public chat as well as the input box (the one that appears with things like Withdraw-X). In most cases with the public chat and the input box it won't even input the character once, so for instance if I want it to hold down '1', no '1's will appear at all in the chat/input box.

Not sure if this is a problem in RT6 as well

**Comment by Timer** [comment]
Your keyboard simulates holding the backspace as tons of presses iirc -- you have to send them individually.

**Comment by stumpy3toes** [comment]
Yeah just researched after reading your response and it appears to be a feature of the hardware. Thanks for the reply
