### ISSUE TITLE
Developers/staff page not accessible

### ISSUE THREAD

**Issue by k0na** [powerbot/powerbot#1470]
"Something went wrong :/"

**Comment by Moosheplusplus** [comment]
You can view the compilation log [here](https://www.powerbot.org/store/orders/).

**Comment by k0na** [comment]
Any word on this @Paris?

**Comment by Paris** [comment]
@Moosheplusplus is correct, the additional information will be moved there along with the script stats and sales snapshot.

**Comment by k0na** [comment]
@Paris, closing this before it's resolved seems like a bad idea

**Comment by k0na** [comment]
@Paris if the sales log could be made accessible again that'd be great
