### ISSUE TITLE
RuneScape Client frame centers itself on script start/stop

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1471]
Not OS-specific; occurs on both Windows 10 and Ubuntu 16.04. [More information here](http://www.powerbot.org/community/topic/1316771-client-moving/).

**Comment by k0na** [comment]
Same on Windows 7

**Comment by ArtificialPB** [comment]
Also happens when selecting user Input allowance

**Comment by Strikegently** [comment]
It collapses the client window, messing up the UI and potentially causing issues for scripts.

**Comment by Strikegently** [comment]
Forgot to mention: this was fixed in 7040.
