### ISSUE TITLE
Have the SDN randomize order of scripts client-sided

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1474]
The SDN currently randomizes the order of scripts server-sided, meaning the result is cached by the client, and is unlikely to change until the cache expires. If the SDN were to randomize them client-sided, that means each time a user goes to the scripts page, they will have a new order of scripts.

Currently, a user is less likely to use a script if it's at the bottom of the page. By randomizing it each time, it gives a fair shot for every script.

**Comment by k0na** [comment]
I don't think this is a good idea.

It will get very confusing for the user if the position of their scripts change every single time they want to run one, especially if they have added more than what the scrollpane initially allows them to see.

**Comment by Moosheplusplus** [comment]
@k0na why would you have to open up http://powerbot.org/scripts/ in order to run a script every time

**Comment by k0na** [comment]
@Moosheplusplus don't you also do that

**Comment by Moosheplusplus** [comment]
@k0na no? I'm talking about the script page, not the RSBot script selection window. RSBot already sorts the scripts alphabetically.

**Comment by Paris** [comment]
The sorting is still done server side but now happens more frequently and the order is random with a preference for scripts that have been most recently updated.
