### ISSUE TITLE
Unable to sign in to RSBot

### ISSUE THREAD

**Issue by PorkScripts** [powerbot/powerbot#1475]
When going to Script > Play and having to sign in, entering a valid powerbot username and password does not work. The text fields are cleared and nothing happens. This started occurring in version 7031.

**Comment by Moosheplusplus** [comment]
Press Get PIN and copy+paste the pin where the password field is.

**Comment by PorkScripts** [comment]
I've done that and it does the exact same thing. I've deleted my browser history on every browser I have installed. I've deleted my temp folder and RSBot folder in AppData.

**Comment by PorkScripts** [comment]
Update: This issue appears to be caused when the account has no scripts added to their collection. I simply added a script at http://www.powerbot.org/scripts/ and can now login to the client.

**Comment by ChrisBPB** [comment]
this was fixed afaik
