### ISSUE TITLE
Combat broke 

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1481]
java.lang.RuntimeException: Config missing for org/powerbot/bot/rt4/client/LinkedListNode.getNext 
	org.powerbot.bot.Con.break(ik:168)
	org.powerbot.bot.Con.break(ik:163)
	org.powerbot.bot.Con.break(ik:46)
	org.powerbot.bot.rt4.client.LinkedListNode.getNext(jg:184)
	org.powerbot.script.rt4.Actor.break(kc:342)
	org.powerbot.script.rt4.Actor.break(kc:293)
	org.powerbot.script.rt4.Actor.inCombat(kc:227)
	e.a(e.java:82)
	e.accept(e.java:79)
	org.powerbot.script.AbstractQuery.select(jb:187)
	bb.c(bb.java:79)
	bb.a(bb.java:23)
	hb.poll(hb.java:127)
	org.powerbot.script.PollingScript$6.run(ci:255)

java.lang.NullPointerException 
	hb.run(hb.java:207)

**Comment by Moosheplusplus** [comment]
This is preventing any interaction with NPCs. NPC query selection still works, though.

**Comment by FazzyLlogic** [comment]
when the broked can be finish?.

**Comment by widget-** [comment]
I'm having the same issue. I don't know how common it is so it if helps reproducibility I'm on the 64-bit Java 8 u73.

**Comment by Timer** [comment]
Resolved in 028b8eac5dbc38be8e60b6c3cbf5125eaac4a6cd
