### ISSUE TITLE
RT4 Magic Broken (?)

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1485]
java.lang.ArrayIndexOutOfBoundsException: -1
 org.powerbot.script.rt4.Component.null(od:529)
 org.powerbot.script.rt4.Component.borderThickness(od:223)
 org.powerbot.script.rt4.Magic.spell(d:127)
 zy.b(zy.java:29)
 o1.poll(o1.java:121)
 org.powerbot.script.PollingScript$6.run(le:348)

@Moosheplusplus

**Comment by Timer** [comment]
Resolved in 42ab72dcd8f1a11740f26712d4593da082a1789d
