### ISSUE TITLE
Client side world select

### ISSUE THREAD

**Issue by woodcutterguyman** [powerbot/powerbot#1486]
I was wondering/requesting that you implement a "world number select" option to the client. You could possibly put it in the same place where you also select which account/script you are going to use. I would find this very helpful because the client continues to log me onto one specific world every time and when i have multiple running they will all log onto this world. Plus, the ping on that world is terrible for my connection and i always have to end up hopping worlds anyway. I could individually sign on to each account and select the world i want to go to but i have long emails/passwords which become repetitive and annoying to type in over and over again.

**Comment by Moosheplusplus** [comment]
That's the nature of the Runescape client itself. If you want to specify a specific world on startup, add this to your VM arguments:
`-Dcom.jagex.config=http://world20.runescape.com/l=en/jav_config.ws`

Or if you're using OSRS:
`-Dcom.jagex.config=http://oldschool6.runescape.com/l=en/jav_config.ws`

change the number after "world" or "oldschool" to the world you'd like to join.

**Comment by Paris** [comment]
Closing as per @Moosheplusplus's comments.
