### ISSUE TITLE
Statistics still broken

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1487]
@Paris How am I supposed to get my script premium if statistics remain broken

here's my statistics tracker
![](https://i.imgur.com/f7ftsGM.png)

here's yours:
![](https://i.imgur.com/IuADpPV.png)

I'm still getting requests for help on threads which scripts are supposedly dead, so obviously *someone* is running my scripts

**Comment by Paris** [comment]
I've been making some tweaks to this, please let me know if the numbers look better to you now.

**Comment by ChrisBPB** [comment]
I thought they were removed, where do you see stats?

**Comment by ArtificialPB** [comment]
At http://www.powerbot.org/client/ select "Scripts" @ChrisBPB 

As of yesterday, statistics only show stats for 2 out of 7 scripts on the SDN. All scripts are working.

**Comment by ChrisBPB** [comment]
mm I have no scripts button

**Comment by Moosheplusplus** [comment]
@ChrisBPB Go into the forums, click Orders. Should look like this:

![](https://i.imgur.com/NQElV5q.png)

**Comment by ChrisBPB** [comment]
nah I don't have any tabs

**Comment by Paris** [comment]
This has been fixed in the next version.
