### ISSUE TITLE
Warn users to restart bot after an update

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1490]
Following an update a good amount of users say scripts are broken because they won't do something (usually eat/walk/open bank .. stuff like that) but they have to restart their PC

It's been an issue for a while, I reported it in February but it was closed. No exception is thrown or anything.

Might be OSRS only but can't confirm

**Comment by Paris** [comment]
Is this for a game update or Java update?

**Comment by ChrisBPB** [comment]
after a game update

**Comment by Paris** [comment]
Is this something from the game client itself that requires a restart?

**Comment by ChrisBPB** [comment]
no just view->objects sometimes doesnt work unless you restart pc after update, maybe npcs etc too but havent tried

**Comment by ChrisBPB** [comment]
restarting rsbot not entire pc seems to fix it

so first launch after update
http://i.imgur.com/cyklOv4.png

after restart
http://i.imgur.com/eU6xg05.png

**Comment by Paris** [comment]
Fixed for next version.
