### ISSUE TITLE
Script statistics show for only a couple of scripts

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1498]
Statistics is available for only 2 out of 8 uploaded scripts:
![statistics](https://cloud.githubusercontent.com/assets/4672155/18230422/2f7c0e78-729b-11e6-86fa-0c6f6ac5ef58.png)

**Comment by Paris** [comment]
There was a bug up until the last RSBot release so stats will start correcting themselves as people update and use the scripts on the new version.

**Comment by ArtificialPB** [comment]
Okay, thanks for clarifying.
