### ISSUE TITLE
Can't interact with items in inventory

### ISSUE THREAD

**Issue by dayjaby** [powerbot/powerbot#1508]
ctx.backpack.itemAt(i).click() doesn't click on the item anymore.
However ctx.widgets.component(1473,7).component(i).click() seems to work.
Looks like [Constants.BACKPACK_CONTAINER](https://github.com/powerbot/powerbot/blob/fb1527bb101fa42723582b3bd534ff34417a9fcd/src/org/powerbot/script/rt6/Constants.java#L190) needs to be updated to = 7.

Or am I using a wrong kind of interface? I am using the layout 'Classic'.

**Comment by Timer** [comment]
This, indeed, would be a bug. We'll look into it.
Does this snippet of code do anything?
`ctx.backpack.select().shuffle().poll().interact("Examine")`

**Comment by ChrisBPB** [comment]
nope does not do anything
