### ISSUE TITLE
Mouse event listeners not working

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1518]
Implementing MouseListener/MouseMotionListener/MouseInputListener doesn't listen to any mouse events. Adding it to ctx.dispatcher does not work either. PaintListener and others work fine. Even if the mouse listener is implemented in the same class as the paint, only the paint works.

**Comment by ArtificialPB** [comment]
This only happens if you add more than one mouse listener to the dispatcher. The listener that was added first works.

**Comment by Timer** [comment]
Fixed
