### ISSUE TITLE
Remove the "Install 32-bit java" message

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1520]
This message is unnecessary as it doesn't fix anything (and may cause memory problems in using it). Even if the user installs 32-bit java, this message will still display since the 32-bit version is not set as default on most machines.

The message itself can be closed and RSBot will work fine without it. Not only this, but it doesn't show up on certain machines with 64-bit java, anyway.

**Comment by Moosheplusplus** [comment]
Here's an [example](https://www.powerbot.org/community/topic/1323342-) of someone having an issue with this message.

**Comment by Paris** [comment]
Fixed for next version.
