### ISSUE TITLE
[rt4] Inventory#selectedItem always returning a nil item

### ISSUE THREAD

**Issue by stumpy3toes** [powerbot/powerbot#1532]
It appears Inventory#selectionType is always returning 0

**Comment by dayjaby** [comment]
And Inventory#selectedItem().id() always returns -1

**Comment by Moosheplusplus** [comment]
The issue is with `org.powerbot.bot.rt4.client.Client#getSelectionType()` and `getSelectionIndex()`.

**Comment by Moosheplusplus** [comment]
by the way, this was fixed a while back and can be closed. @Timer @Strikegently @Paris
