### ISSUE TITLE
OSRS inventory item components returning nil

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1534]
if I were to get an item from `Inventory#select()`, its component will be nil. Not sure if related to #1532.

**Comment by Timer** [comment]
What do you mean?

**Comment by Moosheplusplus** [comment]
@Timer if you were to grab any of the items in the inventory, the component returned via `Item#component()` is nil.

For example:
```java
ctx.inventory.select().peek().component(); // invalid/nil component
```

**Comment by ArtificialPB** [comment]
Tested and it works correctly, it doesn't return nil component if item is valid. Does this happen with any specific interface @Moosheplusplus ?

**Comment by Moosheplusplus** [comment]
oh @ArtificialPB you're right. I forgot that OSRS stored the IDs of all of the items in one component.
