### ISSUE TITLE
Component location and visability/validity hooks broken

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1544]
This happens in rt6 and it started happening after one of the recent game updates:

![component issue](https://cloud.githubusercontent.com/assets/4672155/20845597/20c77ae0-b8c6-11e6-9a5d-c9f296c50632.png)

**Comment by Timer** [comment]
Broken hook!

**Comment by PorkScripts** [comment]
Is it just due to updated components?

For example: When in game, the recent chat box messages are in widget 137, component 133. My RSBot client is reporting the absolute coordinates of this component at (2, 25) which are wrong.
The correct coordinates can be found by finding the chat box container in widget 1477, component 102. Its absolute coordinates are (4, 434). Add these to the incorrect coordinates above (2, 25) and you get (6, 459) which should be correct.

So is RSBot depending on widget 1477 for offsetting other widgets? And maybe the components in 1477 were updated from a game update, screwing up offsets of certain interfaces?

Also, another issue I've found it the options menu (widget 1433) is showing visible as "true" even after closing it.

Pls fix thx

**Comment by ArtificialPB** [comment]
In addition to location offset, some widgets and components are always valid/visible, even when closed. One of those interfaces for example is Options Menu:
![componentissue2](https://cloud.githubusercontent.com/assets/4672155/21179417/42f6186a-c1f4-11e6-9c62-bab32f5cdac2.png)

**Comment by scriptnoob2000** [comment]
Any ideas when this will be fixed? I'm also experiencing this issue and it blocks me from continuing work on my artisan blacksmithing script since all mini game components are also broken with the same issues 1) Always visible 2) Position on screen is reported wrongly.

**Comment by ArtificialPB** [comment]
Please make this a high-priority fix. A lot of RS3 script are at least partially broken due to broken hook.

**Comment by Timer** [comment]
d35f5564e568cfe885cf7fbf96efcf0972128f59

**Comment by ArtificialPB** [comment]
Still happens, including with always returning valid/visible for some components. 
<img width="609" alt="screen shot 2016-12-24 at 18 28 21" src="https://cloud.githubusercontent.com/assets/4672155/21468181/dd49582c-ca06-11e6-8544-1e9dde2d7aeb.png">

**Comment by k0na** [comment]
This is still broken @Timer

**Comment by Strikegently** [comment]
Hud doesn't work at all. Widgets return valid and visible even when closed. 
My scripts are almost entirely non-functional.

**Comment by k0na** [comment]
@Timer @Diana-Dionisio when will this be addressed

**Comment by ArtificialPB** [comment]
This is getting ridiculous. It's been over a month now with no real progress on this. I understand that you are busy @Timer, but what I don't get is why powerbot does not get another developer in this case to fix at least critical issues like this one? If money for hiring a dev is an issue I'm sure there are script writers/scholars on the forums who are qualified and willing to help for free, at least with the open source API. And since that part of the API is public there's even no need to have them sign an NDA, you just give them a right to merge into the repository.

And @Diana-Dionisio, as far as I know you had some issues with setting up RSbot for testing. If you still have them feel free to contact me on Slack or powerbot forums and I'll gladly help you set it up.

**Comment by utahclock** [comment]
Any update on a fix for this?

**Comment by Strikegently** [comment]
Two months.

**Comment by Moosheplusplus** [comment]
can we just automatically assign all issues to the "next" ~graveyard~ milestone

**Comment by k0na** [comment]
It's been three months in two days. Come on...

**Comment by Strikegently** [comment]
3 months 2 days.

**Comment by Strikegently** [comment]
4 months.

**Comment by PorkScripts** [comment]
Pretty ridiculous that this is still broken... I'm assuming all you need to do is fix the hook that tells which component some widgets are contained inside.

In the meantime: if anyone needs this working, and you have a component that is showing incorrectly in the top-left corner, or is showing as visible when not, find the container component in (usually in widget 1477) and use that when testing visibility and use its x and y position to offset the incorrect x and y of your component.

**Comment by k0na** [comment]
Any word on a full fix for this?

**Comment by Strikegently** [comment]
0ef9eff
