### ISSUE TITLE
Request for Property to manually override SDN icon

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1546]
I'd like to request a property in the Script Manifest to override the icon which shows beside the SDN entry, for example:

```java
properties = "vip=true; author=Mooshe; topic=1323884; icon=" + Constants.SKILLS_CRAFTING
```

would show up as:
![](https://i.imgur.com/El6qpNz.png)

**Comment by Paris** [comment]
This has been implemented, you can now set a custom `category` property with any of the string names available in the [CSS file](https://cdn.powerbot.org/assets/css/icon-scripts.css).

**Comment by Moosheplusplus** [comment]
awesome, thanks.
