### ISSUE TITLE
rt4 bank pin not being entered

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1549]
I don't have one to test.

**Comment by Moosheplusplus** [comment]
if you give me 14 days to request a PIN I can test this for you ![](https://res.cloudinary.com/urbandictionary/image/upload/a_exif,c_fit,h_32,w_32/v1395991705/gjn81wvxqsq6yzcwubok.png)

**Comment by Moosheplusplus** [comment]
oh ok this was never fixed

Timer used `Integer.toString()` rather than `Character.toString()` to get the character value, so the character was being implicitly casted to an integer.

reverted it in #1574

**Comment by Moosheplusplus** [comment]
@Strikegently this was fixed in #1574 and can be closed.
