### ISSUE TITLE
rt4 menu action misclicking

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1556]
I've noticed that when trying to interact with certain NPCs (via `npc.interact(action, npcName)`), it will sometimes misclick the menu action. I've noticed this often with `ctx.bank.open()`, enough for me to write my own banking API, but my API does this as well.

I've tested it a bit, and it seems that it's not an issue with the bounds (see below):
![](https://i.imgur.com/TW17wqZ.png)

I'm not entirely sure what could be causing this.

**Comment by ArtificialPB** [comment]
Most likely related to https://github.com/powerbot/powerbot/issues/1032.
