### ISSUE TITLE
remove PIN system

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1576]
too many people don't understand it, and it is failing to work for many people for all different reasons - antivirus being a big reason, and often adware (usually premieropnion) causing an issue

the past month or more though a lot of people have simply been unable to log in, I have teamviewed multiple and can't find anything wrong and they aren't on VPNs or anything either

the system is complicated and doesn't work effectively, if there is no way to use passwords (although I imagine if pins aren't working passwords won't either in this case) and block attempts after X tries then perhaps look at a 'sign in' button which will launch a browser tab which somehow versifies the user and logs them in, kind of like the RuneScape sign up process where you enter your email and when you validate it automatically continues.

**Comment by Moosheplusplus** [comment]
I think it should be replaced with optional TOTP Authentication, which people are more familiar with.

**Comment by k0na** [comment]
TOTOP could work but in my opinion it's a bit of an unnecessary over-complication. What was wrong with forum username/password in the first place?

**Comment by Moosheplusplus** [comment]
@k0na it should be optional for users, and required for script writers and staff members.

**Comment by Strikegently** [comment]
We have TOTP as part of the 2FA system we enabled a little while ago. We could maybe use that.

**Comment by Paris** [comment]
TOTP would not work for the same reasons the current PIN doesn't. So I'll need to evaluate this.

We disallowed password based login due to brute-force hacking attempts, but I may re-enable this with some security to prevent that in the next version.

**Comment by Moosheplusplus** [comment]
@Paris Are you using IPBoard's API for user authentication, rather than directly querying the database? IPBoard has implemented security to prevent brute force attacks

**Comment by Paris** [comment]
We do use their internal code and APIs.

**Comment by Paris** [comment]
A setting has been changed server side so the bot now accepts regular passwords for bot login. The next RSBot version will use different wording on the GUI to make it clear that PIN codes or passwords may be used to authenticate.
