### ISSUE TITLE
Request to Deobfuscate Script Stacktraces from Client Page

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1577]
If a user reports a log with a stacktrace in it, it's sometimes impossible to guess what has caused it (because both the names and lines are obfuscated), or whether or not it was thrown by RSBot or the script.

I think it would be a good developer tool to add a stacktrace deobfuscator to the client page.

**Comment by Paris** [comment]
From the next version all stacktraces will show file names and line numbers.
