### ISSUE TITLE
Projectiles OSRS

### ISSUE THREAD

**Issue by k0na** [powerbot/powerbot#1578]
Although there are more pressing issues at the moment, support for projectiles in OSRS would be much appreciated

**Comment by ccarpenter04** [comment]
I support this too but I'm interested in what you plan on using them for detecting and such?

**Comment by Moosheplusplus** [comment]
projectiles are just objects if I remember correctly.

**Comment by iDznPB** [comment]
+1 for this. From what I can see so far projectiles all return 65535.
