### ISSUE TITLE
Fatal Error: Unable to find package java.lang in classpath or bootclasspath

### ISSUE THREAD

**Issue by LukasBraun1** [powerbot/powerbot#1581]
When running the ./make.sh file, I get the error "Fatal Error: Unable to find package java.lang in classpath or bootclasspath"
I can't find anything online about this issue so I think it could be a problem with the script itself

**Comment by rs-sliske** [comment]
you arent meant to be able to run it

it depends on a lot of other classes which are not part of the public repo

**Comment by LukasBraun1** [comment]
If you got all of these other classes would you be able to run it?

**Comment by Moosheplusplus** [comment]
yes, but you can't get all of the other classes, it's proprietary.
