### ISSUE TITLE
RS3 and OSRS issues with scripts

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1586]
```
java.lang.NoClassDefFoundError: ync 
    org.powerbot.bot.aUx.loadClass(th:188)
    z.auX.char(gj:281)
    z.coM8.run(pm:410)
```

**Comment by ChrisBPB** [comment]
latest update
1422 java.lang.OutOfMemoryError: Java heap space 
    z.D.char(fg:208)
    z.D.<init>(fg:107)
    z.ub.char(kn:91)
    org.powerbot.script.rt4.CacheNpcConfig.char(bc:197)
    org.powerbot.script.rt4.Npc.actions(rb:172)
    org.powerbot.script.Actionable$Matcher.accept(f:106)
    org.powerbot.script.Actionable$Matcher.accept(f:132)
    org.powerbot.script.AbstractQuery.select(ma:88)
    org.powerbot.script.rt4.BasicQuery.action(gc:23)
    org.powerbot.bot.rt4.nuL.char(ah:121)
    org.powerbot.bot.rt4.nuL.poll(ah:140)
    org.powerbot.script.PollingScript$6.run(ng:73)
1422 java.lang.OutOfMemoryError: Java heap space 
    z.D.char(fg:208)
    z.D.<init>(fg:107)
    z.ub.char(kn:91)
    org.powerbot.script.rt4.CacheNpcConfig.char(bc:197)
    org.powerbot.script.rt4.Npc.name(rb:181)
    ae.d(ae.java:1881)

**Comment by Strikegently** [comment]
Is this still an issue?

**Comment by ChrisBPB** [comment]
hasn't been reported recently

**Comment by ArtificialPB** [comment]
Some of my users reported the NoClassDefFoundError recently. It's possible it affects just the users of my scripts due to https://github.com/powerbot/powerbot/issues/1588.

**Comment by ArtificialPB** [comment]
```
java.lang.NoClassDefFoundError: rhb 
    org.powerbot.bot.Aux.run(td:160)
```

**Comment by ArtificialPB** [comment]
Another _NoClassDefFoundError_, this time with a rt6 script. Like I said, it might only affect my scripts due to the script downloading issue.
```
java.lang.NoClassDefFoundError: tdc 
    org.powerbot.bot.aUx.loadClass(in:176)
    z.coN.if(ag:499)
    z.com7.run(jm:262) 
```

**Comment by ChrisBPB** [comment]
related?
2018 java.lang.NoClassDefFoundError: zb 
    wb.h(wb.java:214)
    wb.<init>(wb.java:42)
    ti.a(ti.java:39)
    si.start(si.java:68)
    org.powerbot.script.PollingScript$2.run(lk:65)

**Comment by ArtificialPB** [comment]
```
 java.lang.NoClassDefFoundError: y/rhb 
    org.powerbot.bot.COn.run(ScriptController.java:151) 
```

**Comment by ChrisBPB** [comment]
444 java.lang.NoClassDefFoundError: rhb 
    org.powerbot.bot.COn.run(ScriptController.java:151)

**Comment by ArtificialPB** [comment]
RS3 stacktrace
```
java.lang.NoClassDefFoundError: tdc 
	org.powerbot.bot.nUL.loadClass(ScriptClassLoader.java:75)
	z.Prn.void(ScriptList.java:254)
	z.cOm9.run(BotPreferences.java:388)
```

**Comment by ArtificialPB** [comment]
This is still a major issue with my scripts.
