### ISSUE TITLE
Make Powerbot Great Again

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1590]
Please provide write access to someone who's active in this repository. There are plenty of blatantly ignored issues and pull requests which should have been addressed a long time ago.
 [#MakePowerbotGreatAgain](https://github.com/powerbot/powerbot/issues?utf8=%E2%9C%93&q=%23MakePowerbotGreatAgain)

**Comment by ChrisBPB** [comment]
It is something we are working on, we have some things in mind that need looking over and putting into effect. If you have any specific suggestions you can email them to myself or @Paris. The main priority right now is getting RS3 back online which should be sorted this week as mentioned on the forums. Following that we hope we can start moving at a much faster pace and including/utilising our active script writers as developers.

**Comment by Moosheplusplus** [comment]
@ChrisBPB I don't think it has to be a case of "one or the other", just expand the team to get these issues addressed. At the time, @Timer is MIA, I don't know whether or not Diana is contributing, and @Paris is stretched thin.

There are plenty of capable developers which can help out, such as @ArtificialPB and I, and there are a few other developers which show interest in contributing such as @rs-sliske, @sethrem, and @Mrfreezerburnt.

Let us help you guys out, because some of us rely on RSBot as a source of income, and the state of RSBot is directly affecting us.

**Comment by sethrem** [comment]
I completely agree with @MooshePlusPlus, I myself haven't been active recently on PowerBot because of the lack of development and digress on trying to move to another runescape bot because I've been using powerbot since day-1. We need more updates and consistent updates. There are so many members of this community whom can contribute greatly to the bot. We need to work on the bot before the community moves on, which most have.

**Comment by ChrisBPB** [comment]
This is what I meant we had plans to do, but we need to get RS3 back online before we can start putting this into effect.

**Comment by MrFreezerburnt** [comment]
I know I'm not a script writer or proficient at coding, but I don't want to see PB go down a road where it'll never recover, and with most of the main developer admins MIA, I think PB should take any help that they can get. Giving capable developers like Mooshe and Artificial write access could easily address this issue, whether it is a temporary fix or a permanent solution.
