### ISSUE TITLE
Could not download script (Not in GZIP format)

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/powerbot#1606]
I know @ArtificialPB's scripts have been getting this issue, however, now one of my scripts is getting this issue.

```
0548 Could not download script (Not in GZIP format)
0548 java.util.zip.ZipException: Not in GZIP format
 at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
 at java.util.zip.GZIPInputStream.<init>(Unknown Source)
 at java.util.zip.GZIPInputStream.<init>(Unknown Source)
 at z.coN.if(ag:226)
 at z.com7.run(jm:262)
 at java.lang.Thread.run(Unknown Source)
```

The script is Master Pyro.

**Comment by Strikegently** [comment]
Rebuild your repository.

**Comment by Paris** [comment]
I have tested your scripts [Master Miner](https://www.powerbot.org/community/topic/1310443-rs3-master-miner-free-mining-script-for-rs3/), [Master Chef](https://www.powerbot.org/community/topic/1297570-master-chef-chained-aio-cooker/) and [Master Flower](https://www.powerbot.org/community/topic/1299917-vip-master-flower-earn-~15mhr-planting-mithril-seeds33/), all work fine after a forced rebuild.
