### ISSUE TITLE
Could not download script

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1609]
Happening to some users with Nex's scripts (Master Hunter, Master Rockcrabs) - error is just 'Could not download script' nothing more.

Possibly related #1606 #1588?

**Comment by Paris** [comment]
This has been fixed live.

**Comment by ChrisBPB** [comment]
this issue has still been happening a lot with Artificials script, unsure of others. Don't think it was ever fixed, seems to just get passed around between scripts/users everytime the sdn is fully rebuilt.

**Comment by ArtificialPB** [comment]
Was just about to open a new issue. Here's the stack trace:
```
Could not download script java.lang.NumberFormatException: For input string: "W?_?8??_u?"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at z.Nul.byte(TarReader.java:68)
    at z.Nul.hasNext(TarReader.java:32)
    at org.powerbot.bot.nUL.<init>(ScriptClassLoader.java:32)
    at z.Prn.void(ScriptList.java:244)
    at z.cOm9.run(BotPreferences.java:388)
    at java.lang.Thread.run(Unknown Source) 
```

**Comment by ChrisBPB** [comment]
I believe some people literally just get "Could not download script" but I could be wrong? @ArtificialPB

**Comment by ArtificialPB** [comment]
I only got this stack trace when I ran the client through an IDE @ChrisBPB.

**Comment by MrFreezerburnt** [comment]
Any update on this? @Paris @Timer @Strikegently

**Comment by ArtificialPB** [comment]
Still a major issue with my scripts.

**Comment by ElZaiat** [comment]
I have the same issue with one of my scripts I recently updated (zGoldFarmer)
