### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by pulkitsharma** [powerbot/powerbot#1627]
How to compile the project? There are multiple java files not present in the codebase.

**Comment by ArtificialPB** [comment]
@pulkitsharma You can't because a part of the API is closed-source.

**Comment by pulkitsharma** [comment]
@ArtificialPB Then whats the use of this repository?

**Comment by ArtificialPB** [comment]
For issue tracking and contributing to the open-sourced part of the API @pulkitsharma .

**Comment by SamyCoenen** [comment]
why is there a make.sh file then? I was trying to compile this thing for some time .
