### ISSUE TITLE
inventory.selectedItem(), .selectedItemIndex(), and .selectionType() broken for OSRS

### ISSUE THREAD

**Issue by MrFreezerburnt** [powerbot/powerbot#1638]
Keeps returning -1 for index and 0 for type regardless of item being selected. I tried using ctx.client() and ran into the same problem. In one instance it would pull an id of 1520 (which I'm sure doesn't exist for an item) but I have not been able to reproduce this.

**Comment by ChrisBPB** [comment]
seems to all come back to https://github.com/powerbot/powerbot/blob/6abebd606a5e73a2ce8778ede5605848fab9713c/src/main/java/org/powerbot/bot/rt4/client/Client.java#L361

**Comment by ChrisBPB** [comment]
Fixed. Please confirm though.

**Comment by MrFreezerburnt** [comment]
`Selection type: 1
Selection index: 1
Selected item name: Mithril bar`

Looks good, thanks for the quick fix guys
