### ISSUE TITLE
Objects NPE rt4

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1640]
Looks like it passes a null ReflectProxy object instance for some reason when initializing BasicObject on [this line](https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/rt4/Objects.java#L78).
```
 java.lang.NullPointerException
    org.powerbot.script.rt4.Objects.get(Objects.java:79)
    org.powerbot.script.rt4.Objects.get(Objects.java:35)
    org.powerbot.script.rt4.Objects.select(Objects.java:22)
```

**Comment by Kyle628** [comment]
Where is a ReflectProxy?

I see:

    import org.powerbot.bot.ReflectProxy;

In BasicObject.java but I can't actually find that class in powerbot/src/main/java/org/powerbot/bot/

**Comment by ArtificialPB** [comment]
It's obfuscated when the client is built. You can't find it here because it's not open-sourced @Kyle628

**Comment by Kyle628** [comment]
It would be nice to see what is happening in this isNull() function on line 79

    if (!o.object.isNull()) {

**Comment by Kyle628** [comment]
How did you create the error? I want to try changing it to:

    if (o.object != null) {

**Comment by ArtificialPB** [comment]
Only people with access to the full code should change this kind of things, because otherwise you can't know how the internals work and could break things further @Kyle628

**Comment by ChrisBPB** [comment]
this does not occur anymore
