### ISSUE TITLE
Switch back to inventory tab if item is used and it's not open

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1645]
Until one of the past 2 updates people, my self included, have been doing things like checking exp for skills as a minor form of antipattern. The problem is now it very often gets stuck on the tab, usage such as

switch
move mouse
sleep
switch back

Does not switch back, I don't know why. I had to resort to putting a loop after the sleep 
while(not inventory)
open inventory

Anyway, would be a much more seamless implementation if when you interact with an Item the inventory is opened for you rather than trying to click the item on the skills tab where it doesn't exist.

**Comment by MrFreezerburnt** [comment]
I have a check in all my tasks that uses `ctx.game.tab(Tab.INVENTORY)` if tab is not currently on inventory, but having this integrated would be nice. A simple if statement is all the user needs to workaround this, so I doubt it'll be implemented anytime soon.

**Comment by ChrisBPB** [comment]
going to close this because items extend interactive (as do many other things) so switching to the inventory in the method call could break other things and isn't always required (i.e when interacting with npc or something)
