### ISSUE TITLE
Quick Prayer Setup

### ISSUE THREAD

**Issue by ErrorTerm** [powerbot/powerbot#1657]
https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/rt4/Prayer.java#L75

It is failing to interact and this line (L#75) is constantly returning true.

**Comment by PhDinStupidity** [comment]
Using quickPrayer(true/false) works, so I would imagine it's a problem with the interact function.

**Comment by Kyle628** [comment]
Are you sure it isn't returning here?

    if (quickSelectionActive() == quick) {
			    return true;
		    }

If this returns, none of this would ever be evaluated

    if (quick) {
			if (!ctx.widgets.component(Constants.MOVEMENT_MAP, Constants.MOVEMENT_QUICK_PRAYER).interact("Setup Quick-prayers")) {
				return false;
			}
		}

**Comment by PhDinStupidity** [comment]
I believe I tested this and found the issue to be with interact. I will confirm once the client is running again.
