### ISSUE TITLE
Enable environment variables to automate starting a script

### ISSUE THREAD

**Issue by SamyCoenen** [powerbot/powerbot#1706]
Instead of starting the jar and then manually clicking in the GUI to start the script, input powerbot credentials and account credentials, it would be nice if this could be done with a CLI.

Passwords could be generated and encrypted in a passwd file or something to avoid password in the cli history?

**Comment by Paris** [comment]
You can currently use the VM arguments `-Dbot.login.user=<username>` and `-Dbot.login.pass=<password>` to automatically sign in. An option for starting a script will be developed, but for VIP+ users only.

**Comment by SamyCoenen** [comment]
Thanks for the information, that will certainly save some time.
