### ISSUE TITLE
When moving the client window, the screen becomes white

### ISSUE THREAD

**Issue by SamyCoenen** [powerbot/powerbot#1710]
The error message is
```
  [SEVERE] java.lang.IllegalStateException: Buffers have not been created 
	z.CoM7.run(BotOverlay.java:211)
```

**Comment by SamyCoenen** [comment]
I'm able to close the overlay but then all my 2dgraphics are gone and all the powerbot visuals as well.

**Comment by SamyCoenen** [comment]
Here's a video for proof[ with a streamable link](https://streamable.com/z6gpl) I don't have to shake it this much normally.

**Comment by Strikegently** [comment]
So doesn't shake the client.

**Comment by SamyCoenen** [comment]
I'm not allowed to move the window?

**Comment by Strikegently** [comment]
If shaking the client for 30 seconds causes issues, then don't do it.

**Comment by ChrisBPB** [comment]
Looks like this was caught already in an update last year.
