### ISSUE TITLE
Cannot use powerbot when starting with world argument

### ISSUE THREAD

**Issue by turningwind** [powerbot/powerbot#1731]
As referenced in this issue #1486 it should be possible to select the world when starting with a cli.

Using the startup option `-Dcom.jagex.config=http://oldschool8.runescape.com/l=en/jav_config.ws` works as expected with world 308. The problem is that powerbot can't seem to identify the client with the changed world.

![](https://i.imgur.com/Nt59VQO.png)

**Comment by ChrisBPB** [comment]
fixed in upcoming release
