### ISSUE TITLE
[Suggestion] Passive Scripts

### ISSUE THREAD

**Issue by Spedwards** [powerbot/powerbot#1756]
I'm currently working on multiple scripts at the moment, a couple of which would be what I'd consider "passive", meaning that they don't do anything. In my case they just paint information on the screen. What I had in mind as a client feature was a way to support passive scripts to run in sync with your other scripts. For example you could have a fishing script running and some passive script displaying information on the page.

Not seeing how the client works, this should be as simple as opening a new thread, but it would be nice to have some passive scripts up either while playing legitimately or in conjunction with another script.

**Comment by Strikegently** [comment]
Won't be implemented.
