### ISSUE TITLE
6 hour relog limit

### ISSUE THREAD

**Issue by kThisIsCvpv** [powerbot/powerbot#1826]
The 6 hour relog limit does not work if the client is in resizable mode.
Handler fails to click the "Login" button but instead hovers next to the "Create Account" button.
After a couple minutes, several tabs of "Register a new account" will be open, until your system crashes.

I believe there is a widget mismatch. 
Unfortunately, I cannot verify this due to the login class being private.

**Comment by ChrisBPB** [comment]
what game might this be for

**Comment by kThisIsCvpv** [comment]
OSRS

**Comment by ChrisBPB** [comment]
thanks

**Comment by ChrisBPB** [comment]
fixed in upcoming release
