### ISSUE TITLE
Equipment Wrapping in RT4

### ISSUE THREAD

**Issue by kThisIsCvpv** [powerbot/powerbot#1845]
There is a bug with the equipment wrapping in RT4.

The two slots affected are the QUIVER and RING; If you do not have your equipment tab open, you will be unable to retrieve your currently equipped ring and quiver items. 

While the component storing these equipment data are always valid, their data is only updated when the equipment tab is opened; you are able to read from the components directly, but unless it is visible, the equipment is only accurate since the last refresh. So, if you changed your ring or quiver but have have not opened your equipment tab since the wielding, the system would not recognize the change.

The current code compensates for this mistake by referencing the player's current appearance details. However, quiver and ring do not appear in the player's appearance data, hence the current code would believe that the player has nothing equipped in these two slots, returning NIL.

**Comment by ChrisBPB** [comment]
> Unfortunately due to the game engine, this effect is unavoidable. You will have to check the validate method AND have the equipment interface open -- or simply listen for the message and one off check this on start and switching.
