### ISSUE TITLE
HintArrows not implemented

### ISSUE THREAD

**Issue by ShowtimePB** [powerbot/powerbot#1866]
It'd be nice to have HintArrows implemented. There's a class and function for them but from what i can see there's no implementation.

https://github.com/powerbot/powerbot/blob/a7a9385c9d488d79972b8f318b40decbb7566e68/src/main/java/org/powerbot/script/rt4/HintArrow.java

**Comment by ChrisBPB** [comment]
We have Target(npc), initialiser(Player), type, and tile hooked - not sure why they aren't implemented - but I don't know where an example of hint arrows is in the game to do anything for it - can you give me a hint (:
