### ISSUE TITLE
Outdated Widgets for rt6

### ISSUE THREAD

**Issue by samlol** [powerbot/powerbot#1870]
Below are some outdated widgets for rt6. I didn't check all of the widgets, just the ones which are essential.

Outdated Bank Widgets
----------------------
public static final int BANK_PRESET = 35; --> change to 36
public static final int BANK_LOAD1 = 43; --> change to 37
public static final int BANK_LOAD2 = 51; --> change to 38
public static final int BANK_WITHDRAW_MODE = 59; --> change to 64
public static final int BANK_WITHDRAW_MODE_STATE = 160; --> This is outdated.

Outdated Lobby Widgets
----------------------
public static final int LOBBY_PLAY = 140; --> change to 134
public static final int LOBBY_CURRENT_WORLD = 122; --> not sure if this is outdated but I suggest changing this to 124
public static final int LOBBY_CLOSE = 313; --> seems to be outdated
public static final int LOBBY_TABS = 104; --> change to 98

WIDGETCLOSER_ITEMS
-------------------
1253 << 16 | 176, // Squeal of Fortune window --> 1253 << 16 | 803, // Treasure Hunter Window (I'm assuming this widget will be used to close the winow)
1252 << 16 | 5, // Squeal of Fortune notification --> 1252 << 16 | 6, // Treasure Hunter Notification

Both seem to be outdated:
906 << 16 | 427, // validate email 
906 << 16 | 230, // validate email

Widget for "skip" button on validate email window = 906 << 16 | 502, // skip validate email
also might want to include skipping/bypassing the nxt download window(sometimes pops up during login). The Widget is 906 << 16 | 595,

other outdated widgets
----------------------
public static final int MOVEMENT_RUN = 47;
public static final int MOVEMENT_RUN_ENERGY = 51;
public static final int MOVEMENT_RUN_STATE = 463;
public static final int MOVEMENT_HOME_TELEPORT = 57;
public static final int MOVEMENT_COMPASS = 55;
public static final int MOVEMENT_WORLD_MAP = 43;

Side Note
-----------
The widgets for selecting a world seem to be completely broken. Here's an example of what I mean: if you look in this image (https://prnt.sc/j4y1iy) you can see component 2 corresponds to world 3 on the world list and that it is validated and is visible. In this next Image (http://prntscr.com/j4y42p), I scroll down the world list so world 3 is no longer visible yet component 2 still remains validated and visible.

**Comment by ChrisBPB** [comment]
a few you listed as incorrect were varpbits and don't seem to be incorrect, and some were pointing to the wrong index (some things have multiple) but appreciate your time on this, I can barely run rs3 without getting bsod so helped a lot

**Comment by ChrisBPB** [comment]
and I understand the issue with the world widgets but I don't know if this breaks functionality or if it's already accounted for in the code
