### ISSUE TITLE
Filter<Npc> throws exception on @Override

### ISSUE THREAD

**Issue by drusepth** [powerbot/powerbot#1880]
Versions:

<img width="591" alt="screen shot 2018-05-16 at 1 31 41 pm" src="https://user-images.githubusercontent.com/538235/40140916-bb4ebcb4-5919-11e8-8db6-99377f789c1a.png">

This code throws an exception:

```java
        Npc fishing_spot = ctx
                .npcs
                .select()
                .id(FishingIds.NET_FISHING_SPOT)
                .select(new Filter<Npc>() {
                    @Override
                    public boolean accept(Npc npc) {
                        return true;
                    }
                })
                .poll();
```

The exception is: `Error:(46, 43) java: <anonymous scripts.tasks.train.fishing.NetFishingTask$1> is not abstract and does not override abstract method test(org.powerbot.script.rt4.Npc) in java.util.function.Predicate`

Here are the imports for the file:
```java
import org.powerbot.script.Condition;
import org.powerbot.script.Filter;
import org.powerbot.script.Random;
import org.powerbot.script.Tile;
import org.powerbot.script.rt4.ClientContext;
import org.powerbot.script.rt4.Npc;
```

Here's the whole file, for reference: https://gist.github.com/drusepth/0aa5785ebdb333ee3f694a2bc25732f4

Discord thinks it might be related to https://github.com/powerbot/powerbot/commit/e79ed75af5b0e70437ae236dd284f988593ef710. [Handy reference for the line being called](https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/AbstractQuery.java#L103).

`Filter<T>` seems to work just fine with `GameObject` and `GroundItem`, but seems to fail reliably on `Npc`.

**Comment by Strikegently** [comment]
I can't reproduce this.

**Comment by Strikegently** [comment]
I was able to reproduce this by changing my project language level to Java 6. 
You're getting this error because the method `test(Npc)` is defined in the interface using the `default` keyword which was introduced in Java 8. Since the compiler does not have an instruction set for `default` when compiling with Java 6 rules, it incorrectly throws the error.

Change your language level to Java 8. Since the SDN supports it now, it shouldn't be an issue.

**Comment by drusepth** [comment]
Awesome, thanks a ton for the fix!
