### ISSUE TITLE
[OSRS] Can't cast redirected teleports using ctx.magic.cast()

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1885]
Cast checks for the action "Cast", "Reanimate" and "Resurrect", however when a teleport is redirected, the action starts with the redirected location e.g. Seers' Camelot Teleport.

**Comment by ChrisBPB** [comment]
Which game version does this affect?

**Comment by rs-sliske** [comment]
fairly sure this is osrs

dont think rs3 currently has any spells which do this

**Comment by ChrisBPB** [comment]
Is it enough to just add cmd.action.contains("Teleport") ? I don't have an account with this ability and I can't find a useful video to verify anything.

**Comment by rs-sliske** [comment]
unfortunately i dont think it will be that simple

for teleports which have multiple options (varrock, camelot and watchtower),
the destination which is set as the left click has an action of the destination name
the other destination is available via right-click and then 'cast'
![https://sliske.uk/img/captures/77ad09c7b032dc8.png](https://sliske.uk/img/captures/77ad09c7b032dc8.png)

**Comment by ChrisBPB** [comment]
so perhaps an overloaded cast method where you can specify the action

**Comment by ChrisBPB** [comment]
```
public boolean cast(final MagicSpell spell, String action) {
		if (!ctx.game.tab(Game.Tab.MAGIC)) {
			return false;
		}

		final Component c = component(spell);
		return c.visible() && c.click(cmd -> cmd.action.equals(action));
	}
```

does this work for you?

**Comment by ChrisBPB** [comment]
see PR

**Comment by ChrisBPB** [comment]
Unable to test but in my head this works. Please reopen if not.
