### ISSUE TITLE
[OSRS] Request for methods to get Item boundingRect and index, boundingRects/points for inventory slots

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1886]
Some activities are done most efficiently with a specific inventory setup which requires dragging items to specific inventory indexes.

**Comment by ChrisBPB** [comment]
Unsure of what you are asking. Items already have #boundingRect() and #inventoryIndex() methods

**Comment by ChrisBPB** [comment]
oh for the slots themselves?

**Comment by Mkerian10** [comment]
@ChrisBPB He wants the bounding rects for the inventory slots.

**Comment by ChrisBPB** [comment]
They used to be widgets but I can't find them anymore, any idea on this @Strikegently ?

**Comment by Mkerian10** [comment]
https://github.com/powerbot/powerbot/pull/1906
