### ISSUE TITLE
Minor bug: out of bounds failsafe in Calculations.nextPoint

### ISSUE THREAD

**Issue by dfreelan** [powerbot/powerbot#1889]
in org.powerbot.script.Calculations.nextPoint, which is supposed to choose a random point in a rectangle with some bias, there's a small bug in line 44.
 
`double rx = d[0] + Random.nextDouble(0d, d[2]), ry = d[1] + Random.nextDouble(0d, d[2]);`

d[2] is the width, d[0] is the x-coordinate, and d[1] is the y-coordinate. You're trying to choose a point uniformly here, however for ry you add a random number between 0 and the **width** when you should using the **height**, which is d[3].

So the proper line should read 
`double rx = d[0] + Random.nextDouble(0d, d[2]), ry = d[1] + Random.nextDouble(0d, d[3]);`

**Comment by ChrisBPB** [comment]
fixed in next released, thanks for your input!
