### ISSUE TITLE
Run until X hours/minutes

### ISSUE THREAD

**Issue by 4ss4s1n** [powerbot/powerbot#1898]
Could there be an option for run until x? It would be much better than run until 2/4/10.
And while we are at it, could it be renamed to stop after x hours/minutes.

**Comment by ChrisBPB** [comment]
They were only added to test if it would be useful to people, we can add run until X.

**Comment by ChrisBPB** [comment]
added into next version

**Comment by ChrisBPB** [comment]
(hours only), potential for minutes in the future I suppose if there is real demand for it
