### ISSUE TITLE
MenuCommands behaving erratically

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/powerbot#1903]
TheBonobo made a post on the forums about this but I wanted to make it a more formal issue.

MenuCommands currently will erratically move around, even when they aren't changing. Here's the thread in question: https://www.powerbot.org/community/topic/1345572-menucommand-unreliable/

I personally would like for them to be consistent, because it seems like a very easy way to check if I'm hovering over the desired gameobject. If there's a method like that or an easy way to create one I'd love to hear it, but right now it'll potentially mess up due to menuCommands performing erratically. 

To reproduce simply turn on menu commands in View and hover over a tree or anything, it'll flicker often.

EDIT: Literally milliseconds after posting this I thought of a method to check if I'm hovering, simply check if the point of the mouse is contained in the area of the object. But the menuCommands are still an issue.

**Comment by Mkerian10** [comment]
This issue could be related to #1032

**Comment by ChrisBPB** [comment]
Will be released in 7077, there is still some jumping but it's a lot rarer and I don't imagine it would be enough to cause harm, atleast you won't be spammed constantly now - I don't think there was a sleep on the old one either which made it a lot worse. 

Please reopen if you get any issues from this.
