### ISSUE TITLE
healthPercent() Incorrect values for large health npcs

### ISSUE THREAD

**Issue by iDznPB** [powerbot/powerbot#1918]
Health percent shows correct amount of health when the bar is not visible but as soon as it becomes visible it's no longer correct. Found this on Zulrah which has 500hp and can sometimes return 300%+ when damage has been done.

**Comment by ChrisBPB** [comment]
did you ever get around to trying the @AshGreh solution

**Comment by iDznPB** [comment]
Didn't know there was one?

**Comment by AshGreh** [comment]
@ChrisBPB it was only for debugging from what I remember. I'm quite close though. Will probably try getting the bar's width when I'm done with the current project at hand.

**Comment by ChrisBPB** [comment]
this will be fixed in 7082

**Comment by Mkerian10** [comment]
@ChrisBPB Was this fixed? Can this be closed?
