### ISSUE TITLE
Game update corrupts cache, breaking script functionality until client is restarted

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1919]
After a game update, the cache remains corrupt until the client is restarted once or twice (in my experience).

Although it says the cache is corrupt in the log, no one reads the log and thinks the script they're running is broken.

**Comment by ChrisBPB** [comment]
This should be changed to a pop-up in the next version if accepted

**Comment by AshGreh** [comment]
@ChrisBPB @Paris could you please keep the pop up on a different thread? It blocks the mouse from clicking, but the script still continues and hence, the virtual mouse still keeps moving. Would recommend invoking pause/stop for the script and then displaying the request if you want to continue with a single thread.

**Comment by ChrisBPB** [comment]
Will be on new thread for next release. Can't pause script from where it is called.

**Comment by ChrisBPB** [comment]
The class that handles the cache does not have client context access
