### ISSUE TITLE
Bounds

### ISSUE THREAD

**Issue by AshGreh** [powerbot/powerbot#1928]
could bounds return the object instead of void? would allow the developer to avoid caching the entity
Example: ctx.objects.select.id(objectId).poll().bounds(bounds).interact(interaction);

**Comment by Strikegently** [comment]
`ctx.objects.select().id(objectId).each(Interactive.doSetBounds(bounds)).poll().interact(interaction)`

**Comment by AshGreh** [comment]
@Strikegently each is not a satisfactory solution, I do not want to set bounds for everything in the query, only the object I want to interact with. ctx.objects.select().id(objectId).first().each(Interactive).poll() would work, but that's again a pointless loop. My intention is to only set bounds for the last entity. The Issue was prematurely ended. I want a chain of the polled entity instead of a void return on bounds.
