### ISSUE TITLE
Painting user's IP

### ISSUE THREAD

**Issue by AshGreh** [powerbot/powerbot#1935]
Could we please have a paint overlay that can show the IP being used? It would help in knowing whether proxy/vpn is not leaking. It would also be preferable that this would be toggle able from the view menu.

**Comment by Strikegently** [comment]
Why is this in the scope of RSBot? I don't see this as our responsibility.

**Comment by AshGreh** [comment]
@Strikegently It becomes hard to test IPs while using it with powerbot. This is a step towards ensuring safety to the user. Consider it a QoL update.
