### ISSUE TITLE
downloadString HTTPS problem

### ISSUE THREAD

**Issue by AshGreh** [powerbot/powerbot#1936]
downloadString is able to perfectly load from http but not from https, could you guys please provide alternatives, thanks

**Comment by rs-sliske** [comment]
this will be an issue with your ssl certificate

**Comment by AshGreh** [comment]
@rs-sliske custom method works in my own java application.

**Comment by AshGreh** [comment]
@rs-sliske oh and what's the solution?

**Comment by Paris** [comment]
What version of Java are you using @AshGreh? If SSL verification fails you can disable it with the relevant Java setting.

**Comment by AshGreh** [comment]
@tullydwyer there are few security reasons to block that if I recall correctly. They have provided an alternative to a formal GET request with the use of downloadString[](http://www.powerbot.org/rsbot/docs/org/powerbot/script/AbstractScript.html#downloadString). If you want to stick to your own code though, join the discord group and tag ShowtimeScripts. He made a NetworkUtil to enable GET and POST.

**Comment by tullydwyer** [comment]
Thanks for the info @AshGreh !

Do you have any example code on how to implement the downloadString method? This would save me and any future readers time getting it working. I do see the docs however I am not super familiar with Java and the Javadocs format. https://www.powerbot.org/rsbot/releases/docs/org/powerbot/script/AbstractScript.html

Thanks again

**Comment by rs-sliske** [comment]
for get requests you should use script#downloadString

to get "raw" http requests to work i think you need to set the connect = close property to allow it through the security policies (unless this has been tightened even more since i was active)

not the cleanest thing ive written but here is the code i had for handling http requests to my server 
![https://sliske.uk/img/captures/7a6743e07405d05.png](https://sliske.uk/img/captures/7a6743e07405d05.png)

**Comment by Mkerian10** [comment]
@tullydwyer Here's my NetworkUtils file that Ash mentioned: https://gist.github.com/Mkerian10/1985b647f1577faa6dbe8c9fd6e13d31

The problem with your original solution is you weren't disabling Keep-Alive connections.

**Comment by benpoulson** [comment]
This issue should be resolved. I was also originally unable to make https requests, but have been able to make them for a couple of months now.

If anyone has any further issues, please feel free to reopen the issue again.
