### ISSUE TITLE
Actions contains null values

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1938]
I've had a couple crashes due to accessing actions by indexes since I thought it'd be ordered how it is when you right click the item (which is not the case considering you can change or hide options via the in-game settings).

Would be nice to change the defaults to empty strings or otherwise to prevent crashes.

**Comment by ChrisBPB** [comment]
We have decided against this as this is game functionality, for null safety you should remain within our API which is null safe. If there is something I am missing here that is making our API itself not null safe then please point me to the method(s) themselves and we can perhaps implement something at API level. Reopen this if that is the case.
