### ISSUE TITLE
Add field to saved accounts read-able by scriptwriters

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#1942]
In order for SW'ers to profile and obtains stats per account rather than per user a field could be added and auto-populated on creation of game accounts, just a random string.

This would still have the potential downfall of if a user deletes their accounts file, or gets a new machine - unless the string contains a hashed version of the login name, however would not be appreciated by the end user. Something could be done I guess, i.e hash(login name+pb id+rnd) then substr it to get just half. Has the potential to not be unique but unlikely.

anyone have thoughts?

**Comment by AshGreh** [comment]
Voicing support. How do you want to recover the random? hash(enc((bts private key), pbid+loginname))

**Comment by ChrisBPB** [comment]
what do you mean by recover it?

**Comment by ChrisBPB** [comment]
it's a hidden field created when they add their RS account to the client, so it's stored on their PC

**Comment by AshGreh** [comment]
@ChrisBPB logically speaking, is there any point of including the random then?

**Comment by ChrisBPB** [comment]
It's for the peace of mind of people (end users) that don't understand it, there's no real use to it since the hash will be chopped in half.

**Comment by AshGreh** [comment]
What's the reason behind chopping the hash in half? Why not just use encrypt the pbid+login with the random and then hash the encrypted text?

**Comment by ChrisBPB** [comment]
there's no need for the full string, it just adds a possibility for it to be reversed, it's only purpose is to be unique per rs account&pb user and this will provide that

**Comment by ChrisBPB** [comment]
(and the same token will be created per account no matter what machine is used providing they use the same pb account)

**Comment by AshGreh** [comment]
what is this token you speak of? the hash?

**Comment by ChrisBPB** [comment]
half the hash, yes

but it's really not the point, the point is you will have access to a token that will identity a profile (profile being a pb users specific account rather than just a pb user)

**Comment by Mkerian10** [comment]
I'd rather have the information stored on PB's servers so that it wouldn't be affected by the user changing machines. There could also be default values that would be included in the API (default usage of functions like closing the bank would use PB's values) but also allow SWs to make their own values for their own scripts.

I think this is long overdue, should've been put in a while ago.

**Comment by ChrisBPB** [comment]
This has been submitted and should be in the next version.

**Comment by ChrisBPB** [comment]
login.account.token
