### ISSUE TITLE
Allow Polygon Bounds

### ISSUE THREAD

**Issue by AshGreh** [powerbot/powerbot#1943]
Better tools for mapping clicks and polygon bounds would be nice to have.

**Comment by ChrisBPB** [comment]
Please add more detail to your request as it is unclear what you want.

**Comment by AshGreh** [comment]
Ah, sorry. I wanted to allow the ability to add a polygon/set of polygons instead of a cuboid for well, most if not all interactable entities. Also, a tool that would allow easy working with polygons to shape bounds.

**Comment by ChrisBPB** [comment]
The issue that jumps out at me mainly would be NPC's. Given they are animated their model changes which is why we use a cube to surround them completely but also their orientation which may break bounds harsher than if they were a simple cuboid. 

We could make bounds adapt with the orientation of the entity but I'm not sure what cost that may have on resources, and it would not help still with the animation.

I imagine for game objects polygonal bounds wouldn't be an issue but could you give the use case you had in mind as in my head I picture most objects in RS to be quite cube'y in shape anyway

**Comment by AshGreh** [comment]
I agree, it would be a bit harsher. However, it would be easier to attach bounds from cache models according to another developer. We were working on attaching cache bounds/get bounds at RT, however, we had to reflect most of it for attachment/overriding a few things that wouldn't be possible on the SDN level.

In general, it would be costly, but would give refined clicks. Maybe as an optional refinement.

For example, redwood trees. Having a cuboid would make it hard to click on a few parts of the tree. Either the developer would have to provide extra spacing( induced miss clicks ) or reduce spacing ( bound limiting ). Both in general, even though work, would eventually boil down to being a pattern.

**Comment by Mkerian10** [comment]
Reading models from the cache would be nice. Would allow users to add that to their paints and also allow for more accurate clicking. I can't imagine there'd be much more complex calculations.

**Comment by AshGreh** [comment]
Found another thing today. Half of the tree is empty when you specify it with a cuboid. It's horrible in my opinion that there is a good chance that the client would click on the empty area of the tree.

**Comment by ChrisBPB** [comment]
Am looking into this just not sure of the best implementation right now so evaluating options.

**Comment by Mkerian10** [comment]
@ChrisBPB wym best implementation? Seems like just adding the model bounds to the CacheConfigs and adding the back end to get the models from the cache would be sufficient. Design is straight forward here isn't it?

**Comment by ChrisBPB** [comment]
I've never explored the cache for rt6 or for rt4, so it's unlikely we're going to get model bounds and models from the cache and scale, orientate, and animate as required.

My response was to the initial request not the subrequest of obtaining and applying models. If a simple box isn't sufficient, then I am looking to alternatives that are feasible at this time.

**Comment by benpoulson** [comment]
I'd like to look at contributing to this effort if possible? I've already built the majority of what's needed for this today.

![image](https://user-images.githubusercontent.com/1797843/50182024-1c3da580-0306-11e9-8fad-16cf6c16e67f.png)

**Comment by ChrisBPB** [comment]
sure @benpoulson I'd be happy to see your implementation

as far as I got was adding the models for rt6 but have not had time to work further on this
