### ISSUE TITLE
Query filters to accept Lists

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#1953]
Currently what I have to do to get lists working
`
private List<String> eatCommands = Arrays.asList("eat","drink");
ctx.inventory.select().action(eatCommands.toArray(new String[eatCommands.size()]))
`

What I'd like it to be
`
private List<String> eatCommands = Arrays.asList("eat","drink");
ctx.inventory.select().action(eatCommands)
`

**Comment by AshGreh** [comment]
Support.
Would recommend (String... options) instead along with calling the method actions.

**Comment by Strikegently** [comment]
>`private ArrayList<String> eatCommands = new ArrayList<>(Arrays.asList("eat","drink"));`

Why are you creating two lists?

**Comment by AshGreh** [comment]
It was an example. :c
List<String> eatCommands = Arrays.asList("eat", "drink") is the best way, everyone agrees.
Shouldn't we criticize the choice of structure instead. :s

**Comment by Mkerian10** [comment]
So if I'm not mistaken `private List<String> eatCommands = Arrays.asList("eat","drink");` isn't actually important here, just pretend that eatCommands was given as an argument to a function or is from somewhere else?

Easiest solution seems to be to just accept a Collection as a paremeter
