### ISSUE TITLE
Add a Component Query and caching

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/powerbot#1958]
Component IDs can change more often than most other things in the game.  This can ruin scripts with inactive Script Writers, or force current Script Writers to go back to old scripts and figure out the issues.

This would be solved (mostly) with a component query. This way we can base it less on IDs which can change upon any update, but on things that change far less often (for example texture IDs for the game tabs)

Another feature I'd like to suggest for this is caching the components once they've been found. A not very well thought out idea is to overload the poll() so that it accepts a String as a key to a hashmap in the Components class. We can then check if that hashmap has the key, if it does we can return the cached component, if not we can just go through the query to find it, and then store it in the cache. There may be issues with thread safety or other issues but I think caching would be vital to this query for the sake of time.

**Comment by Strikegently** [comment]
There's a ComponentQuery that does exactly this.

https://www.powerbot.org/community/topic/1201831-component-query/

**Comment by Mkerian10** [comment]
@Strikegently Would be better to be built into the API, and that doesn't cache it from what I can see

**Comment by Mkerian10** [comment]
@Strikegently I don't mean cache in that way. I mean if you use the query once, and use other queries, if you come back to this query 10 minutes later it should grab the component from the cache rather than re-search the list of components.

**Comment by Strikegently** [comment]
You need to know when a Component appears or disappears. If you returned results from a timed cache, then it would take 10 minutes for a script to react to a changing Component.

**Comment by Mkerian10** [comment]
I don't mean caching that specific component, but caching the ids required to grab it. Right now the component query can take up to 700 ms for some queries. If, when we got it the first time, we cached the widget and component IDs we could have constant time lookup while still using the query

**Comment by Strikegently** [comment]
I don't think I follow. 

But as an aside: if `ComponentQuery` is taking 700ms then you're using it wrong.
Use the `select(int)` overload to select only children of that widget - then your filters will be much faster.

**Comment by Mkerian10** [comment]
@Strikegently Regardless of the caching, ComponentQuery should be part of the default API. That way people don't have to rely on bringing in something into their own API when it should be standard. The caching can be looked at after running tests with the ComponentQuery, I remember at some point I had a query take 700 seconds, although with the overridden method maybe that cuts it down to a trivial point.
