### ISSUE TITLE
Projectile#getTarget Blocking if there's no Actor target

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/powerbot#1988]
Projectile#getTarget function blocks when the projectile has no Actor target. Whenever an NPC fires a projectile towards the ground (e.g. Zulrah cloud projectiles) it's blocking.

The code used to test: 
```javaSystem.out.println("Id: " + projectile.getId());
System.out.println("Origination: " + projectile.getStartX());
System.out.println("Y: " + projectile.getStartY());
System.out.println("Target: " + projectile.getTarget().toString());
System.out.println("After target");
```

Client outputs the 3 lines, however never outputs the target of after target lines.

I believe this is unrelated to #1987 as in that projectiles of all types don't show up. 

I couldn't think of any where else to reproduce this other than Zulrah. The hook seems improperly used, there doesn't appear to be any invisible NPCs spawned for the actor target. So to me the most obvious thing is that the Projectile hooks are unfinished. There must be a different targeting system used. In addition to that, the Projectile function as a whole is unfinished. There's no documentation, the Projectiles query has little functionality, it simply extends IdQuery.

The projectiles need to be revisited, even if there's no hooks we can get, the issue with the blocking is a critical error, documentation needs to be set, and extra functionality needs to be added to Projectiles.

**Comment by ChrisBPB** [comment]
I can't get it to 'block' but I can get it to throw an out of bounds exception

**Comment by ChrisBPB** [comment]
ps you don't need toString because it will automatically use its toString method

**Comment by Mkerian10** [comment]
Ah, that makes sense. I was running it in a different thread and I'm sure I was ignoring the exception somewhere.
