### ISSUE TITLE
[RS3] Object's names are broken

### ISSUE THREAD

**Issue by anwar6953** [powerbot/powerbot#1994]
Object queries by name are returning empty results. Example:
```java
GameObject nearestObject = ctx.objects.select().name("Portable forge").nearest().poll();
```

I can query by id, which works. If I print the name of the queried object, it returns no text.
```java
GameObject nearestObject = ctx.objects.select().id(97271).nearest().poll();
if (nearestObject.id() == -1) {
    LOG.warning("No forge nearby.");
} else if (!nearestObject.click()) {
    LOG.warning("Couldn't click on forge.");
} else {
    LOG.info("name: " + nearestObject.name());
    return true;
 }
```

The above code prints:
![image](https://user-images.githubusercontent.com/2440977/48732627-0ba9ea80-ebf5-11e8-9c38-dd8719b46ca2.png)

**Comment by anwar6953** [comment]
I restarted my bot clients and it seems to work now...

**Comment by ChrisBPB** [comment]
Corrupt cache.
