### ISSUE TITLE
Allow API to be more freely extended

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/powerbot#2002]
Currently the API doesn't allow a lot of extendability. We can extend queries but that's largely it due to stuff like `npc` having a protected constructor.

Adding functionality for overriding input as well as the actual endpoints would be nice.

An easy way to start it off would be to add a generic type to the queries and have `poll()` return this generic type. 

```
public class Npcs<N extends Npc>{

...

public N poll(){
    ...
}
```

Right now it's clunky to add extra functionality and checks to things like interact and such. There's no way to change the mouse algorithms or such.

**Comment by Mkerian10** [comment]
Any update?

**Comment by ChrisBPB** [comment]
There are plans for this, but nothing in motion.

**Comment by Mkerian10** [comment]
@ChrisBPB I could start working on this if you want. Or would you rather wait and have someone higher do it.
