### ISSUE TITLE
inViewport not registering.

### ISSUE THREAD

**Issue by Beerato** [powerbot/powerbot#2008]
I put an expression if(!fire.inViewport) { cut trees }
if(fire.inViewport) {cook}
When it lights the fire it still clicks on cut trees. I even tried adding wait condition 0.5s still did not work.

**Comment by AshGreh** [comment]
Seems more like a logic problem than inViewport problem. Could you try showing your code on discord?

**Comment by ChrisBPB** [comment]
inViewport works. If you need help pls use discord.
