### ISSUE TITLE
Make rtx

### ISSUE THREAD

**Issue by AshGreh** [powerbot/powerbot#2012]
It would be better to have a unified api for both games, maybe called rtx. This would not only bring in more developers for rs3, but also get more scripts on both the game versions and reduce the distance to hop from one game's development to the other.

**Comment by ChrisBPB** [comment]
Even with a unified api scripts would not work without edits for each game version - which people are not willing to do.

**Comment by AshGreh** [comment]
@ChrisBPB minor edits. Most developers don't mind doing them if they get a bit more revenue. Currently, we have to rewrite a good chunk of code. How many people have you spoken with about this?
