### ISSUE TITLE
[RS3] Treasure Hunter is being opened, and not closed

### ISSUE THREAD

**Issue by anwar6953** [powerbot/powerbot#2022]
Very similar to https://github.com/powerbot/powerbot/issues/580. I only noticed it happening since the past day, but across all RS3 scripts.

The client is opening the Treasure Hunter (TH) interface by clicking the TH popup. It is the popup in the top left:
![image](https://user-images.githubusercontent.com/2440977/50206517-7ea39f80-0320-11e9-949f-4765f322d597.png)

It doesn't close it, though. The bot remains in a state like so:
![image](https://user-images.githubusercontent.com/2440977/50206739-35078480-0321-11e9-9c54-4ed90a66c208.png)

**Comment by ChrisBPB** [comment]
fixed

**Comment by ChrisBPB** [comment]
will do release tonight or tomorrow

**Comment by anwar6953** [comment]
Thanks!
