### ISSUE TITLE
Move org.powerbot.bot.cache in to the open source repo

### ISSUE THREAD

**Issue by benpoulson** [powerbot/powerbot#2024]
In a variety of features I've been working on recently (and plan to submit PRs for), I've had to implement my own cache reader to load models, maps and more from the RS cache.

I would much rather integrate and improve on the Powerbot cache reader.

Would it be possible to expose these classes in the open-source repo?
It doesn't look like there's anything overly proprietary in there.

**Comment by ChrisBPB** [comment]
We will be doing this, but it likely won't be in December

**Comment by benpoulson** [comment]
Amazing, thanks Chris. I'll close the ticket for this.
