### ISSUE TITLE
Component query inconsistent behaviour

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#2036]
None of these queries work in new component query. Works on my own component query, I have checked the height matches the scroll height.

WORLD_WIDGET = 69
ctx.components.select(true,WORLD_WIDGET).scrollHeight(ctx.worlds.list().height()).poll()
ctx.components.select(false,WORLD_WIDGET).scrollHeight(ctx.worlds.list().height()).poll()
ctx.components.select(WORLD_WIDGET).scrollHeight(ctx.worlds.list().height()).poll()
ctx.components.select().scrollHeight(ctx.worlds.list().height()).poll()

https://i.imgur.com/2vIQKVU.png

**Comment by Mkerian10** [comment]
Why are you doing that in the first place,  you're attempting to get the worlds list widget by getting the height stored in the worlds list widget?
