### ISSUE TITLE
[OSRS] Special attack using special attack orb

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#2042]
Latest update added this feature.
"Clicking on the Special attack data orb will now activate your special attack if you are wielding a weapon which has one."

Default behaviour should probably stay with changing tabs as some scripts might have a dependency on being on the correct tab.

**Comment by ChrisBPB** [comment]
uses orb if tab is not opened

**Comment by tanlines** [comment]
Orbs can be hidden within game, making it unable to be clicked.
It also cannot be used in PVP scenarios, not sure if there's a way to determine that.

The current implementation kind of looks like it will spam? Unless clicking it also changes the special attack varp.
IIRC the text/texture colour can determine if you have enough % to use special.

I'll try make a PR later.
