### ISSUE TITLE
Bank::getBank doesn't filter out "fake" banks.

### ISSUE THREAD

**Issue by OneBigOwnage** [powerbot/powerbot#2062]
**I found an issue in [`org.powerbot.script.rt4.Bank`](https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/rt4/Bank.java#L17)**

The `getBank` method searches for any GameObject called "Bank chest", "Bank Chest-wreck" or "Bank booth". Somehow Jagex managed to create "fake" or closed bank booths in some areas in the game. These are called "Bank booth" but they cannot be opened.

This means that if one of those "fake" banks is the nearest bank booth, the mouse will hover over the booth without clicking, as the script is looking for menu actions "Bank", "Use" or "Open" which are not present on it.

An example "fake" booth can be found in Draynor, see image below.
_This is a problem there, as it is the closest bank booth to the player if you are fishing shrimp or chopping willows._

![Fake bank](https://user-images.githubusercontent.com/12835742/59613236-d92a8680-911e-11e9-99b4-d4e0105cb7b2.png)

**Comment by ChrisBPB** [comment]
Unusable banks are specified in constants via their tiles, if it isn’t in the array you can add it
