### ISSUE TITLE
SOCKS5 proxy support

### ISSUE THREAD

**Issue by WuggyRS** [powerbot/powerbot#2065]
Currently getting this error when trying to use a SOCKS5 proxy through the JVM arguments. 
![image](https://user-images.githubusercontent.com/52111974/59968150-9ee42f00-94fa-11e9-9246-7d231d71bac8.png)

Would be nice if there were support for proxies (including authentication)

**Comment by Paris** [comment]
Supporting this would cause some difficulty since the game handles its own connections at a low level. Your best bet is using a VPN.
