### ISSUE TITLE
ctx.bank.Open() Falador East Bank OSRS

### ISSUE THREAD

**Issue by Smileynator** [powerbot/powerbot#2066]
After following some standard code, i try to walk to the falador bank and open it once there. However, the script ends up clicking on the booth through the banker (camera facing north) and opening the booth through the banker. Which results in the message "You can not reach that" because i am on the wrong side of the wall at that point.

Obviously there are ways to fix this on my side, but i suppose if i would do it, i would force open through boot, so your character just walks up to the booth instead of not reaching the banker.

**Comment by Smileynator** [comment]
http://puu.sh/DKu0c.png Image of the issue in question. Image expires in a few months from posting this.

**Comment by ChrisBPB** [comment]
This has always been an issue but it's up to the script to open the bank when it's reachable/usable

**Comment by Smileynator** [comment]
In regards to this, is there a way with the query system to filter banks for Booths only? That would also greatly resolve the issue, because then the bank system without changes, works as intended.
