### ISSUE TITLE
Script hotswapping breaks occasionally

### ISSUE THREAD

**Issue by tanlines** [powerbot/powerbot#2070]
After compiling a couple times, local scripts stop being updated, requiring a restart of the client. Rebuilding does not help.

I have checked the out folder does contain the updated, compiled class files.

**Comment by Paris** [comment]
This is how Java works unfortunately, sometimes hotswapping can fail so you will need to restart. Classes cannot be unloaded easily in Java and there's no way we can outdo an instrumentation agent as good as your IDE.

If you want to be able to hotswap effectively minimise the amount of refactoring you do, i.e. keep changes within method bodies so class, field and method signatures do not change. If they do then obviously you'll have to work when the game isn't loaded.
