### ISSUE TITLE
Whitelists for trading and GE/shop item selling

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#710]
Rather than blocking trade all-together, would it be possible to create a trade whitelist where the user would have to input names?

If the trading window is not from a player on the whitelist, it would cancel it just as it does now. 

This would still have the benefit of added security of the users while allowing more creative scripts, such as RC runners and other inter-account botting activities.

**Comment by Paris** [comment]
The next version resolves this issue by providing the checkbox option *Script > Allow Trades* (off by default). Ticking this allows all scripts to then use the trade interfaces. I believe it's a simpler approach to a whitelist which can be restrictive in cases where parties need to be dynamic.

**Comment by Logicail** [comment]
Is there a method to find out if allow trades is enabled? So you can tell the user to enable it, rather than just constantly opening and closing the trade interface.
