### ISSUE TITLE
Client reloading

### ISSUE THREAD

**Issue by Paris** [powerbot/powerbot#721]
Support the 6 hour session reloading for VIPs, and in general a `reload` method in the client which handles scripts.

**Comment by Strikegently** [comment]
Since the game limit was upped from 6 hours to 24 hours, this is much less of a priority, and may even be unnecessary at this point.

**Comment by Timer** [comment]
I'll leave this one up to @Paris now that it's 24 hours.

**Comment by Timer** [comment]
Assuming this is fine now to not implement, per @Strikegently's analysis.

**Comment by anwar6953** [comment]
I still think this would be valuable, for the case that a scriptwriter would like to run a script for days on end. The breaks could be done programmatically.
