### ISSUE TITLE
Canvas repainting - Linux

### ISSUE THREAD

**Issue by PatriqDesigns** [powerbot/powerbot#778]
Im using Fedora 21, with Oracle's JRE 8 and the canvas doesnt seem to clear itself.
Here take a look: 
![screenshot from 2014-12-22 17 38 04](https://cloud.githubusercontent.com/assets/3120671/5528575/a2a8b948-8a01-11e4-8fb6-bc5395267139.png)

Which is truly annoying makes development a big pain in the ass.
I tried using OpenJDK8 and the jre from the OpenJDK8 but nothing seems to work.

**Comment by IITC** [comment]
For operating systems that do not 'properly' clear upon Graphics#clearRect(int, int, int, int), call Graphics#setColor(Color) to your desired background color. If it's still not clearing, call Graphics#setPaintMode right before clearing, after any manual color changing.

**Comment by Paris** [comment]
After much testing I'm sad to say this can't be fixed.

**Comment by PatriqDesigns** [comment]
Where did you test in? Its yeird because it works on Centos, and not on Fedora..

**Comment by IITC** [comment]
@PatriqDesigns, make sure you're running the exact same environment on both systems.

**Comment by Joe32** [comment]
OpenJDK-7 flickering(not whole client just bot stuff) like crazy, maybe releated? http://w3facility.org/question/java-window-translucency-animation-flicker-on-linux/

**Comment by Timer** [comment]
See #987

**Comment by 4H1Z1** [comment]
I'm experiencing a similar problem but on Rasbian on the raspberry pi

![Image of Yaktocat](https://pbs.twimg.com/media/CR4Y2yAXAAAfT6Y.jpg)

But the paint canvas is fully black and you can only see the screen when you frame the frame and hold it in position

**Comment by Echocage** [comment]
@4H1Z1 I get the same thing when I try to move my rsbot client to any other monitor, this black box that follows the client around when I move the window. Very annoying!

**Comment by IITC** [comment]
@Echocage, I bet one of your monitors is connected through VGA and the other HDMI/DVI? That happens when one of your monitors doesn't support the proper graphics settings as the other. Like with my setup, with has the same problem as yours, my right monitor's X11 drivers don't support transparency or opengl and linux kinda freaks out and turns the paint black as it's new graphics display is unable to cope with the original settings. You'll see if you have issues going left-right, you won't see them going right-left.

**Comment by 4H1Z1** [comment]
@IITC Then how do you explain my problem since i only have 1 HDMI plugged in? :p

**Comment by IITC** [comment]
Probably what I mentioned the problem for when it happens to dual monitor setups. Your graphics drivers just don't support enough to fully operate rsbot.

**Comment by Paris** [comment]
Fixed for the next version thanks to @iitc's comments in #1126.
