### ISSUE TITLE
Combat info popups

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#784]
A method in the API to get which ones are up would be nice. They include things like current poisons, what stats are reduced, if the player is trapped or teleblocked, as well as ability timers (time left on current ability).

The show up just above the combat bar.

![](http://i.imgur.com/C2kqJRn.png)

**Comment by Strikegently** [comment]
Also, could get you get the info from other Npcs?

So you can tell when an Npc is stunned/entangled

![](http://i.imgur.com/2CBuLeQ.png)

**Comment by Timer** [comment]
Done.

**Comment by ArtificialPB** [comment]
Has this been added? I can't seem to find any related methods for it.

**Comment by Timer** [comment]
@ArtificialPB ctx.combatBar.targetEffects()

**Comment by ArtificialPB** [comment]
Awesome, thanks @Timer !
