### ISSUE TITLE
Npc.healthPercent() and healthRatio()

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#785]
Those two methods always return 100 when in EOC mode, even when the npc has less than 100% of its health. It works fine in Legacy mode. I've tried changing interface settings if that would fix the problem but I was not able to resolve it.

**Comment by Timer** [comment]
Is this when they're not engaged or while you're attacking them?

**Comment by Timer** [comment]
Tested fine and it works.  Provide a better case to reproduce.

**Comment by ArtificialPB** [comment]
This happens when it's in combat with the player (haven't tested if someone else is fighting it). Here's a picture of the issue and the code I'm using:
![combatbug](https://cloud.githubusercontent.com/assets/4672155/5724304/01d42d8a-9b4b-11e4-8a8e-2b5e9a099a7b.png)
