### ISSUE TITLE
"signer information does not match signer information of other classes in the same package"

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#794]
Could be an obfuscation problem.

http://www.powerbot.org/community/topic/1242166-whats-the-fix-for-this/

**Comment by IITC** [comment]
I've reported this in the past with no solution found. Hopefully we can find one this time.

**Comment by Paris** [comment]
You're right, its is an edge case problem with obfuscation. Hopefully the next version won't have this issue.

**Comment by Strikegently** [comment]
I got this error while testing local scripts, so that rules out the obfuscation theory. I recompiled the script and it worked fine afterwords. 
Regardless, it's clearly a rare edgecase scenario that it probably impossible to purposefully replicate.
