### ISSUE TITLE
Client arguments

### ISSUE THREAD

**Issue by Logicail** [powerbot/powerbot#795]
Any chance we could have arguments to pass to the client?

* login - username/password/game
* account - rs username/password to login to
* script - which script to run, I'd guess pass the name (assuming unique)/script id/ topic id

**Comment by Paris** [comment]
Can you please give an example of a use case for this?

**Comment by Timer** [comment]
@Paris gold farming.

**Comment by rs-sliske** [comment]
it would allow users to get around the 6h log,
it would also allow non vip to get around the 2h timer though.

personally i would find a feature like this useful for debugging my scripts, the amount of times ive retyped my test accs login details is depressing

**Comment by Logicail** [comment]
The reasons are covered here. 
In reply to the points @rs-sliske made. I suppose the 2 hour thing for non-vips could be resolved by making the `script` argument require the user to be vip+

**Comment by rs-sliske** [comment]
@Logicail wasnt meaning it as a reason not to have this feature, was just pointing out what it could be used as which the devs might want to restrict

**Comment by Paris** [comment]
We'll support this when client reloading is properly implemented in v7.

**Comment by Paris** [comment]
As of the next release the bot recognises the following two properties:

- `bot.login.user` for the account username
- `bot.login.pass` for the password, if this is blank or not specified the account is logged out

The options to specify the game account and script is under review for reasons @rs-sliske mentioned above. Perhaps when #719 is resolved we can look into this again.
