### ISSUE TITLE
Actor.healthPercent() & healthRatio()

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#796]
Since the last one was closed, I'm opening another issue with more information about this bug.

Those two methods always return 100 even when the health is less than 100. It only happens in EOC while in combat. Here's a picture of the issue:
![combatbug](https://cloud.githubusercontent.com/assets/4672155/5789146/7ed67be6-9e5f-11e4-902d-32632f5f9737.png)

**Comment by Timer** [comment]
This is the intended function.

**Comment by Timer** [comment]
These methods only support the bars above your player, obviously.
In EOC, this does not exist for your target due to that information pane.
See combatBar#targetHealth, targetHealthPercent, targetName, targetLevel, etc.

**Comment by ArtificialPB** [comment]
Okay, thank you for your explanation.
