### ISSUE TITLE
Ironman grounditem hook

### ISSUE THREAD

**Issue by Strikeskids** [powerbot/powerbot#797]
Ironmen are unable to pick up items that do not belong to them. It would be nice to know which ones belong and which ones do not.

**Comment by Strikegently** [comment]
#766 

I asked about it, and @Timer said it doesn't exist. That data is somewhere and we need it.

**Comment by Strikeskids** [comment]
I think this might belong as a request to Runescape itself. Then, they would have to add a hook for it.

**Comment by Timer** [comment]
Sorry, but this doesn't exist.
