### ISSUE TITLE
Equipment.itemAt(Slot) ID

### ISSUE THREAD

**Issue by riemann111** [powerbot/powerbot#798]
`ctx.equipment.itemAt(slot).id() == id` returns `false` when the id of the item at `slot` is equal to `id`

**Comment by Paris** [comment]
Are you sure your query is being refreshed with `select()` and the item isn't actually a `Nillable`?

**Comment by riemann111** [comment]
`ctx.equipment.select();`
`ctx.equipment.itemAt(Equipment.Slot.MAIN_HAND).id() == Items.WEAPONS[34]`
Never returns true.

For every case I've tested, `ctx.equipment.select().isEmpty()` always returns True

**Comment by rogerli** [comment]
What are the alternatives to checking equipment at the moment?

**Comment by Timer** [comment]
Fixed.
