### ISSUE TITLE
Hook DirectX to disable rendering.

### ISSUE THREAD

**Issue by Sehyo** [powerbot/powerbot#799]
Hook DirectX to minimize gpu usage.

Example:

Hook DirectX CreateDevice and change it to a null device -> no gpu usage for bots 

Can be done through multiple ways

**Comment by Strikegently** [comment]
Why?

**Comment by Sehyo** [comment]
If you bot multiple accounts and want to use GPU power for something else, this is ideal

**Comment by Paris** [comment]
You can manually go into safe mode by pressing `s` when the bot loads the game, this will not use GPU rendering but that option will still be available. CPU is the limiting factor with bots so disabling OpenGL/DirectX mode will kill performance and increase the power demand. If you need your GPU for something else then perhaps you should not be using the bot on the same machine.
