### ISSUE TITLE
Lobby broken

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#801]
- `Lobby.tab()` → Always returns `NONE`
- `Lobby.tab(Tab)` → Doesn't open tab so it always returns `false`
- `Lobby.worlds()` → Doesn't list any worlds
- `Lobby.world()` → Doesn't get currently selected world and always returns `-1`

**Comment by Strikegently** [comment]
https://gist.github.com/Strikegently/d725161dad884b777807

**Comment by Paris** [comment]
Fixed :)
