### ISSUE TITLE
PollingScript NPE

### ISSUE THREAD

**Issue by Submotion** [powerbot/powerbot#802]
Users have been complaining for > 2 months about this bug and finally somebody caught the error. Happens somewhere around 5-30 minutes (a lot of people complained around 30-40mins). And a few even on startup. 

Machine: Intel i7-4k w 32Gb RAM (waiting for more info on machine)

```
1606 Select your game, then to play a script click Edit > Play 
1606 Starting... 
1606 Loading bot 
1607 Starting Ultra Fletcher 
1644 java.lang.NullPointerException 
     	ij.a(Unknown Source)     
     	zi.poll(Unknown Source)     
	org.powerbot.script.PollingScript$6.run(Unknown Source) 
1654 Starting Ultra Fletcher 
1654 java.lang.NullPointerException     
	ij.a(Unknown Source)     
	zi.poll(Unknown Source)     
	org.powerbot.script.PollingScript$6.run(Unknown Source) 
1655 Starting Ultra Fletcher 
1706 java.lang.NullPointerException     
	ij.a(Unknown Source)     
	zi.poll(Unknown Source)     
	org.powerbot.script.PollingScript$6.run(Unknown Source)  
```

**Comment by Strikegently** [comment]
This is not an issue with PollingScript, but your script.

**Comment by Submotion** [comment]
ij.a(Unknown Source) ?

I've never encountered this error running the script

**Comment by Strikegently** [comment]
ij.a is an obfuscated method in your script.

**Comment by Paris** [comment]
If you push any update to your repository the scripts will be rebuilt with line numbers and source information in the stack trace which you can use to identify the problem.
