### ISSUE TITLE
Movement.reachable() not limited to current floor

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#804]
If a tile is reachable on a different floor than the player currently is, it will keep returning true.

Let's say we're checking Tile(3253, 3421, 1). Checking for reachable will return true even if we're on a different floor.

 This also applies to TileMatrix.reachable().

**Comment by Timer** [comment]
So check your floor.

**Comment by ArtificialPB** [comment]
Shouldn't reachable() method already do this? It seems logical to me that if object query is limited to objects only on current floor that reachable() should work the same way to make it consistent with API and to avoid confusion.

**Comment by Timer** [comment]
patched
