### ISSUE TITLE
ComponentListener

### ISSUE THREAD

**Issue by iitc** [powerbot/powerbot#807]
Can we get something similar to get access to the new applet size? I know you need to restrict direct access to the component to stop the addition of KeyListeners but an alternate approach would be very beneficial to me. My paint framework will not be properly supported on RS3 or 07 (once resizable comes out) without iterating through all loaded frames and stepping down to the content pane of the frame to add the componentlistener.

Here's the mediating object I'd use to dispatch events to my UI. https://github.com/IITC/Java/blob/master/src/iitc/awt/display/AWTConnector.java
I would create an alternate version of this to comply within the limitations of the client but you can notice how I resize my RootPane in the constructor.

**Comment by Paris** [comment]
The next version will have the method [`Input.getComponentSize()`](http://www.powerbot.org/rsbot/docs/org/powerbot/script/Input.html#getComponentSize()) which you can use to get the size of the game applet.
