### ISSUE TITLE
Proper Frame Resizing

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#810]
Can we get proper frame resizing to remove the unnecessary black space surrounding the rs applet? Maybe even allow resizing the frame when using old school? I can't resize the client how I want to in eOS. Also maybe wrap the applet in a JScrollPane so the user can shrink the client but still scan to the script paint to get updates. Thanks.

**Comment by Obicere** [comment]
Been meaning to make one of these for a while.

[AspectRatioLayout](https://gist.github.com/Obicere/d30cb542a64ab9a4a513)

You just add the container to a panel with this layout, set the desired aspect ratio and it will handle all the padding as per the alignments.

**Comment by IITC** [comment]
Obicere, while that is a nice layout (despite some minor flaws I noticed) just using a centered FlowLayout is enough for applet placement within the container. :P

**Comment by Strikegently** [comment]
This can be closed.

**Comment by Timer** [comment]
Unfortunately, we cannot center the applet any longer due to the implementation of resizable mode.
