### ISSUE TITLE
String: Index out of bounds

### ISSUE THREAD

**Issue by Algol0x7DB** [powerbot/powerbot#812]
Viewing Npc's, Menu → View → Npcs, gives an `StringIndexOutOfBoundsException`, when *Swarm* is in view on *Karamja/Musa Point* area.

![Image of ScreenCap](http://i.imgur.com/KmoF1fm.png)

![Image of CMD](http://i.imgur.com/0xtzJu1.png)

**Comment by Strikegently** [comment]
I got the same issue. That's weird.

**Comment by Timer** [comment]
Fixed
