### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by NexPB** [powerbot/powerbot#814]
java.lang.NullPointerException     com.sun.java.swing.plaf.windows.XPStyle.getTypeEnumName(Unknown Source)     com.sun.java.swing.plaf.windows.XPStyle.getBorder(Unknown Source)     com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPBorderValue.getXPValue(Unknown Source)     com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPValue.createValue(Unknown Source)     ph.a(ph.java:236)     ph.<init>(ph.java:27)     ce.run(ce.java:54)

**Comment by Strikegently** [comment]
Try formatting that, so I can actually read it.

**Comment by Alec55500** [comment]
2208 Select your game, then to play a script click Edit > Play
2208 Starting...
2208 Loading bot
2209 Starting MasterChopper
2209 java.lang.NullPointerException 
	com.sun.java.swing.plaf.windows.XPStyle.getTypeEnumName(Unknown Source)
	com.sun.java.swing.plaf.windows.XPStyle.getBorder(Unknown Source)
	com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPBorderValue.getXPValue(Unknown Source)
	com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPValue.createValue(Unknown Source)
	ph.a(ph.java:236)
	ph.<init>(ph.java:27)
	ce.run(ce.java:54)

**Comment by Strikegently** [comment]
This is an issue with your script, not the client.

**Comment by NexPB** [comment]
Everything runs fine local for me..
