### ISSUE TITLE
Shop Inventory

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#817]
[rt4] I'm trying to sell items to a shop but the current inventory is returning false for valid checks for all items which, i assume, stops any interaction from proceeding. I am testing using the Karamja General Store.

**Comment by NexPB** [comment]
Yh I'm pritty sure it's a different interface.

**Comment by Timer** [comment]
Just tell me the interface and I'll add it!

**Comment by Timer** [comment]
Added
