### ISSUE TITLE
Intermediate Interface [Locatable & Interactive]

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#818]
Can we get a SceneEntity of sorts to please generics compiling, please? You cannot create something designated for multiple game interactives currently and it's very frustrasting. My interaction system has a LocatableInteractor which prepares by turning camera/moving/etc then interacting with an object. The type parameter for LocatableInteractor must extend both Locatable & Interactive and there is no interface to achieve a clean static type across the board. 

Example of frustration:
https://gist.github.com/IITC/e36ebc726c9286bb9a3d
where it could be simplified to:
https://gist.github.com/IITC/fc984ee6f3f1fc5c5614

(if you're wondering why i have them initialized separately, I change the action string for the first interactor throughout runtime. :P)

**Comment by Timer** [comment]
org.powerbot.script.rt6.Interactive

**Comment by IITC** [comment]
I'm talking for both rt4 and rt6. An interface signifying an interactive with a tile would be lovely.

**Comment by Timer** [comment]
org.powerbot.script.Targetable
org.powerbot.script.Locatable
org.powerbot.script.Identifiable

All super level.
If you notice, the super-level APIs (mouse/input api) accepts Targetables -- not Interactives.

**Comment by Timer** [comment]
Unless if you're asking for a super-level interface which abstracts Interactive?

**Comment by IITC** [comment]
I'm interacting with multiple objects that are also locatables. It has nothing to do really with your API capabilities, it's just creating extensions that are multi-functional. The intermediate class/interface wouldn't have to have any functionality. It just needs to unify all scene entities.

**Comment by IITC** [comment]
Sorry, it would need to function as combining Interactive and Locatable.

**Comment by IITC** [comment]
I'm not in office to update my code, which is like 5-6 commits behind, but here is the class that you need. Notice the type parameter for the class. https://github.com/IITC/Powerbot/blob/master/src/iitc/rsbot/util/rt4/LocatableInteractor.java

**Comment by Strikegently** [comment]
```N extends Interactive & Locatable & Identifiable & Nameable```
Works just fine. Any instance of `N` has access to the interaction methods, as well as IDs, names, and tiles.

**Comment by IITC** [comment]
@Strikegently, I mentioned having a clean static type to use across the board. I wish to reference it directly and not have to cast at all. I already generalized my implementation enough. It's the matter of referencing the variable, after instantiating it. For example, ```List<???> list = new ArrayList<>(some instance of 'n');``` There's no unifying interface/class to reference when calling upon members of that container. list.get(int) would not return a useful static type. There are quite a few interactives that are also classified as locatables so I feel as an interface explicitly identifying those types of entities would be beneficial.

**Comment by Timer** [comment]
Added `org.powerbot.script.Interactive` and `org.powerbot.script.InteractiveEntity`.
