### ISSUE TITLE
First/Last Items Filter

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#819]
For the inventory, could we have a method that removes all extra instances of items with the same id? Options for the first and last instance of an item would be great. I can do this manually at the moment but it requires either creating a new filter each call or purging my item cache each call which is just too expensive for my liking.

**Comment by IITC** [comment]
The cache purging would be an additional method call, outside the query, which is also frustrating.

**Comment by IITC** [comment]
I created an easier method of performing this task but I'd see love to see it integrated into the client.

https://gist.github.com/IITC/7e7599e9622e624d3e0c

**Comment by Strikegently** [comment]
id().first()
id().reverse().first()
???

**Comment by IITC** [comment]
All items in the inventory. I don't want to query n times to accomplish this.

**Comment by Strikegently** [comment]
inventory.addTo(set)
return select(set)

**Comment by IITC** [comment]
Waste of memory.. Again, I'm looking for an inline solution.

**Comment by Strikegently** [comment]
It won't get any more efficient than that.

**Comment by IITC** [comment]
Yes it will. Lol your method copies the backing list twice. I don't want 2n method calls when I could have 1. 1 iteration removing copies of each item is the algorithm I want implemented. Not piecing together individual queries.

**Comment by Strikegently** [comment]
Just extend the Inventory and implement it however you'd like. You're requesting something incredibly niche that I can't really see a purpose for. The API is extendable for this very reason.

**Comment by IITC** [comment]
It's used for banking multiple items, selling multiple items, and combining items efficiently. A majority of scripts would make sure of this. Otherwise, I wouldn't make this request.

**Comment by Strikegently** [comment]
```
    public Backpack removeDuplicates() {
        return select(new Filter<Item>() {
            @Override
            public boolean accept(Item item) {
                return !contains(item);
            }
        });
    }
```

**Comment by IITC** [comment]
Just stop. Lol that wouldn't even remove a single item btw.

**Comment by Timer** [comment]
Internals would have to be doing the same EXACT thing you're doing, so there's no point in implementing as it can't get more efficient.
Here's a proposed solution.
https://gist.github.com/Timer/b59bcd4664922c38ea07

**Comment by Timer** [comment]
Sorry I understood the question wrong, here's a different solution.
https://gist.github.com/Timer/fbd96039cf8d1e60d6ef

**Comment by IITC** [comment]
I only mentioned it because I thought it'd be a great API addition for everyone. :P

**Comment by Timer** [comment]
@Paris I don't really see a use for this, see my second gist for what he's trying to accomplish.

**Comment by IITC** [comment]
https://github.com/IITC/Powerbot/blob/master/src/iitc/rsbot/util/rt4/InventoryManager.java

Depositing multiple items in inventory with mutliple entries.

**Comment by Timer** [comment]
I'm not following, @IITC

**Comment by IITC** [comment]
Let's say you're depositing 7 logs, 4 bows, and 8 air runes. The best way to do this would be find the first of each of them and interact with "Deposit-All" or "Deposit-10" rather than iterate over every item in the inventory.

**Comment by Timer** [comment]
@IITC that's why Bank#deposit exists.
		for (final Item i : ctx.backpack.select().id(junk)) {
			if (!i.valid()) {
				continue;
			}
			ctx.bank.deposit(i.id(), Bank.Amount.ALL);
		}

**Comment by Timer** [comment]
While I understand what you are asking for (now), @IITC.  I think this is asking for a bit too implementation-specific API as it only has application in the backpack.  Since you're already beyond using bank and doing custom depositing, just handle this yourself.

**Comment by IITC** [comment]
Actually run your code and you'll know why this is necessary.

**Comment by IITC** [comment]
Understandable.

**Comment by IITC** [comment]
As long as the ClientContext consistency gets resolved, I can effectively start using custom ClientContext.

**Comment by Timer** [comment]
I was lost on that ClientContext request, can you elaborate more in that issue?
And I know how it functions so I don't need to run my code, @IITC.  Deposit is blocking (waits for the item to actually disappear), so all items of the same id afterward would be invalid and thus skipped.

And I'd just do something retarded like this

		final int[] depositIds = {};
		Arrays.sort(depositIds);
		ctx.backpack.select().id(depositIds).select(new Filter<Item>() {
			private final boolean[] found = new boolean[depositIds.length];

			@Override
			public boolean accept(final Item item) {
				final int index = Arrays.binarySearch(depositIds, item.id());
				return !found[index] && (found[index] = true);
			}
		}).each(new Filter<Item>() {
			@Override
			public boolean accept(final Item item) {
				if (item.valid()) {
					item.interact("Deposit-All");
				}
				return true;
			}
		}).each(new Filter<Item>() {
			@Override
			public boolean accept(final Item item) {
				return Condition.wait(new Condition.Check() {
					@Override
					public boolean poll() {
						return !item.valid();
					}
				}, 50, 20);
			}
		});
		final boolean success = ctx.backpack.select().id(depositIds).isEmpty();

**Comment by IITC** [comment]
I'll post on that thread. I was commenting on the speed difference really. No need for waiting until the item disappears when you can be done by then. :P

**Comment by Timer** [comment]
That's what my second snippit there does fine without adding new things to the query api!
We don't want to add in bloat that isn't necessary, that's why we added the select(Filter) so people could customize their queries.

**Comment by IITC** [comment]
True true. I only use it once anyways in the way I modularized the SetupItems. Lol
