### ISSUE TITLE
ClientContext Consistency

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#820]
Method classes don't use the same ClientContext as the parameterized Script class instance, it uses the "child" ClientContext of the current one.

**Comment by Timer** [comment]
Lay it on me @IITC.  Give me some code example or explain more.

**Comment by IITC** [comment]
The ClientContext constructor that uses another ClientContext just passes the method classes that were already constructed using that ClientContext. The input method class even uses the most basic ClientContext that uses a Bot parameter. Sorry, I'm on phone so I can't go to in depth.

**Comment by IITC** [comment]
I'll post an example. 

Let's say I have a custom ClientContext called IITContext. 
ClientContext base = new ClientContext(new Bot());
...rt4.ClientContext publicConstructor = new ...rt4.ClientContext(base);
IITContext ctx = new IITContext(publicConstructor);

The input method class is constructed using base. 
All other public method classes are constructed using publicConstructor. 
These are all then passed to the custom context.

**Comment by IITC** [comment]
Most likely gonna have to change it via reflection.

**Comment by Strikegently** [comment]
You shouldn't be instantiating the ClientContext, except your custom on.
Pass around the context instance created by the client.

For reference:
http://www.powerbot.org/community/topic/1178781-rsbot-6-properly-extending-the-api/

**Comment by Paris** [comment]
This is by design, it means you cannot override the API internals, in other words your custom `ClientContext` is isolated to your script code only.
