### ISSUE TITLE
Force Nillable to extend Validatable

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#821]
Technically, everything that implements Nillable can be valid if it doesn't equal #nil(). Could we see this added across the entire API? It's not a critical change, just something I find logically correct.

**Comment by Timer** [comment]
This doesn't make any sense, nil is in the query not the object -- and valid already is present in all of those classes.

**Comment by IITC** [comment]
Tile lacks a valid method.

**Comment by Strikegently** [comment]
TileMatrix

**Comment by IITC** [comment]
TileMatrix checks if the Tile is loaded within the current game region. A valid Tile would be one that exists in the game.

**Comment by Timer** [comment]
Tile is a universal API, not specific to a context.  There is no "game".

**Comment by IITC** [comment]
Fair enough.

**Comment by IITC** [comment]
Ever consider moving the TileMatrix getter to ctx.movement.matrix(Tile) so that way you could make use of a nill TileMatrix and cache if necessary?

**Comment by Timer** [comment]
No because there's no "query" for tiles.
