### ISSUE TITLE
Covarient Return Type with Queries

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#822]
Can we see covariant return types taken advantage of in the core method classes along with more specific convenience methods such as: #actions(String...) for Npc, #at(int...) for Inventory, #at(Equipment.Slot...) for Equipment? I know it'd cause confusion to query Inventory and then call #itemAt(int) but it would allow the use of additional filter convenience methods.

**Comment by Strikegently** [comment]
Actions is understandable and could be useful, but what's the purpose of at() for slot index in the inventory and equipment? Only one item can be at a specified slot.

**Comment by IITC** [comment]
Those were just examples of extensions. You could check if you're wearing items at certain equipment slots.. You could check if your inventory is setup a certain way to optimize actions. Mostly higher level applications.

**Comment by Paris** [comment]
This level of complexity provides little benefit and won't be implemented.
