### ISSUE TITLE
Higher Level Directory Access

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#824]
Can we have access to the RSBot folder and not just the script directory? I don't want to save my web file for each script folder when I have it referenced once. I also need to save it in the constructor of my custom ClientContext and controller.script() is not assigned yet so there's no current way to accomplish this without overriding the parent ClientContext in the AbstractScript subclass.

**Comment by IITC** [comment]
If this directory is already available for saving, could we get a convenience method for it? I want some insurance my scripts will always have the ability to store the web file.

**Comment by Strikegently** [comment]
You can access everything in $TMP/RSBot.

**Comment by IITC** [comment]
Alright then, see my second post.

**Comment by Strikegently** [comment]
Make them separate methods, please, so this doesn't mess up script-specific settings.

**Comment by Paris** [comment]
As @Strikegently said you can use the temp folder for shared access. Your second request will be discussed in #839.
