### ISSUE TITLE
Bank#open and Bank#nearest

### ISSUE THREAD

**Issue by iitc** [powerbot/powerbot#825]
Bank for rt4 needs opening methods. 
If you want a code reference, https://github.com/IITC/Powerbot/blob/master/src/iitc/rsbot/script/rt4/Bank.java
It's messy at the moment due to #818. I also support isolating individual bank types as interacting with bankers sometimes leaves you outside the bank; something I liked to combat.

**Comment by Strikegently** [comment]
This is already done for v7. 

If you remember, the reason it wasn't available before was because of the constantly-changing IDs.

**Comment by IITC** [comment]
Well if it's done for v7, sweet. Bank type isolation is a necessity/ Interacting with bank booths alone relieves the issue of getting stuck outside banks.

**Comment by Timer** [comment]
Added in #1201
