### ISSUE TITLE
Item.inViewport

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#828]
`Item`s are never in viewport but to make use of this method, could we have it return `true` when it's valid?

**Comment by Paris** [comment]
@Timer perhaps this is as easy as adding an override method implementation in the `Item` class for `boolean inViewport()` which returns the value of `valid()`?

**Comment by Timer** [comment]
@Paris as far as I'm concerned viewport is the viewport... however we can make this change if you so desire.

**Comment by IITC** [comment]
Viewport is different for varying objects. Bank items is the bank. Inventory items is the inventory. Game objects is the viewport that's being used now.

**Comment by Timer** [comment]
Items cannot be in viewport. This request is denied. I would use the properly associated method for this, which is `ctx.backpack.scroll(Item)`.
