### ISSUE TITLE
Locatable#distanceTo(Locatable) Convenience Method

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#830]
Could we get this added? For npcs/objects that take up multiple squares, you could even generate the shortest distance to them to get a realistic calculation.

**Comment by Strikegently** [comment]
Locatable.tile().distanceTo(Locatable)

**Comment by IITC** [comment]
Read the title.. I'm asking for a convenience method..

**Comment by IITC** [comment]
Also, read the post.. Just reread everything before you post next time, please.

**Comment by Strikegently** [comment]
is 8 extra characters that much of an issue? 

If we supported Java 8, this could just be added as a default method to the interface; but we don't support Java 8.

**Comment by IITC** [comment]
I explained myself in the OP, I don't feel like doing it again.

**Comment by Timer** [comment]
No, these are functions public-libraries should provide, not the API itself.

**Comment by IITC** [comment]
One, there's no way for public libraries to provide these functions without access to the area of an npc. Two, it's a very simple addition and would make it work both ways. A Tile is a locatable so you can call Tile#distanceTo(Locatable) but there is no Locatable#distanceTo(Locatable/Tile).
