### ISSUE TITLE
Viewport filters

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#831]
I know there's the `areInViewport()` filter that can be used, but a `inViewport()` filter directly in the query chain makes it flow a little better; i.e.

```
ctx.npcs.select().id(...).inViewport()
```
rather than
```
ctx.npcs.select().id(...).select(Interactive.areInViewport())
```

**Comment by IITC** [comment]
Query.Viewable#viewable()

**Comment by IITC** [comment]
https://github.com/IITC/Powerbot/blob/master/src/iitc/rsbot/script/rt4/Distractions.java#L52
for a code reference

**Comment by Strikegently** [comment]
or, you know, just ```return select(Interactive.areInViewport())```

**Comment by IITC** [comment]
True, pretty sure both do the same exact thing. lol

**Comment by Paris** [comment]
The `viewable()` filter as @IITC suggested is the recommended way.
