### ISSUE TITLE
TileMatrix.onMap not completely accurate

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#832]
![Image of Minimap](http://i.imgur.com/3Qa0TL1.png)

**Comment by Timer** [comment]
Accurate now.

**Comment by Timer** [comment]
![](http://puu.sh/iCzz9/0ef4880588.png)
![](http://puu.sh/iCzEw/e668439b37.png)

**Comment by IITC** [comment]
You can expand the bounds on the non-resizable mode, if you want. You can click into the surrounding UI some bit.
