### ISSUE TITLE
Tile.tile()

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#834]
Can you make `Tile.tile()` return a separate tile instance or make `Tile` final or make `Tile` not a `Locatable`? Subclassing `Tile` and properly overriding `equals()` and `hashCode()` has some very undesirable effects for when using `tile()`. I'm not subclassing `Tile` anymore but I'd like to see some security for that method/class.

**Comment by Timer** [comment]
No.  I don't see the necessity of this.

**Comment by IITC** [comment]
There are consistency issues. I'm asking for finalization of the class to avoid improper subclassing. Finalizing the class as a whole or the Tile#tile() method.

**Comment by Timer** [comment]
There is no such thing as improper subclassing -- subclassing lets you do what you want for a reason.

**Comment by IITC** [comment]
Then you can call it a design flaw. A tile is a position that has a position. A tile shouldn't be a Locatable. Nothing in the API requires it to.

**Comment by IITC** [comment]
All Tile needs is a Tile#distanceTo(Tile) to make up for the removal of the Locatable interface and you'd have the same function with no breakages.

**Comment by Strikegently** [comment]
>A tile shouldn't be a Locatable

A locatable is something that has a location. A tile not only has a location, but IS a location.

**Comment by IITC** [comment]
How is that logical? A tile represents a point within space. It is literally the most basic unit of space. Anything that possesses a tile exists within the coordinate space. It's at a higher level of existence than a tile. A tile does not exist in the coordinate space, it simply represents an objects location. There has to be some sort of hierarchy. What would you call someone who has a car? A car owner. Is a car a car owner? There is a sense of ownership that the hierarchy must abide by. Having something and being something are two completely separate things.

**Comment by IITC** [comment]
This has been effectively accomplished in other frameworks if you seriously need this functionality. However, the getter must return a separate object. Look at Point.

**Comment by IITC** [comment]
That way the getter has the basic unit, not the redefined one. Calling Tile#tile() should equal TileB#tile().

**Comment by Timer** [comment]
They do equal one another.

**Comment by IITC** [comment]
They do from Tile but not from TileB. TileB would need a TileB with the same qualities to return true. A regular Tile wouldn't suffice.

**Comment by IITC** [comment]
Returning a copy for Tile#tile() would resolve any issues.
