### ISSUE TITLE
Target Reticules

### ISSUE THREAD

**Issue by Strikeskids** [powerbot/powerbot#836]
Can we have this implemented? Would be very helpful :)

**Comment by Timer** [comment]
wat

**Comment by Strikegently** [comment]
http://runescape.wikia.com/wiki/Interface#Interface_options

**Comment by Strikeskids** [comment]
^ Be able to query which monsters have the red circly thingy and which ones have the yellow circly thingy.

**Comment by Timer** [comment]
Ooooooo okay

**Comment by ArtificialPB** [comment]
Any news on this @Timer ?

**Comment by Timer** [comment]
I could not find hooks for this, if anyone has a direction, please inform me.
