### ISSUE TITLE
Item prices

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#837]
Since prices are associated with items in-game, it would be fantastic to have a method to get the price.

I mentioned this to @Timer briefly and he said he would look into it for v7, but the sooner this is available, the better. 
External sources for prices are far too unreliable.

**Comment by IITC** [comment]
This would be fantastic with rt4 and rt6 as both game modes feature a Grand Exchange.

**Comment by Strikegently** [comment]
Does RT4 have the same style as RT6, where you get the price when you examine an item?

**Comment by IITC** [comment]
No but there should be a lookup method within the client as there is a lookup module within the price checker.

**Comment by Timer** [comment]
This cannot be done, it is a server side call and calling game methods = detection.  Sorry.
