### ISSUE TITLE
Directory Initialization

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#839]
Can you add a `#mkdirs` call within the `State.START` runnable like you currently do within `State.STOP`? The temp directories are either being lazy loading during runtime or being called as the script is stopping. Why not just initialize them straight away?

**Comment by Paris** [comment]
Fixed for next version.

**Comment by IITC** [comment]
Does this include the convenience method for the parent directory or just the earlier initialization? Thanks.
