### ISSUE TITLE
Chat.clickContinue() bug

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#840]
It sometimes doesn't correctly click on the continue button while chatting and it starts clicking on players / npcs head icon instead. Picture of the issue: 
![chatbug](https://cloud.githubusercontent.com/assets/4672155/6647834/08d95de2-c9d3-11e4-9513-cc88c6ca7428.png)

This is rt6.

**Comment by Timer** [comment]
Fixed
