### ISSUE TITLE
Bank.withdraw(id,amount)

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#843]
When we have a stack of only two items in bank and we only need to take one it will withdraw it by clicking "Withdraw - All but one" action instead of just clicking it. It works normally if the stack in bank has more than two items. This happens every time.

This is rt6.

**Comment by IITC** [comment]
Pretty sure it's up to you to adjust the passed amount according to bank count.

**Comment by ArtificialPB** [comment]
I think you misunderstood what I was trying to say. Let say we have two Enchanted Gems in bank and we only want to take one. When I pass "1" as the amount parameter it clicks "Withdraw - All but one" instead of just clicking it. However it works fine (withdraws by clicking on the item once) if we have three or more Enchanted Gems in bank.

**Comment by IITC** [comment]
Ah yes. That's definitely not a good thing. :P

**Comment by IITC** [comment]
Alongside this fix, could Bank#withdraw(int,int) make use of present Withdraw-X actions(Withdraw-12,Withdraw-12837) rather than redundantly re-enter the string using Withdraw-X - Enter Amount?

**Comment by ArtificialPB** [comment]
I support suggestion made by @IITC. It would make the bot look a bit more human-like.

**Comment by Timer** [comment]
Fixed, and @IITC it already works like this unless the actions hook is broken.
