### ISSUE TITLE
NullPointerException when starting script

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#845]
From what I've seen, it's only free users using free scripts.

http://www.powerbot.org/community/topic/1254130-no-bots-will-run-for-me-on-the-new-update/?p=15212776

**Comment by IITC** [comment]
I've also gotten reports of free users who are able to run scripts and bypass any run limits.

**Comment by Strikegently** [comment]
Haven't seen anything else about this, so i'll assume it's been fixed.
