### ISSUE TITLE
Proper inCombat method

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#846]
The `inCombat()` method currently just returns if the health bar is above the player. The game uses stance to determine it. 
So the API can say that the player is not in combat, but the game says the player is. This causes issues with trying to do things that are blocked by combat. 

RT6.

**Comment by Timer** [comment]
inCombat is a server call, so there's nothing we can actually do that says "hey you're actually in combat", do you have any existing code that examines stance, animation, stance/animation of interacting npc?

**Comment by Strikegently** [comment]
Yes, but it isn't very accurate because I don't have all of the combat stance IDs. They change based on what  kind of weapon the player has equipped and their gender.

**Comment by ArtificialPB** [comment]
I've solved this by starting a looping checker on a worker thread. What this checker does is it checks if player is under attack or if the player is attacking anyone. If not, start the 10 second timer which acts as a combat timeout. After this timer finishes we're definettly out of combat.
