### ISSUE TITLE
Npc.inCombat() broken

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#848]
It seems to return false in EOC mode, however it works fine in Legacy. If I remember correctly, it worked until recently in EOC too. Could this be related to https://github.com/powerbot/powerbot/issues/796?

rt6

**Comment by Timer** [comment]
This is for the same reasons.  Nothing we can do.

**Comment by ArtificialPB** [comment]
Thank you for your reply. I've updated my code to reflect on this limitations.

**Comment by Timer** [comment]
@ArtificialPB Yes, unfortunately, our names of inCombat, getHealthPercent, etc, aren't their true names.
inCombat is actually hasRenderedHealthbar
getHealthPercent is a representation of getHealthbarRatio and getHealthbarMax(=255)

**Comment by ArtificialPB** [comment]
Noted, thanks. I've changed my code so it now checks if anyone is already interacting with the desired npc, which should return similar results as inCombat check.
