### ISSUE TITLE
Move storage directory

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#849]
Storing everything in the temp directory can cause problems, especially with software that routinely clears the directory (like many antivirus software do).

Moving it to user home would be a far better solution. 
User home/RSBot for all RSBot settings, user home/RSBot/Script Settings for script-saved settings.

**Comment by Paris** [comment]
After reviewing this I decided not to implement it: moving to a persistent storage directory will clutter the users file system which can have a compounding effect if they try a variety of scripts. They should most cleaning software are configured to ignore temp files younger than 48 hours old, so just update the file modification timestamp when your script starts to preserve those files.
