### ISSUE TITLE
Missing Resource Exception

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#850]
One of my users reported that this issue has been thrown when script was running.

**Stacktrace one:**
*java.util.MissingResourceException: Can't find bundle for base name sun.text.resources.FormatData, locale en_AU 
org.powerbot.bot.AUX.catch(Unknown Source)
org.powerbot.bot.AUX.break(Unknown Source)
org.powerbot.bot.AUX.stop(Unknown Source)
org.powerbot.script.PollingScript$6.run(Unknown Source)*

**Stacktrace two:**
*java.util.MissingResourceException: Can't find bundle for base name sun.text.resources.FormatData, locale en_AU 
z.CON.break(Unknown Source)
z.aux.catch(Unknown Source)
z.nUl.break(Unknown Source)
z.nUl.break(Unknown Source)
z.coM7.run(Unknown Source)*

**Comment by Paris** [comment]
Looks like a locale error, tell him to reinstall the latest Java.

**Comment by ArtificialPB** [comment]
Alright, thanks for clearing that up. I'll notify users to reinstall java if they get the issue again.
