### ISSUE TITLE
Persistent Interact Point Support

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#853]
Can we get an interact method that doesn't readjust the interact point if the interactable contains the mouse point or if, given no model, the mouse is within a certain distance of the base point and the menu contains the command we're looking for? I'm trying to repetitively click an npc and the readjustment of clicking position is very bot-like and I can't really remedy this without creating my own interactions.

**Comment by Timer** [comment]
It already works like this.

**Comment by IITC** [comment]
When you say it already works like this, is that in the current revision? Because I tested it literally moments before posting the request.

**Comment by Timer** [comment]
You did not explain your request carefully, Coma clarified.

**Comment by IITC** [comment]
Sweet, thanks.

**Comment by Timer** [comment]
The only problem with this is that a human does move his mouse ever-so-slightly when he right clicks because the mouse will jitter.
Would you be okay with just less movement?

**Comment by Timer** [comment]
Like so...
```diff
diff --git a/src/org/powerbot/script/Input.java b/src/org/powerbot/script/Input.java
index 9268287..3f10836 100644
--- a/src/org/powerbot/script/Input.java
+++ b/src/org/powerbot/script/Input.java
@@ -121,6 +121,13 @@ public abstract class Input {
 	}
 
 	public final boolean apply(final Targetable targetable, final Filter<Point> filter) {
+		final Point sp = getLocation();
+		if (targetable.contains(sp)) {
+			sp.translate(Random.nextInt(-3, 4), Random.nextInt(-3, 4));
+			if (filter.accept(sp)) {
+				return true;
+			}
+		}
 		final Point target_point = new Point(-1, -1);
 		final int STANDARD_ATTEMPTS = 3;
 		for (int i = 0; i < STANDARD_ATTEMPTS; i++) {
```

**Comment by Timer** [comment]
I implemented above code.
