### ISSUE TITLE
Interaction Upgrade

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#855]
I've noticed when you try to interact with an object while moving, the mouse just catches up eventually and clicks on the point but the movements in which is keeps up are very bot-like. I was wondering if you could compose a solution to utilize an estimated moving-point projection? Find the approximate speed of your mouse and estimate the ending tile location of your player where he would actually click the object by that time accounting for the current destination, mouse positioning, and orientation. You could use the "travel distance" to generate a slight advancement of the interact point to adjust for mouse lagging.

**Comment by Paris** [comment]
Merge into #777

**Comment by Mkerian10** [comment]
Was this ever implemented? We could revisit this now
