### ISSUE TITLE
Some way to detect what spell or item you have selected

### ISSUE THREAD

**Issue by 4H1Z1** [powerbot/powerbot#858]
Currently on 07 there is no way to detect what item or spell you have selected unless you are hovering over a item or object, for example useing ctx.menu.items()[0] will only throw 'Cancel' until you hover over a item and then it will show the spell or item you have selected.
https://www.powerbot.org/community/topic/1260125-check-to-see-if-level-1-enchant-is-selected/#entry15273024

**Comment by Strikegently** [comment]
For clarification: he wants an RT4 equivalent to client.isSpellSelected()

**Comment by MookyMan** [comment]
Would enjoy this @Timer  :)

**Comment by IITC** [comment]
For the time being, check the border thickness on all the spell components of the spellbook. If there is no setting for it, I assume that's what you'd use @Timer.

**Comment by Timer** [comment]
@IITC @MookyMan ctx.magic.spell() should work

**Comment by Timer** [comment]
Like stated previously, ctx.magic.spell().
