### ISSUE TITLE
Outdated widgets

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#859]
Following the major interface update this morning, quite a few widgets changed. I'll update this as I find more things that are broken.

Health:
- Regenerate: 1430, 3
- Points text: 1430, 4, 7

Adrenaline:
- Toggle auto-retaliate: 1430, 47
- Points text: 1430, 48, 7

Prayer:
- Quick prayer toggle: 1430, 10
- Points text: 1430, 11, 7

Summoning:
- Familiar options: 1430, 16
- Points text: 1430, 17, 7

Ability IDs and Type are correct, but 
- `ready()`
- `cooldownPercentage()`
- `bind()`, and 
- `queued()` are wrong.

**Comment by Timer** [comment]
Holy moley.  Will fix tonight.

**Comment by Timer** [comment]
Fixed.

**Comment by ArtificialPB** [comment]
Why not just use varps for Action.queued() ? Here's my implementation of it:

```java
private static final int QUEUED_VARPBIT = 4164;
public boolean queued(Action action) {
		return (action.slot() + 1) == ctx.varpbits.varpbit(QUEUED_VARPBIT);
}
```
