### ISSUE TITLE
OSRS interactions broken

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#862]
Latest update broke interactions in OSRS.
Also, it introduced resizable mode so you should allow the user to resize the window.

**Comment by Timer** [comment]
Fixed interactions and updated inventory for resizable mode.

**Comment by Timer** [comment]
Pinging @Paris for considering resizable mode.

**Comment by Timer** [comment]
@Paris fixed resizable mode and pushed it.
@Strikegently full resize implementation now done
