### ISSUE TITLE
Bank Widget IDs changed

### ISSUE THREAD

**Issue by R3dundant** [powerbot/powerbot#864]
Widget changed [RS3]

**Comment by Strikegently** [comment]
Withdrawing is also broken. The bank query returns empty.

**Comment by Strikegently** [comment]
Close button is 762, 323, 1
Item widgets are 762, 235

**Comment by Paris** [comment]
Fixed for next version.

**Comment by R3dundant** [comment]
close button changed again as of today.
new close button is 762, 327, 1
