### ISSUE TITLE
Add Npc cache reading

### ISSUE THREAD

**Issue by Timer** [powerbot/powerbot#866]
Npc cache reading for RT4. Specifically, names and actions.
note to self -- make sure to get other useful things (colors?).

**Comment by Strikegently** [comment]
once you get this, you could go ahead and add in the bank stuff.

#825 
#826 (since objects are already done)

**Comment by Timer** [comment]
@Strikegently that's a good point -- find objects by name with actions "Bank", and Npcs too.

**Comment by Timer** [comment]
Done.
