### ISSUE TITLE
Adding custom components to account for in inViewport method

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#868]
I would like to check if interfaces like Hero, Looting interface, etc., are blocking the view from entities. The only way to achieve this right now is by writing our own method of inViewport to account for it. It would make everything much easier if there could be something added so we can add our own components/rectangles to account for in base inViewport method. I can provide additional information about what I'm trying to achieve, if necessary.

**Comment by IITC** [comment]
inViewport is supposed to return true when the entity is in the viewport. Not necessarily visible or clickable. You'd have to create your own method.

**Comment by ArtificialPB** [comment]
Well it does check if any HUD interfaces are blocking it.

**Comment by Strikegently** [comment]
You can override inViewport(), return super.inViewport() && !blockingComponent.contains(centerPoint)

**Comment by ArtificialPB** [comment]
I'd have to create wrapper classes for each entity that implements Viewable and extend queries to return wrapped ones with overridden inViewport.

**Comment by ArtificialPB** [comment]
Never mind, already done what coma said.

**Comment by Timer** [comment]
Effectively, the API does not support these widgets anywhere in the API -- so they're obviously not supported by inViewport. inViewport obeys (or should), and widgets accessible by the API. If you exit that scope, you're on your own!

**Comment by ArtificialPB** [comment]
Alright, will keep that in mind with future requests.

**Comment by Timer** [comment]
The problem is that it would be tons to keep track of, not to mention when something breaks someone might just think it's not a feature @ArtificialPB. To keep it simple -- if the API can open it -- inViewport should support it.
