### ISSUE TITLE
RT4 GroundItem#actions() and Item#groundActions()

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#870]
Same functionality in each. Both fields are in ItemDefinition.

**Comment by Timer** [comment]
@IITC actions for ground items should've been groundActions.
See backpackActions for backpack.

**Comment by IITC** [comment]
This is RT4. Oldschool lacks both actions() and groundActions().

**Comment by Timer** [comment]
Added actions and inventoryActions

**Comment by IITC** [comment]
Awesome, thanks.
