### ISSUE TITLE
Item#actions() and Item#groundActions() switched RT6

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#871]
Item#actions() returns ground actions and #groundActions() return backpack actions.

**Comment by Timer** [comment]
Is this still an issue?

**Comment by ArtificialPB** [comment]
Yes, it still happens.

**Comment by Timer** [comment]
I don't mean to pester, but is this still an issue?
Did they change the opcodes in game?

**Comment by ArtificialPB** [comment]
Yes it's still an issue. If I dump item definitions from cache it shows correct actions. Opcodes I use:
* Ground actions opcodes -> 30-34
* Backpack actions opcodes -> 35-39

**Comment by Timer** [comment]
Fixed.
