### ISSUE TITLE
Linux Support v7

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#882]
Support for using the linux loader as the main rs loader only supports windows and OSX, to my testing.

**Comment by Timer** [comment]
@Paris see https://github.com/HikariKnight/rsu-client/

**Comment by Paris** [comment]
It works fine on Ubuntu, can you please give details of your OS and Java version.

**Comment by IITC** [comment]
That's very weird how it works on Ubuntu but not my OS.

OS: elementary OS v 0.2.1 (64-bit)
Java: 1.8.0_45-b14

**Comment by IITC** [comment]
For the record, it loads just fine but the UI is "frozen". Only the file/help menus are responsive while other menus and the applet and unresponsive.

**Comment by IITC** [comment]
v7 supports loading on linux just fine for me.
