### ISSUE TITLE
Additional Item parameters

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#887]
Requested parameters:
* Special attack boolean and required adrenaline

Special attack info is found under additional parameters in opcode ```249```. Parameter ```4332``` is the required adrenaline number. If the item is a cosmetic override (or lent, etc..), it's adrenaline value can be found by checking item with ID found under parameter ```4338``` (this is the parent item ID from which it possesses special attack, if any).

If anyone has any other requests regarding items, post them here and I'll add them to this post.

**Comment by Strikegently** [comment]
I thought this was in v7 already, but apparently it isn't. Same for #880.
We're already pulling item definitions from the cache, so it shouldn't be difficult to add these methods.

**Comment by ArtificialPB** [comment]
Merged this request with https://github.com/powerbot/powerbot/issues/880.

**Comment by Timer** [comment]
Many of these can be found by using [Ground]Item#unsafeConfig in rt4 and rt6, I updated @ArtificialPB's list according to what is already available.

**Comment by Timer** [comment]
cool!
