### ISSUE TITLE
Possibly expand web communications?

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#888]
I'm running into a dilemma with sending script info to my database(s). Either HttpURLConnection#setRequestMethod(String) or HttpURLConnection#getReponseCode() are not able to be called with the current security manager settings (I can't check atm since the client is down). I don't think I'm up-to-date on security issues with these methods so I'd appreciate some insight, and if possible, whitelisting of these methods. I don't believe either of these methods are dangerous in any way and are used to properly send data to databases and retrieve response codes to ensure the call went through.

**Comment by Paris** [comment]
These methods are not blocked, you just need to ensure that keep alive is disabled for those particular requests.

To do this add a request property `Connection: close` before making the connection.
