### ISSUE TITLE
Setting input to current switches to the other option v7

### ISSUE THREAD

**Issue by Logicail** [powerbot/powerbot#895]
Input > "Allow" is enabled
* Options > Allow

Options > "Block" is enabled

Only minor issue

**Comment by Timer** [comment]
This doesn't happen for me on OS X, is this a Windows specific problem @Strikegently?

**Comment by Timer** [comment]
Oh, this isn't really an issue as much as intended functionality.
If you uncheck block, allow will obviously become checked.
