### ISSUE TITLE
Further Abstract Game Data Objects

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#905]
Would it be possible to create an abstraction layer beneath all respective entities for rt4 and rt6 and some method classes so that script writers could create frameworks that support both game types? I understand creating the entire api to be cross-compatible is a stretch but if the core objects and some method classes could have some underlying object that's cross compatible, it would reduce redundant code. Even if classes couldn't be completely mimicked, if there are some persistent methods, it would be very beneficial. You could even accomplish this by creating interfaces and just adding them to both classes, to make it easy, and that layer could be used for cross-compatible utilities. 

Examples: 
A skills tracker. The structure of the Skills class for both rt4 and rt6 are identical, besides their actual implementation. 
A custom Actor interaction system. Basic interaction module that would turn camera, walk, etc.. then interact with the Actor.
Walking. Walking methods are pretty much identical for both game types.

**Comment by Timer** [comment]
We proposed this in the beginning of v6 and decided against it. There will be absolutely no unified API methods.
