### ISSUE TITLE
familiarInventory() methods returning incorrectly.

### ISSUE THREAD

**Issue by Revertion** [powerbot/powerbot#907]
ctx.summoning.familiarInventory.opened() isn't returning correctly. The widgets may have changed. I'd also like to suggest implementing a more extensive method to store items in a BoB familiar. Currently the method store will only store an item and you cannot choose the amount of the item you wish to store.

**Comment by Timer** [comment]
I need these ids, none of our staff has a BoB.

**Comment by Timer** [comment]
Works fine for us.
