### ISSUE TITLE
Camera#x(), y() and z()

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#909]
Request for the above methods for v7 rt6.

**Comment by Strikegently** [comment]
Angle, pitch, yaw.

**Comment by Timer** [comment]
What do you need these for?

**Comment by ArtificialPB** [comment]
Tbh I would only need z() and that's because of view distance calculations.

**Comment by Timer** [comment]
View distance calculations have since been added to RSBot.

**Comment by ArtificialPB** [comment]
I don't think I was clear enough with my previous post. I calculate current view distance and the distance at which the desired object is. I use that to calculate the needed pitch and angle to bring that object in to the view.
