### ISSUE TITLE
v6 CombatBar

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#910]
Widgets changed with the update this morning. 
You can have multiple combat bars open at once now, so it might complicate things a little bit.

High priority fix.

**Comment by Strikegently** [comment]
Widget: 1430

Health text: 4, 7
Prayer text: 11, 7
Quick prayer orb: 12
Summoning text: 17, 7
Summoning orb: 18
Retaliate button: 49

Ability setting: 739

**Comment by Timer** [comment]
Fixed
