### ISSUE TITLE
Hud.Window.WORN_EQUIPMENT partialy broken

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#912]
Checking if the above window is opened works when equipment interface is like this:
![worksgear](https://cloud.githubusercontent.com/assets/4672155/9454030/32ac6f0c-4abf-11e5-893c-f3fb17488b1c.png)

But does not work if a player has interface like this:
![brokengear](https://cloud.githubusercontent.com/assets/4672155/9454036/46329c54-4abf-11e5-9edd-84786aca2484.png)
![brokengear1](https://cloud.githubusercontent.com/assets/4672155/9454037/46343e74-4abf-11e5-8112-f73be58be9d6.png)

**Comment by Timer** [comment]
Fixed.
