### ISSUE TITLE
GameObject#getArea and readjusted base tile for Multi-tiled GameObjects

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#915]
Currently, as far as I'm aware, the base tile for multi-tiled game objects is the NW tile. Other clients use the SW tile as the base. The SW tile would make more sense in relevance to the way the rs grid is laid out. Also, knowing the width and height of a GameObject in tiles would be fantastic. There's an instance of each GameObject for each tile it takes up (same object) so it'd be quite easy to gather the area.

**Comment by Timer** [comment]
Tiles are given as provided from the game itself -- so I will not change this behavior. However, I will add width and height.

**Comment by Timer** [comment]
Done.
