### ISSUE TITLE
Menu commands changing

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#921]
When you're hovering certain npcs it's actions are constantly changing order in the menu. Here's a gif of the issue:
https://gyazo.com/897a8b9b01c08f6946668d1f8422a73a

This is RT6

**Comment by Timer** [comment]
This cannot be fixed.

**Comment by ArtificialPB** [comment]
Alright, noted.

**Comment by Timer** [comment]
@ArtificialPB: upon right click the menu should become fixed -- but this is a byproduct of reflection.

**Comment by ArtificialPB** [comment]
It does become fixed, but the main reason I reported this is because I don't want it to always right click due to patternisation. I'll think of something else to remedy this. @Timer

**Comment by Timer** [comment]
Oh this is happening in v6? It really shouldn't be -- I don't want to focus on a fix for v6 because v7's due date is today.

**Comment by ArtificialPB** [comment]
Yeah no worries. I'll let you know if this also happens in v7 as soon as the update is finished being processed so I can debug.
