### ISSUE TITLE
Non-primary action bars report wrong IDs

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#924]
i.e. user has action bar 2 enabled, it still returns the IDs for action bar 1.

![](http://i.imgur.com/QWG5p97.png)
![](http://i.imgur.com/WrtZsAM.png)

varps for IDs starts at 739 and are offset by 12 (length of each action bar).
So slot 1 for action bar 1 is 739
slot 1 for action bar 2 is 751, 763 for action bar 3, etc. 

By default, there are 6 action bars, though you can purchase more in the store. I don't see a need to support anything more than 6, but that's your call.

The current action bar index is ((varp 682 >> 5) & 0x7)

so 739 + ((action bar index - 1) * 12) + slot

**Comment by Timer** [comment]
Done.
