### ISSUE TITLE
Make calculating Targetable#nextPoint() faster

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#925]
Calculating nextPoint() is really slow in v7. This is because Hud#bounds() takes a lot of time to execute. I've noticed it caches those bounds for 1 second before re-calculating them again. That's usually not enough because a lot of scripts interact while in motion and this prevents it doing that, because by the time a point is calculated, the object on screen already changed its position so it usually only interacts successfully while the player is not moving which is very bot-like imo. 

Here are a few suggestions to make it faster:
* Recalculate Hud bounds when either Hud#open() or Hud#close() is called, or when client dimensions change. Once the script is started, hud location and bounds don't usually changed with the exception when calling any of the Hud#open()/close() methods.
**EDIT**: When any of these methods get called you could fire the bounds() method on a new worker thread. That way there wont even be any delay when interacting with Huds.

* Make a worker thread that constantly recalculates bounds in the background.

**Comment by Timer** [comment]
The bounds also accounts for other things like popups, etc, so I cannot have it only update when you open or close something.

**Comment by Timer** [comment]
I'll spin it in the background.

**Comment by Timer** [comment]
Done.
