### ISSUE TITLE
getRunPercentage RuntimeException

### ISSUE THREAD

**Issue by CodeRedRS** [powerbot/powerbot#934]
java.lang.RuntimeException: Config missing for getRunPercentage 
	org.powerbot.bot.Con.null(oo:7)
	org.powerbot.bot.Con.null(oo:171)
	org.powerbot.bot.rt4.client.Client.getRunPercentage(o:486)
	org.powerbot.script.rt4.Movement.energyLevel(kc:3)
	q.a(q.java:21)
	s.poll(s.java:107)
	org.powerbot.script.PollingScript$6.run(gg:205)

**Comment by Timer** [comment]
Merging this into #939.
