### ISSUE TITLE
Fix advertisement display issue

### ISSUE THREAD

**Issue by Timer** [powerbot/powerbot#935]
Advertisements still display for F2P users on windows

**Comment by Timer** [comment]
http://tinypic.com/view.php?pic=lbktv&s=8#.VgVzL49Viko

**Comment by AzDeRi** [comment]
they do not show on dev mode

**Comment by PatriqDesigns** [comment]
They do for me in RT4

**Comment by R3dundant** [comment]
In reference to this issue, this also happens when trying to open up a 4th client window making it impossible to run more than 3 bots currently.
![untitled](https://cloud.githubusercontent.com/assets/4537895/10320985/526c2f66-6c44-11e5-8709-3c89a26e66a9.png)

**Comment by warx1a** [comment]
This also will offset the painting and offsets many of the items under the View tab in the client. Also makes it impossible to draw in the bottom of the client.

**Comment by Paris** [comment]
Use correct offsets for mouse events for when the surrounding components aren't hidden.

**Comment by Paris** [comment]
The next version will allow ads to be shown if they pop-up during gameplay but instead adjust the paints and mouse events so they produce the correct result.
