### ISSUE TITLE
Config missing for getRunPercentage

### ISSUE THREAD

**Issue by AzDeRi** [powerbot/powerbot#939]
```
 java.lang.RuntimeException: Config missing for getRunPercentage 
 org.powerbot.bot.Con.null(fk:152)
 org.powerbot.bot.Con.null(fk:122)
 org.powerbot.bot.rt4.client.Client.getRunPercentage(l:308)
 org.powerbot.script.rt4.Movement.energyLevel(kc:59)
 org.powerbot.script.rt4.TilePath.traverse(xb:132)
 org.powerbot.script.rt4.Path.traverse(sb:169)
```

**Comment by hilolhi** [comment]
how do i fix this?? got any tips or link to fix?

**Comment by AzDeRi** [comment]
best you can do atm is turn run on and run only scripts that do not burn it down to 0

**Comment by hilolhi** [comment]
Thats the problem am doing rocky crabs str training


Verzonden vanaf mijn Samsung Galaxy-smartphone.<div>
</div><div>
</div><div>-------- Oorspronkelijk bericht --------</div><div>Van: AzDeRi <notifications@github.com> </div><div>Datum: 27-09-2015  14:15  (GMT+01:00) </div><div>Aan: powerbot/powerbot <powerbot@noreply.github.com> </div><div>Cc: hilolhi <emrreaksuu@hotmail.com> </div><div>Onderwerp: Re: [powerbot] [OSRS] out of energy/run off causes crash (#939) </div><div>
</div>
best you can do atm is turn run on and run only scripts that do not burn it down to 0

---

**Comment by CodeRedRS** [comment]
A temporary solution for enabling run is to check the widget text value.

This checks if your energy level is greater than 25-35.
Integer.parseInt(ctx.widgets.widget(160).component(23).text()) > Random.nextInt(25, 35)

This checks if run is disabled
ctx.widgets.widget(160).component(24).textureId() == 1064

I hope this helps for the time being.

**Comment by Timer** [comment]
Fixed.

**Comment by hilolhi** [comment]
Ah nice man thats fast thankyou fot fast responds


Verzonden vanaf mijn Samsung Galaxy-smartphone.<div>
</div><div>
</div><div>-------- Oorspronkelijk bericht --------</div><div>Van: Joe Haddad <notifications@github.com> </div><div>Datum: 28-09-2015  06:51  (GMT+01:00) </div><div>Aan: powerbot/powerbot <powerbot@noreply.github.com> </div><div>Cc: hilolhi <emrreaksuu@hotmail.com> </div><div>Onderwerp: Re: [powerbot] Config missing for getRunPercentage (#939) </div><div>
</div>
Fixed.

---
