### ISSUE TITLE
ctx.bank.close()

### ISSUE THREAD

**Issue by MookyMan** [powerbot/powerbot#945]
Freezes my paint and this makes `interact()` not work, only sometimes though.
Once the paint is frozen it won't disappear after stopping the script or restarting it, and the new script won't even paint anything.

More info here: http://www.powerbot.org/community/topic/1284508-osrs-ctxbankopen/

**Comment by Timer** [comment]
You clean ctx.bank.close()?

**Comment by AzDeRi** [comment]
confirming that sometimes script crashes and forces to restart the whole botclient.
Paint freezes; stopping the script does not make paint go away and prevents the script from opening bank again (mouse keeps wiggling on the bank booth but does not click).

will post log information when re-occurs.

**Comment by Timer** [comment]
Our API doesn't have a `ctx.bank.open()`? What are you guys talking about?

**Comment by AzDeRi** [comment]
http://puu.sh/kpZSw/1e656e58cb.jpg
script stopped, paint frozen.
http://puu.sh/kpZXQ/44dfd02bdc.png
whole client does not respond to anything but playerclicks

**Comment by AzDeRi** [comment]
oh and log does not say no nothing

**Comment by Timer** [comment]
???

**Comment by AzDeRi** [comment]
no idea if it's bank-related in any way because log does not give any information.
Paint freezes, client "view" settings do not work, and scripts keep hovering on banker and after stopping the current one, new ones won't start unless you restart the whole client.

**Comment by Timer** [comment]
What method are you using?

**Comment by AzDeRi** [comment]
so far i have ran into this only with Mooky's wine script.

**Comment by Timer** [comment]
@MookyMan are you talking about `ctx.bank.close()` or `ctx.bank.open()`?

**Comment by AzDeRi** [comment]
I don't know if it's problem with either. seems to happen with other SDN scripts too (xchopper).

**Comment by AzDeRi** [comment]
Wine scripts keeps spamming 
1440 (00:32:23) Running: BankDrinkWine
1440 (00:32:28) Running: BankDrinkWine
1440 (00:32:33) Running: BankDrinkWine

**Comment by MookyMan** [comment]
Ah yeah sorry it was bank.close()

Changing it to ctx.input.click(BANK_CLOSE_WIDGET, true) fixes the issue.

**Comment by Timer** [comment]
Odd, because that method isn't recursive at all...
```java
	public boolean close() {
		return !opened() || (ctx.widgets.widget(Constants.BANK_WIDGET).component(Constants.BANK_MASTER).component(Constants.BANK_CLOSE).interact("Close") && Condition.wait(new Condition.Check() {
			@Override
			public boolean poll() {
				return !opened();
			}
		}, 30, 10));
	}
```

**Comment by Timer** [comment]
Is the mouse moving when it locks up?

**Comment by MookyMan** [comment]
Yes, but it can only do ctx.click.

widget.interact() after it locks up the mouse overs the widget but never clicks it

**Comment by Timer** [comment]
Does it ever stop trying?

**Comment by MookyMan** [comment]
Um I've never let it run for a long time sorry

**Comment by Timer** [comment]
I changed it to click.

**Comment by AzDeRi** [comment]
ps. never stops trying
