### ISSUE TITLE
Reflection failing to grab loaded classes

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#950]
1058 java.lang.NullPointerException 
	org.powerbot.bot.rt6.Com2.void(ef:68)
	org.powerbot.bot.Nul.run(qf:49)

Happens with multiple game packs, if not all.

**Comment by ChrisBPB** [comment]
seems to be unique to windows from what I can tell

**Comment by Ragezors** [comment]
Not unique to Windows:

[SEVERE] java.lang.NullPointerException 
	org.powerbot.bot.rt6.Com2.void(ef:68)
	org.powerbot.bot.Nul.run(qf:49)
Error: client.init:1058 sun.reflect.NativeMethodAccessorImpl.invoke0 sun.reflect.NativeMethodAccessorImpl.invoke:62 sun.reflect.DelegatingMethodAccessorImpl.invoke:43 java.lang.reflect.Method.invoke:497 Rs2Applet.a:18 Rs2Applet.init:414 app.appletviewer.a jagexappletviewer.main:34 | java.lang.RuntimeException | 

Popped up on OSX Yosemite 10.10.5 when running the client.

**Comment by Timer** [comment]
@Paris damn your code! jk love u bae

**Comment by Ciaran96** [comment]
Any idea when the bot will be fixed?

**Comment by Timer** [comment]
Tonight when I get home from school.

**Comment by Ciaran96** [comment]
Alright, glad to see admins/moderators who are dedicated for once:)

**Comment by Timer** [comment]
Fixed.
