### ISSUE TITLE
Paint will freeze

### ISSUE THREAD

**Issue by NexPB** [powerbot/powerbot#953]
Paint will sometimes freeze no idea what's causing it yet.

I asked around someone had this happen aswell, seems like this happens when banking or something:

![bug](https://i.gyazo.com/dd6c9581d539a8f7063103f85387c376.png)

**Comment by Timer** [comment]
@Strikegently probably related to your inventory code freezing

**Comment by Strikegently** [comment]
@NexPB I have a hunch about this. Can you post a gist of your paint? You can shoot it to me on Skype if you don't want it public for whatever reason.

**Comment by Timer** [comment]
@Strikegently keep me in the loop

**Comment by Strikegently** [comment]
The only connection I've been able to find is the frequency of banking. 
Testing with a script that banks very infrequently, no problems in over 10 hours of continuous testing.
Testing with a script that banks more frequently, the inventory monitor thread freezes after some time.

I talked to @NexPB about it, and he reported similar findings. My "hunch" was wrong, and our findings only make me more confused.

**Comment by Strikegently** [comment]
Any update?

**Comment by Paris** [comment]
@NexPB can you check the comments above please, does this still happen?

**Comment by NexPB** [comment]
@Paris Yes this still happens.

@Strikegently Here is my paint class https://gist.github.com/NexPB/8dc08f610753d61457a5

**Comment by Timer** [comment]
Merging into #1075
