### ISSUE TITLE
GameObjects have the wrong name

### ISSUE THREAD

**Issue by CodeRedRS** [powerbot/powerbot#958]
![Bank name shows as "Chair"](http://puu.sh/krYVb/1386c84266.jpg)

Bank Booth is showing up as Chair

**Comment by Timer** [comment]
Does restarting the client fix this?

**Comment by CodeRedRS** [comment]
No. I've tried a few times of closing and opening the client.

**Comment by Timer** [comment]
Okay. looking into this.

**Comment by CodeRedRS** [comment]
Okay I've run around a little bit and it doesn't seem to be all objects, just a few are wrong.
![Correct GameObjects](http://puu.sh/ks0yH/db666a2456.jpg)

**Comment by Timer** [comment]
fixed
