### ISSUE TITLE
Not attaching/loading to game

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#960]
Can't reproduce myself but I teamviewed someone on OSX and [they had this issue](http://www.powerbot.org/community/topic/1284823-not-able-to-choose-osrs-option-when-downloading-powerbot-client/#entry15586953
), but it worked for OSRS (running dev mode, switch manually). So I assume unique to RS3.

**Comment by ChrisBPB** [comment]
someone on mac has this issue with both osrs and rs3, so might be on both

**Comment by Timer** [comment]
The javaagent part would obviously happen to both types of games, @ChrisBPB. ;)
But @Paris, this issue seems independent of possibly having spaces in the file path -- I wonder what could be going wrong ...

**Comment by ChrisBPB** [comment]
I know but the guy I teamviewed only had the issue on RS3

**Comment by ChrisBPB** [comment]
someone I teamviewed had this issue on mac (both rs3 and osrs) and

RS3 threw this error:
Error: client.init:1251 sun.reflect.NativeMethodAccessorImpl.invoke0 sun.reflect.NativeMethodAccessorImpl.invoke:62 sun.reflect.DelegatingMethodAccessorImpl.invoke:43 java.lang.reflect.Method.invoke:497 Rs2Applet.a:27 Rs2Applet.init:428 app.appletviewer.a jagexappletviewer.main:34 | java.lang.RuntimeException | 


OSRS threw this:
[SEVERE] java.lang.ExceptionInInitializerError 
	z.Q.run(pg:172)


After restarting RS3 continue to throw the error, OSRS stopped - and they both started showing the RSBot options regardless :s

**Comment by Timer** [comment]
hm
```
[SEVERE] java.lang.ExceptionInInitializerError 
org.powerbot.gui.BotChrome.run(BotChrome.java:76)
```

**Comment by Timer** [comment]
Ah! What is the directory of their cache, @ChrisBPB?
I assume
```java
	public static final CacheWorker CACHE_WORKER = new CacheWorker(new File(
			System.getProperty("user.home"), "jagexcache/oldschool/LIVE"
	));
```

**Comment by ChrisBPB** [comment]
I'll ask them when they're on, but it should be that

**Comment by ChrisBPB** [comment]
that's the correct cache directory

**Comment by Timer** [comment]
Fixed
