### ISSUE TITLE
Sort scripts by manifest name, rather than class name.

### ISSUE THREAD

**Issue by Strikegently** [powerbot/powerbot#968]
Right now, local scripts are sorted by their class name. Would it be possible to make them sorted by their manifest name?
It makes finding a specific script a lot easier, and a lot quicker.

**Comment by Paris** [comment]
Done

**Comment by Strikegently** [comment]
@Paris 
Can you make it show local scripts first, but still sorted by manifest name?

**Comment by Paris** [comment]
Done for next version.
