### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AzDeRi** [powerbot/powerbot#977]
happens randomly, simultaneously on all bots

[SEVERE] java.lang.NullPointerException 
	org.powerbot.script.rt4.Objects.get(oc:108)
	org.powerbot.script.rt4.Objects.get(oc:148)
	org.powerbot.script.AbstractQuery.select(hb:226)
	o.a(o.java:32)
	s.poll(s.java:84)
	org.powerbot.script.PollingScript$6.run(mn:249)

**Comment by Timer** [comment]
Fixed.
