### ISSUE TITLE
[Severe] Class loader denied

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#979]
No error outputted, just that. Happens randomly - more commonly when interacting with something (via interact or click) but also when just peek'ing at an object

not sure if it's just objects or not, it's hard to reproduce reliably 

rt4

**Comment by ArtificialPB** [comment]
Also happens in rt6, with no noticeable effect on scripts.

**Comment by ChrisBPB** [comment]
the script doesn't continue to function because it can't interact with the object - be it a bank, larder, range, fire

**Comment by ArtificialPB** [comment]
It maybe pauses execution for a couple of seconds but it executes it eventually.

**Comment by ChrisBPB** [comment]
it may be different on rt4 then because it never moves past it and will just continue to flood the log with that and never move on

**Comment by Timer** [comment]
Fixed.
