### ISSUE TITLE
Change the "Options" item to a MenuItem instead of Menu

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#985]
This will allow the "Options" item to behave as it did in RSBot 6.

```
    @Override
    public void actionPerformed(ActionEvent e) {
        Menu menu = new Menu(getName());
        MenuItem showStackTrace = new MenuItem("[DEBUG] Show Stack Trace");

        showStackTrace.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, new Object[] { mainThread.getStackTrace() });
            }
        });

        menu.add(showStackTrace);
        ((Menu) ((MenuItem) e.getSource()).getParent()).add(menu);
    }
```

After clicking "Options" to fire the event it creates an item like so:

![image](https://cloud.githubusercontent.com/assets/6828951/10402218/05201d3a-6e92-11e5-93b9-4ea17bb40fef.png)

**Comment by AnthonyOSX** [comment]
If you're using the above code please keep in mind you need to handle removing the added Menu on script stop as well as make sure clicking "Options" multiple times does not make multiple menus.

**Comment by IITC** [comment]
It's a BotMenuActionListener for a reason and not a BotMenuListener. I believe the functionality you speak of was not intended. Maybe they want you to pop up a GUI to edit options.

**Comment by AnthonyOSX** [comment]
@IITC That's offaly redundant considering your script will pop up a GUI without user interaction during startup if need be. The whole point to the options menu was to allow for simplified settings toggling. This new method only limits what can be done.

**Comment by IITC** [comment]
Regardless, the interface is BotMenu"Action"Listener, not BotMenuListener. Just wait until they respond. I do agree it should be a menu and not menu item.

**Comment by IITC** [comment]
Some people allow script changes during runtime and they may want you to do it through a separate GUI. I kinda like it because I can just spawn a new frame in my paint framework. Lol

**Comment by Paris** [comment]
This isn't possible since the game window uses AWT not Swing.
