### ISSUE TITLE
Repainting Issues [Linux]

### ISSUE THREAD

**Issue by IITC** [powerbot/powerbot#987]
Script PaintListeners continue to paint after being shutdown. @Timer, you have access to my repo. The source is there and the test class is https://github.com/IITC/powerbot/blob/master/src/iitc/rsbot/script/Flaxer.java.

Using elementaryOS.

Here's all the shit you probably need.

dimensions:    3840x1080 pixels (1016x286 millimeters)
Name: Mutter(Gala)
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Stepping:              9
CPU MHz:               1200.000
BogoMIPS:              4589.60
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-7

**Comment by IITC** [comment]
Actually, no clearing happens. lol 

[img]http://i.imgur.com/4XDvSD2.png[/img]

**Comment by IITC** [comment]
Another example:

![Image of Painting](http://i.imgur.com/Rqvep19.png)

**Comment by Timer** [comment]
Merging this into #778
