### ISSUE TITLE
Not compatible if C:\ isn't main drive?

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/powerbot#988]
User has RS installed to D:\ and it just constantly says he has no cache - I copied the cache from D to C and that stopped saying that but he still can't use RSBot because it says unable to create advertising

He has tried 64 bit and 32 bit java, and also has the latest rs client installed.  They could be unrelated issues but I think they are linked. The real RS does not give the advertising error.

**Comment by Paris** [comment]
Note: find RS launcher install path via registry instead of using hardcoded default path in user folder.

**Comment by Paris** [comment]
Fixed for next version.
