### ISSUE TITLE
[Old School] Rooftop object models offset

### ISSUE THREAD

**Issue by AnthonyOSX** [powerbot/powerbot#989]
![image](https://cloud.githubusercontent.com/assets/6828951/10411738/a198f726-6f3d-11e5-859c-317c853b5428.png)

![image](https://cloud.githubusercontent.com/assets/6828951/10411775/61f98d72-6f3f-11e5-97ef-625bc3da8d18.png)

Makes it nearly impossible for the bot to click the object.

**Comment by ChrisBPB** [comment]
>won't set bounds
>calls it broken

**Comment by AnthonyOSX** [comment]
@ChrisBPB No other OSRS bot has this issue.

**Comment by ChrisBPB** [comment]
they use models, we usin' bounds

**Comment by Timer** [comment]
Set the bounds.

**Comment by AnthonyOSX** [comment]
@Timer hook models.

**Comment by Timer** [comment]
@AnthonyOSX no

**Comment by AnthonyOSX** [comment]
@Timer every other OSRS bot has them hooked, why you lagging behind?

**Comment by Timer** [comment]
It's not lagging if they're unnecessary @AnthonyOSX, so stop being lazy.

**Comment by AnthonyOSX** [comment]
@Timer Yes, doing your job for you is being "lazy".

**Comment by Timer** [comment]
Go learn how to retrieve models (without injection), write the code, and I'll gladly implement it. It's not worth the time.

**Comment by Timer** [comment]
@AnthonyOSX
