### ISSUE TITLE
NPC.interacting never returns the local player

### ISSUE THREAD

**Issue by sethrem** [powerbot/powerbot#995]
for (Npc npc2 : ctx.npcs.select()) {
			if (npc2.interacting().equals(ctx.players.local())) {
				System.out.println("Interacting with an npc!!");
			} else {
				if (!npc2.interacting().name().equalsIgnoreCase("")) {
					System.out.println(npc2.interacting().name());
				}
			}
		}

Never prints "Interacting with an npc!!" but will always print other players names who are interacting with npc's. (I'am/was indeed interacting with an npc) (tested lots of times)

**Comment by Timer** [comment]
fixed.
